import { useEffect, useState } from 'react';
import { AdminShell, Message } from './AdminShell.jsx';
import { adminJson, api, requireAdmin } from './adminApi.js';
export function AdminCertificationsPage(){
  const [data,setData]=useState({certificates:[],courses:[],total:0}),[page,setPage]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[courseId,setCourseId]=useState(''),[policy,setPolicy]=useState(null),[reason,setReason]=useState(''),[filter,setFilter]=useState('all'),[search,setSearch]=useState('');
  async function load(){if(!requireAdmin())return;setBusy(true);try{setData(await adminJson(`/api/admin/certifications?page=${page}`));}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  useEffect(()=>{document.title='Certification | Skillomate';load();},[page]);
  useEffect(()=>{let active=true;setPolicy(null);if(courseId)adminJson(`/api/admin/certification-policy/${courseId}`).then(value=>{if(active)setPolicy({questions:value.questions,durations:value.course.videos.map(v=>Number(v.duration)||0),videos:value.course.videos});}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[courseId]);
  async function save(e){e.preventDefault();setBusy(true);try{const result=await adminJson(`/api/admin/certification-policy/${courseId}`,{method:'PUT',body:JSON.stringify({durations:policy.durations,questions:policy.questions})});setMessage(result.message);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  async function change(cert){const action=cert.status==='revoked'?'restore':'revoke';if(reason.trim().length<5){setMessage('Enter an audit reason of at least five characters.');return;}if(!window.confirm(`${action==='revoke'?'Revoke':'Restore'} certificate ${cert.certificateId}?`))return;setBusy(true);try{await adminJson(`/api/admin/certifications/${cert.certificateId}`,{method:'PATCH',body:JSON.stringify({action,reason})});setReason('');await load();setMessage('Certificate updated. The action and reason were recorded.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  function question(i,patch){setPolicy(p=>({...p,questions:p.questions.map((q,k)=>k===i?{...q,...patch}:q)}));}
  const visibleCertificates=(data.certificates||[]).filter(c=>{const haystack=[c.learnerName,c.courseTitle,c.certificateId,c.status].join(' ').toLowerCase();return (filter==='all'||c.status===filter)&&(!search.trim()||haystack.includes(search.trim().toLowerCase()));});
  const revoked=(data.certificates||[]).filter(c=>c.status==='revoked').length;
  const pending=(data.progress||[]).filter(item=>!item.eligible).length;
  return <AdminShell activePage="certifications" title="Certification" subtitle="Manage completion criteria, optional assessments and issued certificates." actions={<button className="toolbar-button" disabled={busy} onClick={load}>Refresh</button>}>
    <Message text={message} type="success"/>
    <section className="summary-grid admin-v2-summary"><div className="summary-card"><strong>Certificates issued</strong><span>{data.total}</span><small>Total certificate records</small></div><div className="summary-card"><strong>Pending requests</strong><span>{pending}</span><small>Completion rows not eligible yet</small></div><div className="summary-card"><strong>Revoked certificates</strong><span>{revoked}</span><small>Audit required</small></div><div className="summary-card"><strong>Conversion</strong><span>{data.progress?.length?Math.round(((data.total||0)/data.progress.length)*100):0}%</span><small>Completion to certificate</small></div></section>
    <section className="health-intro"><div><h2>Completion policy</h2><p>Every lesson requires 90% tracked coverage. Learners need a verified mobile number and a profile name. Optional assessments require 70%. Changing durations or questions starts a new criteria version. Existing certificates remain valid.</p></div></section>
    <h2 className="admin-section-heading">Course criteria & assessment</h2>
    <label>Course <select value={courseId} onChange={e=>setCourseId(e.target.value)}><option value="">Choose a course</option>{data.courses.map(c=><option value={c._id} key={c._id}>{c.title}</option>)}</select></label>
    {policy?<form onSubmit={save} className="certification-editor"><h3>Trusted lesson durations</h3><p>Enter actual durations in seconds. Missing durations block certification.</p>{policy.videos.map((v,i)=><label key={v._id||i}>{v.title||`Lesson ${i+1}`}<input type="number" required min="1" max="86400" step="any" value={policy.durations[i]} onChange={e=>setPolicy(p=>({...p,durations:p.durations.map((d,k)=>k===i?Number(e.target.value):d)}))}/></label>)}
      <h3>Final assessment (optional)</h3><p>No questions means a completion-only certificate.</p>
      {policy.questions.map((q,i)=><fieldset key={i}><legend>Question {i+1}</legend><label>Question<input required maxLength={1000} value={q.prompt} onChange={e=>question(i,{prompt:e.target.value})}/></label>{q.options.map((o,j)=><label key={j}>Choice {j+1}<input required maxLength={300} value={o} onChange={e=>question(i,{options:q.options.map((value,k)=>k===j?e.target.value:value)})}/></label>)}<label>Correct choice<select value={q.answer} onChange={e=>question(i,{answer:Number(e.target.value)})}>{q.options.map((_,j)=><option value={j} key={j}>{j+1}</option>)}</select></label><button type="button" className="toolbar-button" onClick={()=>setPolicy(p=>({...p,questions:p.questions.filter((_,k)=>k!==i)}))}>Remove question</button></fieldset>)}
      <div className="toolbar-actions"><button type="button" className="toolbar-button" disabled={policy.questions.length>=30} onClick={()=>setPolicy(p=>({...p,questions:[...p.questions,{prompt:'',options:['','','',''],answer:0}]}))}>Add question</button><button className="toolbar-button" disabled={busy}>Save criteria</button></div>
    </form>:null}
    <h2 className="admin-section-heading">Recent learner completion</h2><div className="health-check-grid">{(data.progress||[]).map((item,i)=><article className="health-check" key={`${item.courseId}-${i}`}><h3>{item.learnerName}</h3><p>{item.courseTitle} · {item.completedLessons}/{item.totalLessons} lessons</p><p>{item.eligible?'Eligible for certificate':item.requirements.join(' ')}</p></article>)}</div>{!data.progress?.length?<p>No verified playback records yet.</p>:null}
    <h2 className="admin-section-heading">Issued certificates · {data.total}</h2><div className="controls-panel"><div><label>Search certificate</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Learner, course, certificate ID"/></div><div><label>Status</label><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="issued">Issued</option><option value="revoked">Revoked</option><option value="pending">Pending</option></select></div><div><label>Audit reason for revoke / restore</label><input value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder="Explain why the certificate needs to change"/></div></div>
    <div className="health-check-grid" style={{marginTop:16}}>{visibleCertificates.map(c=><article className="health-check" key={c.certificateId}><div className="health-check-heading"><h3>{c.learnerName}</h3><span className={`health-badge ${c.status==='revoked'?'error':'healthy'}`}>{c.status}</span></div><p>{c.courseTitle}</p><p>{new Date(c.issuedAt).toLocaleDateString()} · {c.courseVersion?'Current criteria':'Legacy record'}</p><small>{c.certificateId}</small><div className="toolbar-actions"><a className="toolbar-button" href={api(`/api/certificates/verify/${c.certificateId}`)} target="_blank" rel="noreferrer">View / Download</a><button className="toolbar-button" disabled={busy}>Reissue</button><button className="toolbar-button" disabled={busy} onClick={()=>change(c)}>{c.status==='revoked'?'Restore':'Revoke'}</button></div>{c.audit?.length?<details><summary>Audit history</summary>{c.audit.map((a,i)=><p key={i}>{new Date(a.at).toLocaleString()} · {a.action}: {a.reason}</p>)}</details>:null}</article>)}</div>
    {!visibleCertificates.length?<p>No certificates match this view.</p>:null}<div className="health-controls"><button disabled={busy||page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page}</span><button disabled={busy||page*25>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>
  </AdminShell>;
}
