/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Skillomate AI - About`,
  lang: `en`,
  stylesheets: [],
  styles: `
    :root {
      --about-bg: #F8FAFC;
      --about-bg-soft: #F8FAFC;
      --about-panel: #F1F5F9;
      --about-card: #FFFFFF;
      --about-card2: #FFFFFF;
      --about-nav-bg: #F8FAFC;
      --about-border: #E2E8F0;
      --about-border2: #CBD5E1;
      --about-text: #0F172A;
      --about-heading: #0F172A;
      --about-text2: #475569;
      --about-muted: #94A3B8;
      --about-gold: #C58B2A;
      --about-gold-dark: #C58B2A;
      --about-gold-soft: #F1F5F9;
      --about-gold-border: #E2E8F0;
      --about-shadow: 0 14px 36px rgba(15, 23, 42, .08);
      --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif;
      --font-display: "Fraunces", Georgia, serif;
    }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; overflow-x: hidden; background: var(--about-bg); }
    body {
      min-height: 100vh;
      overflow-x: hidden;
      background:
        radial-gradient(circle at 14% 9%, rgba(197, 139, 42, .18), transparent 27rem),
        radial-gradient(circle at 86% 4%, rgba(197, 139, 42, .11), transparent 25rem),
        var(--about-bg);
      color: var(--about-text);
      font-family: var(--font-body);
      line-height: 1.6;
    }
    a { color: inherit; text-decoration: none; }
    img { display: block; max-width: 100%; }
    button, input { font-family: var(--font-body); }
    .container { width: min(1120px, calc(100% - 48px)); margin: 0 auto; }

    .navbar {
      position: sticky;
      top: 0;
      z-index: 50;
      background: rgba(248, 250, 252, .94);
      backdrop-filter: blur(18px);
      border-bottom: 1px solid var(--about-border);
    }
    .nav-inner {
      width: min(1120px, calc(100% - 48px));
      min-height: 70px;
      margin: 0 auto;
      display: flex;
      align-items: center;
      gap: 34px;
    }
    .nav-logo { font-size: 1.12rem; font-weight: 800; color: var(--about-heading); flex-shrink: 0; letter-spacing: -.02em; }
    .nav-logo span { color: var(--about-gold); }
    .nav-links { list-style: none; display: flex; align-items: center; justify-content: center; flex: 1; gap: 10px; }
    .nav-links a {
      position: relative;
      display: inline-flex;
      padding: 25px 8px 22px;
      color: var(--about-text2);
      font-size: .84rem;
      font-weight: 600;
    }
    .nav-links a:hover,
    .nav-links a.active { color: var(--about-heading); }
    .nav-links a.active::after {
      content: "";
      position: absolute;
      left: 8px;
      right: 8px;
      bottom: 0;
      height: 2px;
      border-radius: 99px;
      background: var(--about-gold);
    }
    .nav-right { display: flex; align-items: center; gap: 12px; flex-shrink: 0; }
    .nav-user { font-size: .8rem; font-weight: 700; color: var(--about-heading); }
    .btn-ghost {
      border: 1px solid var(--about-border);
      background: var(--about-card);
      color: var(--about-text);
      border-radius: 999px;
      padding: 8px 15px;
      font-size: .78rem;
      font-weight: 700;
      cursor: pointer;
    }
    .btn-ghost:hover { border-color: var(--about-gold-border); color: var(--about-gold-dark); }
    .nav-avatar {
      width: 34px;
      height: 34px;
      border-radius: 50%;
      overflow: hidden;
      border: 1px solid var(--about-gold-border);
      background: var(--about-gold-soft);
      display: inline-flex;
      align-items: center;
      justify-content: center;
      color: var(--about-gold-dark);
    }
    .nav-avatar img { width: 100%; height: 100%; object-fit: cover; }

    .about-page { background: transparent; }
    .hero { padding: 76px 0 42px; }
    .hero-grid {
      display: grid;
      grid-template-columns: minmax(0, .9fr) minmax(360px, 1.1fr);
      gap: clamp(36px, 7vw, 84px);
      align-items: center;
    }
    .eyebrow {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 6px 14px;
      border-radius: 999px;
      border: 1px solid var(--about-gold-border);
      background: var(--about-gold-soft);
      color: var(--about-gold-dark);
      font-size: .68rem;
      font-weight: 800;
      letter-spacing: .08em;
      text-transform: uppercase;
      margin-bottom: 25px;
    }
    .eyebrow::before {
      content: "";
      width: 5px;
      height: 5px;
      border-radius: 50%;
      background: var(--about-gold);
    }
    .hero-title {
      color: var(--about-heading);
      font-family: var(--font-display);
      font-size: clamp(3.1rem, 6vw, 5rem);
      font-weight: 600;
      letter-spacing: -.025em;
      line-height: .95;
      margin-bottom: 28px;
      max-width: 560px;
    }
    .hero-title span { color: var(--about-gold); }
    .hero-copy {
      color: var(--about-text2);
      font-size: .98rem;
      line-height: 1.85;
      max-width: 490px;
      margin-bottom: 38px;
    }
    .hero-tagline {
      display: inline-flex;
      align-items: center;
      gap: 9px;
      color: var(--about-gold-dark);
      font-weight: 800;
      font-size: .9rem;
    }
    .hero-tagline i { color: var(--about-gold); }
    .hero-image {
      height: clamp(300px, 35vw, 420px);
      border-radius: 14px;
      overflow: hidden;
      border: 1px solid var(--about-border);
      box-shadow: var(--about-shadow);
      background: linear-gradient(135deg, #FFFFFF, var(--about-panel));
      padding: 14px;
    }
    .hero-photo-row {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 12px;
      height: 100%;
    }
    .hero-photo-row img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      object-position: center top;
      border-radius: 10px;
      border: 1px solid rgba(226, 232, 240, .65);
      filter: saturate(.88) sepia(.08) brightness(1.03);
      background: var(--about-panel);
    }
    .hero-photo-row img:nth-child(2) {
      object-position: center center;
    }
    .hero-photo-main {
      width: 100%;
      height: 100%;
      object-fit: cover;
      object-position: center;
      border-radius: 10px;
      border: 1px solid rgba(226, 232, 240, .65);
      filter: saturate(.92) sepia(.06) brightness(1.03);
      background: var(--about-panel);
    }
    .hero-photo-fallback { display: none; }
    .hero-image.is-fallback .hero-photo-main { display: none; }
    .hero-image.is-fallback .hero-photo-fallback { display: grid; }

    .section { padding: 54px 0; }
    .section.alt { background: linear-gradient(180deg, rgba(241, 245, 249, .72), rgba(248, 250, 252, .5)); border-block: 1px solid rgba(226, 232, 240, .7); }
    .section-head { text-align: center; max-width: 690px; margin: 0 auto 42px; }
    .section-kicker {
      color: var(--about-gold-dark);
      font-size: .74rem;
      font-weight: 800;
      letter-spacing: .08em;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    .section-title {
      color: var(--about-heading);
      font-family: var(--font-display);
      font-size: clamp(2rem, 3.3vw, 3rem);
      font-weight: 600;
      line-height: 1.02;
      letter-spacing: -.018em;
    }
    .section-copy {
      color: var(--about-text2);
      font-size: .95rem;
      line-height: 1.8;
      margin-top: 18px;
    }

    .mission-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 0;
      margin-top: 48px;
    }
    .mission-item {
      text-align: center;
      padding: 4px 30px 0;
      border-right: 1px solid var(--about-border2);
    }
    .mission-item:last-child { border-right: none; }
    .icon-box {
      width: 62px;
      height: 62px;
      margin: 0 auto 20px;
      border-radius: 16px;
      display: grid;
      place-items: center;
      background: var(--about-gold-soft);
      color: var(--about-gold);
      font-size: 1.55rem;
      border: 1px solid var(--about-gold-border);
      box-shadow: 0 12px 24px rgba(197, 139, 42, .08);
    }
    .mission-item h3,
    .paper-card h3,
    .journey-step h3,
    .instructor-card h3 {
      color: var(--about-heading);
      font-size: .98rem;
      font-weight: 800;
      line-height: 1.25;
    }
    .mission-item p,
    .paper-card p,
    .journey-step p,
    .instructor-card p {
      color: var(--about-text2);
      font-size: .82rem;
      line-height: 1.65;
      margin-top: 8px;
    }

    .paper-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 28px;
    }
    .paper-card {
      min-height: 184px;
      padding: 30px 26px;
      border-radius: 10px;
      border: 1px solid var(--about-border);
      background: var(--about-gold-soft);
      box-shadow: var(--about-shadow);
      text-align: center;
    }
    .paper-card .icon-box { width: 52px; height: 52px; margin-bottom: 18px; font-size: 1.35rem; background: transparent; box-shadow: none; }

    .journey {
      position: relative;
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      gap: 24px;
      margin-top: 44px;
    }
    .journey::before {
      content: "";
      position: absolute;
      top: 38px;
      left: 9%;
      right: 9%;
      border-top: 1px dashed var(--about-gold-border);
    }
    .journey-step {
      position: relative;
      z-index: 1;
      text-align: center;
    }
    .journey-step .icon-box {
      width: 78px;
      height: 78px;
      border-radius: 50%;
      background: var(--about-gold-soft);
      margin-bottom: 18px;
    }

    .row-head {
      display: flex;
      justify-content: space-between;
      align-items: end;
      gap: 24px;
      margin-bottom: 22px;
    }
    .row-head .section-title { max-width: 720px; }
    .outline-link {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      border: 1px solid var(--about-gold-border);
      background: var(--about-card);
      color: var(--about-gold-dark);
      padding: 10px 18px;
      border-radius: 8px;
      font-size: .82rem;
      font-weight: 800;
      flex-shrink: 0;
    }
    .outline-link:hover { background: var(--about-gold-soft); }
    .instructors {
      display: grid;
      grid-template-columns: repeat(5, 1fr);
      gap: 28px;
    }
    .instructor-card {
      background: var(--about-card);
      border: 1px solid var(--about-border);
      border-radius: 10px;
      overflow: hidden;
      box-shadow: var(--about-shadow);
    }
    .instructor-card img {
      width: 100%;
      aspect-ratio: 1 / .88;
      object-fit: cover;
      object-position: center top;
      background: var(--about-panel);
    }
    .instructor-body { padding: 17px 18px 20px; }
    .instructor-body p { margin-top: 4px; }
    .instructor-meta {
      display: flex;
      flex-direction: column;
      gap: 4px;
      margin-top: 14px;
      color: var(--about-text2);
      font-size: .72rem;
    }

    .philosophy {
      display: grid;
      grid-template-columns: 1fr 1.15fr 1.1fr;
      align-items: center;
      gap: 58px;
    }
    .book-stack {
      min-height: 230px;
      border-radius: 14px;
      border: 1px solid var(--about-border);
      box-shadow: var(--about-shadow);
      overflow: hidden;
      background: var(--about-panel);
    }
    .book-stack img {
      width: 100%;
      height: 100%;
      min-height: 230px;
      object-fit: cover;
      object-position: center;
      filter: saturate(.93) sepia(.04) brightness(1.02);
    }
    .philosophy .section-title { font-size: clamp(1.8rem, 3vw, 2.7rem); }
    .philosophy-copy {
      color: var(--about-text2);
      font-size: .94rem;
      line-height: 1.82;
    }

    .final-cta {
      margin: 18px auto 72px;
      border-radius: 13px;
      border: 1px solid var(--about-gold-border);
      background:
        linear-gradient(135deg, rgba(241, 245, 249, .86), rgba(255, 255, 255, .95)),
        repeating-linear-gradient(150deg, transparent 0 18px, rgba(197, 139, 42, .05) 19px 20px);
      box-shadow: var(--about-shadow);
      padding: 30px clamp(24px, 5vw, 64px);
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 28px;
    }
    .final-cta h2 {
      color: var(--about-heading);
      font-family: var(--font-display);
      font-size: clamp(2rem, 3.7vw, 3rem);
      font-weight: 600;
      line-height: .98;
      letter-spacing: -.018em;
      margin-bottom: 9px;
    }
    .final-cta p { color: var(--about-text2); font-size: .9rem; line-height: 1.6; max-width: 470px; }
    .cta-actions { display: flex; align-items: center; gap: 16px; flex-wrap: wrap; }
    .primary-btn,
    .secondary-btn {
      min-height: 50px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 9px;
      border-radius: 8px;
      padding: 0 26px;
      font-weight: 800;
      font-size: .9rem;
      white-space: nowrap;
    }
    .primary-btn { background: var(--about-gold); color: #FFFFFF; border: 1px solid var(--about-gold); }
    .primary-btn:hover { background: var(--about-gold-dark); border-color: var(--about-gold-dark); }
    .secondary-btn { background: var(--about-card); color: var(--about-gold-dark); border: 1px solid var(--about-gold-border); }
    .secondary-btn:hover { background: var(--about-gold-soft); }

    @media (max-width: 1024px) {
      .hero-grid,
      .philosophy { grid-template-columns: 1fr; }
      .paper-grid,
      .mission-grid { grid-template-columns: repeat(2, 1fr); gap: 18px; }
      .mission-item { border: 1px solid var(--about-border); border-radius: 10px; padding: 26px; background: var(--about-card); }
      .instructors { grid-template-columns: repeat(3, 1fr); }
      .journey { grid-template-columns: repeat(3, 1fr); }
      .journey::before { display: none; }
      .final-cta { align-items: flex-start; flex-direction: column; }
    }
    @media (max-width: 760px) {
      .container,
      .nav-inner { width: min(100% - 32px, 1120px); }
      .nav-links { display: none; }
      .nav-user { display: none; }
      .hero { padding-top: 52px; }
      .hero-grid { grid-template-columns: 1fr; }
      .hero-title { font-size: clamp(2.75rem, 16vw, 4rem); }
      .hero-image { height: auto; }
      .hero-photo-row { grid-template-columns: 1fr; }
      .hero-photo-row img { aspect-ratio: 16 / 11; }
      .section { padding: 44px 0; }
      .paper-grid,
      .mission-grid,
      .journey,
      .instructors { grid-template-columns: 1fr; }
      .row-head { align-items: flex-start; flex-direction: column; }
      .final-cta { margin-bottom: 48px; }
      .cta-actions,
      .primary-btn,
      .secondary-btn { width: 100%; }
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
