/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `EduNex — NEX AI Tutor`,
  lang: `en`,
  stylesheets: [`css/style.css`, `css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    body{padding-top:0;overflow:hidden}
    .tutor-page{display:flex;flex-direction:column;height:100vh}
    .tutor-top-bar{height:66px;background:rgba(7,7,14,.96);border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 20px;gap:16px;flex-shrink:0}
    .full-tutor{flex:1;display:flex;overflow:hidden}
    .typing-dots{display:flex;gap:4px;align-items:center}
    .typing-dots span{width:7px;height:7px;border-radius:50%;background:var(--accent);animation:typing 1.2s infinite}
    .typing-dots span:nth-child(2){animation-delay:.2s}
    .typing-dots span:nth-child(3){animation-delay:.4s}
    @keyframes typing{0%,100%{opacity:.3;transform:scale(.8)}50%{opacity:1;transform:scale(1)}}
    .topic-chip{padding:6px 14px;background:var(--bg-card);border:1px solid var(--border);border-radius:100px;font-size:.78rem;color:var(--text-secondary);cursor:pointer;transition:var(--ease);white-space:nowrap}
    .topic-chip:hover{border-color:var(--accent);color:var(--accent);background:var(--accent-dim)}
    .topic-chip.active{border-color:var(--accent);color:var(--accent);background:var(--accent-dim)}
    .auth-gate{position:fixed;inset:0;z-index:50;display:none;align-items:center;justify-content:center;padding:20px;background:rgba(0,0,0,.78);backdrop-filter:blur(8px)}
    .auth-gate.is-visible{display:flex}
    .auth-gate-card{width:min(430px,100%);padding:28px;border-radius:16px;border:1px solid rgba(255,255,255,.1);background:#10141c;text-align:center;box-shadow:0 28px 90px rgba(0,0,0,.65)}
    .auth-gate-card h2{margin-bottom:8px;font-size:1.35rem}
    .ai-info h1{font-size:inherit;font-weight:inherit;line-height:inherit;margin:0}
    .auth-gate-card p{color:var(--text-secondary);margin-bottom:22px}
    .auth-gate-actions{display:flex;gap:10px}
    .auth-gate-actions a{flex:1;justify-content:center}
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `js/main.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
