/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Skillomate AI — My Certificates`,
  lang: `en`,
  stylesheets: [`css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { overflow-x: hidden; }
    body { font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; background: var(--bg, #000); color: var(--text, #fff); min-height: 100vh; }
    a { text-decoration: none; color: inherit; }

    :root {
      --bg: #000000;
      --text: #ffffff;
      --text2: #9ca3af;
      --nav-bg: rgba(0,0,0,0.95);
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,0.1);
      --cyan-border: rgba(197,139,42,0.22);
      --card: #0d0d0d;
      --border: rgba(255,255,255,0.07);
      --border2: rgba(255,255,255,0.1);
      --gray: #6b7280;
      --light: #9ca3af;
    }

    .navbar {
      position: fixed; top: 0; left: 0; right: 0; z-index: 999;
      background: var(--nav-bg); backdrop-filter: blur(20px);
      border-bottom: 1px solid var(--border); padding: 16px 0;
    }
    .nav-inner { max-width: 1100px; margin: 0 auto; padding: 0 24px; display: flex; align-items: center; gap: 40px; }
    .nav-logo { font-size: 1.2rem; font-weight: 700; color: var(--text); }
    .nav-logo span { color: var(--cyan); }
    .nav-links { display: flex; align-items: center; gap: 8px; flex: 1; justify-content: center; list-style: none; }
    .nav-links a { padding: 8px 16px; font-size: .9rem; font-weight: 500; color: var(--text2); transition: color .2s; }
    .nav-links a:hover { color: var(--text); }
    .nav-right { display: flex; align-items: center; gap: 16px; }
    .nav-login { font-size: .9rem; font-weight: 500; color: var(--text2); }
    .nav-login:hover { color: var(--cyan); }
    .nav-avatar {
      width: 36px; height: 36px; border-radius: 50%;
      background: var(--card); border: 1px solid var(--border);
      display: flex; align-items: center; justify-content: center;
      font-size: .85rem; color: #888; cursor: pointer; transition: border-color .2s;
    }
    .nav-avatar:hover { border-color: var(--cyan); color: var(--cyan); }

    .page { max-width: 1000px; margin: 0 auto; padding: 96px 24px 60px; }

    .back-row { display: flex; align-items: center; gap: 10px; margin-bottom: 28px; }
    .back-btn {
      width: 34px; height: 34px; border-radius: 9px;
      background: var(--card); border: 1px solid var(--border2);
      display: flex; align-items: center; justify-content: center;
      color: #888; font-size: .78rem; cursor: pointer; transition: all .2s;
    }
    .back-btn:hover { border-color: var(--cyan-border); color: var(--cyan); }
    .back-title { font-size: 1.2rem; font-weight: 800; }

    /* Stats row */
    .cert-stats {
      display: flex; gap: 14px; margin-bottom: 32px; flex-wrap: wrap;
    }
    .cert-stat {
      background: var(--card); border: 1px solid var(--border2);
      border-radius: 12px; padding: 14px 20px; min-width: 130px;
    }
    .cert-stat-label {
      font-size: .6rem; font-weight: 800; text-transform: uppercase;
      letter-spacing: .08em; color: var(--gray); margin-bottom: 4px;
      display: flex; align-items: center; gap: 5px;
    }
    .cert-stat-label i { color: var(--cyan); }
    .cert-stat-value { font-size: 1.4rem; font-weight: 900; color: var(--text); }

    /* Filter tabs */
    .cert-tabs { display: flex; gap: 8px; margin-bottom: 24px; }
    .cert-tab {
      padding: 7px 18px; border-radius: 100px;
      background: var(--card); border: 1px solid var(--border2);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; font-size: .78rem; font-weight: 600;
      color: var(--light); cursor: pointer; transition: all .2s;
    }
    .cert-tab:hover { border-color: rgba(255,255,255,.2); color: var(--text); }
    .cert-tab.active { background: var(--cyan); border-color: var(--cyan); color: #000; }

    /* Grid */
    .cert-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; }

    /* Certificate card */
    .cert-card {
      background: var(--card); border: 1px solid var(--border2);
      border-radius: 16px; overflow: hidden;
      transition: all .22s; cursor: pointer;
    }
    .cert-card:hover { border-color: var(--cyan-border); transform: translateY(-4px); box-shadow: 0 12px 32px rgba(0,0,0,.5); }

    /* Certificate visual */
    .cert-visual {
      background: linear-gradient(135deg, #071820, #0d2535);
      border-bottom: 1px solid var(--border2);
      padding: 24px 20px; text-align: center; position: relative;
      overflow: hidden;
    }
    .cert-visual::before {
      content: ''; position: absolute; inset: 0;
      background: radial-gradient(circle at 70% 30%, rgba(197,139,42,.08) 0%, transparent 60%);
    }
    .cert-visual-seal {
      width: 56px; height: 56px; border-radius: 50%;
      border: 2px solid var(--cyan); background: rgba(197,139,42,.08);
      display: flex; align-items: center; justify-content: center;
      font-size: 1.4rem; color: var(--cyan); margin: 0 auto 10px;
      box-shadow: 0 0 16px rgba(197,139,42,.2);
    }
    .cert-visual-org {
      font-size: .6rem; font-weight: 800; text-transform: uppercase;
      letter-spacing: .12em; color: var(--cyan); margin-bottom: 4px;
    }
    .cert-visual-title {
      font-size: .82rem; font-weight: 700; color: var(--text); line-height: 1.35;
      margin-bottom: 8px;
    }
    .cert-visual-name {
      font-size: .72rem; color: var(--light);
    }
    .cert-visual-ribbon {
      position: absolute; top: 14px; right: -22px;
      background: var(--cyan); color: #000;
      font-size: .52rem; font-weight: 900; letter-spacing: .08em;
      padding: 4px 28px; transform: rotate(40deg);
      text-transform: uppercase;
    }

    /* Card body */
    .cert-body { padding: 14px 16px; }
    .cert-course-name { font-size: .84rem; font-weight: 700; color: var(--text); margin-bottom: 5px; }
    .cert-meta {
      display: flex; align-items: center; gap: 8px;
      font-size: .7rem; color: var(--gray); margin-bottom: 12px; flex-wrap: wrap;
    }
    .cert-meta .dot { font-size: .45rem; }
    .cert-actions { display: flex; gap: 8px; }
    .cert-action-btn {
      flex: 1; padding: 8px; border-radius: 9px;
      background: rgba(255,255,255,.04); border: 1px solid var(--border2);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; font-size: .72rem; font-weight: 700;
      color: var(--light); cursor: pointer; transition: all .2s;
      display: flex; align-items: center; justify-content: center; gap: 5px;
    }
    .cert-action-btn:hover { border-color: var(--cyan-border); color: var(--cyan); }
    .cert-action-btn.primary { background: var(--cyan-dim); border-color: var(--cyan-border); color: var(--cyan); }
    .cert-action-btn.primary:hover { background: rgba(197,139,42,.18); }

    /* In-progress card */
    .cert-card.wip .cert-visual {
      background: linear-gradient(135deg, #0f0f0f, #1a1a1a);
    }
    .cert-card.wip .cert-visual-seal { border-color: #555; background: rgba(255,255,255,.04); color: #555; }
    .cert-card.wip .cert-visual-org { color: var(--gray); }
    .cert-card.wip .cert-visual-ribbon { background: #333; color: #aaa; }
    .cert-progress-wrap { margin-bottom: 12px; }
    .cert-progress-label {
      display: flex; justify-content: space-between;
      font-size: .68rem; color: var(--gray); margin-bottom: 5px;
    }
    .cert-progress-bar {
      height: 4px; border-radius: 2px; background: rgba(255,255,255,.07);
    }
    .cert-progress-fill {
      height: 100%; border-radius: 2px; background: var(--cyan);
    }

    /* Empty state */
    .cert-empty {
      display: none; text-align: center; padding: 60px 20px;
      color: var(--gray);
    }
    .cert-empty i { font-size: 2.5rem; margin-bottom: 14px; opacity: .3; }
    .cert-empty p { font-size: .88rem; }

    .nav-hamburger { display: none; flex-direction: column; gap: 5px; background: none; border: none; cursor: pointer; padding: 4px; }
    .nav-hamburger span { display: block; width: 22px; height: 2px; background: var(--text); border-radius: 2px; }
    @media (max-width: 900px) { .nav-links { display: none; } .nav-hamburger { display: flex; } }
    @media (max-width: 800px) { .cert-grid { grid-template-columns: repeat(2, 1fr); } }
    @media (max-width: 540px) { .cert-grid { grid-template-columns: 1fr; } }
    @media (max-width: 480px) { .container { padding: 0 16px; } }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
