/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Skillomate AI — Explore Our Curriculum`,
  lang: `en`,
  stylesheets: [`css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; overflow-x: hidden; }
    body { font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; overflow-x: hidden; }
    img { max-width: 100%; display: block; }
    a { text-decoration: none; color: inherit; }
    ul { list-style: none; }

    :root {
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,0.1);
      --cyan-border: rgba(197,139,42,0.25);
      /* dark-mode defaults — overridden by theme script at runtime */
      --bg: #000000;
      --card: #0D0D0D;
      --card2: #111318;
      --border: rgba(255,255,255,0.08);
      --text: #ffffff;
      --text2: #9ca3af;
      --nav-bg: rgba(0,0,0,0.92);
      --gray: #888888;
      --light: #bbbbbb;
    }

    .container { max-width: 1200px; margin: 0 auto; padding: 0 24px; }

    /* ===== NAVBAR ===== */
    .navbar {
      position: fixed; top: 0; left: 0; right: 0; z-index: 999;
      background: var(--nav-bg); backdrop-filter: blur(20px);
      border-bottom: 1px solid var(--border); padding: 16px 0;
    }
    .nav-inner { max-width: 1200px; margin: 0 auto; padding: 0 24px; display: flex; align-items: center; gap: 40px; }
    .nav-logo { font-size: 1.2rem; font-weight: 700; color: var(--text); white-space: nowrap; flex-shrink: 0; }
    .nav-logo span { color: var(--cyan); }
    .nav-links { display: flex; align-items: center; gap: 4px; flex: 1; justify-content: center; }
    .nav-links a { padding: 8px 16px; font-size: .9rem; font-weight: 500; color: var(--text2); transition: color .2s; position: relative; }
    .nav-links a:hover { color: var(--text); }
    .nav-links a.active { color: var(--text); font-weight: 600; }
    .nav-links a.active::after { content: ''; position: absolute; bottom: 0; left: 16px; right: 16px; height: 2px; background: var(--cyan); border-radius: 2px; }
    .nav-right { display: flex; align-items: center; gap: 16px; flex-shrink: 0; }
    .nav-login { font-size: .9rem; font-weight: 500; color: var(--text2); transition: color .2s; }
    .nav-login:hover { color: var(--cyan); }
    .nav-avatar { width: 36px; height: 36px; border-radius: 50%; background: var(--card2); border: 1px solid var(--border); display: flex; align-items: center; justify-content: center; font-size: .85rem; color: var(--gray); cursor: pointer; }
    .nav-hamburger { display: none; flex-direction: column; gap: 5px; background: none; border: none; cursor: pointer; padding: 4px; }
    .nav-hamburger span { display: block; width: 22px; height: 2px; background: var(--text); border-radius: 2px; }

    /* ===== SEARCH + FILTER ===== */
    .search-section { padding: 100px 0 40px; }

    /* ===== CATEGORY SECTIONS ===== */
    .category-block { margin-bottom: 72px; }
    .category-block:last-child { margin-bottom: 0; }
    .badge-tech { color: #4ADE80; border: 1px solid rgba(74,222,128,.35); }
    .badge-marketing { color: #F472B6; border: 1px solid rgba(244,114,182,.35); }
    .search-bar-wrap {
      display: flex; align-items: center; gap: 16px;
      flex-wrap: wrap;
    }
    .search-input-wrap {
      display: flex; align-items: center; gap: 10px;
      background: var(--card); border: 1px solid var(--border);
      border-radius: 10px; padding: 11px 16px;
      width: 260px; flex-shrink: 0;
      transition: border-color .2s;
    }
    .search-input-wrap:focus-within { border-color: var(--cyan-border); }
    .search-input-wrap i { color: var(--gray); font-size: .85rem; }
    .search-input-wrap input { background: none; border: none; outline: none; font-size: .85rem; color: var(--text); font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; width: 100%; }
    .search-input-wrap input::placeholder { color: var(--gray); }

    .filter-pills { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
    .pill {
      padding: 9px 18px;
      border-radius: 100px;
      font-size: .8rem; font-weight: 500;
      cursor: pointer; border: 1px solid var(--border);
      background: transparent; color: var(--gray);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      transition: all .2s; white-space: nowrap;
    }
    .pill:hover { border-color: var(--cyan-border); color: var(--cyan); }
    .pill.active { background: var(--cyan); color: #000; font-weight: 700; border-color: var(--cyan); }

    /* ===== CURRICULUM ===== */
    .curriculum-section { padding: 0 0 90px; }
    .section-header { display: flex; align-items: flex-end; justify-content: space-between; margin-bottom: 32px; }
    .section-header-left h2 { font-size: clamp(1.5rem, 2.5vw, 2rem); font-weight: 800; margin-bottom: 6px; }
    .section-header-left p { font-size: .85rem; color: var(--gray); }
    .nav-arrows { display: flex; gap: 8px; }
    .arrow-btn {
      width: 36px; height: 36px; border-radius: 50%;
      background: var(--card); border: 1px solid var(--border);
      display: flex; align-items: center; justify-content: center;
      font-size: .8rem; color: var(--gray); cursor: pointer;
      transition: all .2s;
    }
    .arrow-btn:hover { border-color: var(--cyan); color: var(--cyan); }

    .courses-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 24px; align-items: stretch; }

    .course-card {
      background: var(--card);
      border: 1px solid var(--border);
      border-radius: 18px;
      overflow: hidden;
      transition: all .25s;
      cursor: pointer;
      min-height: 430px;
      height: 100%;
      display: flex;
      flex-direction: column;
    }
    .course-card:hover {
      border-color: var(--cyan-border);
      box-shadow: 0 0 40px rgba(197,139,42,.12);
      transform: translateY(-5px);
    }
    .course-thumb-wrap {
      position: relative;
      flex: 0 0 auto;
      aspect-ratio: 16 / 9;
      overflow: hidden;
      background: #050505;
    }
    .course-thumb {
      width: 100%;
      height: 100%;
      object-fit: cover;
      object-position: left center;
      display: block;
      background: #050505;
    }
    .course-cat-badge {
      position: absolute; top: 12px; left: 12px;
      padding: 3px 10px; background: rgba(0,0,0,.75);
      backdrop-filter: blur(10px);
      border-radius: 100px; font-size: .65rem; font-weight: 700;
      text-transform: uppercase; letter-spacing: .06em;
    }
    .badge-agency { color: var(--cyan); border: 1px solid rgba(197,139,42,.35); }
    .badge-freelancing { color: #A78BFA; border: 1px solid rgba(167,139,250,.35); }
    .badge-content { color: #FB923C; border: 1px solid rgba(251,146,60,.35); }

    .course-body { padding: 20px; flex: 1; display: flex; flex-direction: column; min-width: 0; }
    .course-title-main {
      font-size: 1rem;
      font-weight: 700;
      line-height: 1.4;
      margin-bottom: 6px;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
    .course-author-line { font-size: .78rem; color: var(--gray); margin-bottom: 12px; }
    .course-author-line span { color: var(--text2); }
    .course-stats { display: flex; align-items: center; gap: 16px; font-size: .78rem; color: var(--gray); margin-bottom: 16px; padding-bottom: 16px; border-bottom: 1px solid var(--border); }
    .course-stats .stat-item { display: flex; align-items: center; gap: 5px; }
    .course-stats i { font-size: .72rem; color: var(--cyan); }
    .star-icon { color: #FFD700; }

    .course-price-row {
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: 14px;
      margin-top: auto;
    }
    .price-left { display: flex; align-items: baseline; gap: 8px; }
    .price-original { font-size: .78rem; color: var(--gray); text-decoration: line-through; }
    .price-trial { font-size: 1.2rem; font-weight: 800; color: var(--cyan); }
    .price-off { font-size: .72rem; font-weight: 700; color: #C58B2A; background: rgba(197,139,42,.1); border: 1px solid rgba(197,139,42,.25); padding: 2px 8px; border-radius: 100px; }

    .btn-trial {
      width: 100%; padding: 12px;
      background: var(--cyan); color: #000;
      font-weight: 700; font-size: .88rem;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      border: none; border-radius: 10px;
      cursor: pointer; transition: all .2s;
    }
    .btn-trial:hover { background: #C58B2A; box-shadow: 0 4px 18px rgba(197,139,42,.35); }
    .course-card-actions {
      display: grid;
      grid-template-columns: 1fr 46px;
      gap: 10px;
      align-items: center;
    }
    .wishlist-btn {
      width: 46px;
      height: 46px;
      border: 1px solid var(--border2);
      border-radius: 12px;
      background: rgba(255,255,255,.04);
      color: var(--light);
      display: grid;
      place-items: center;
      cursor: pointer;
      transition: all .2s;
    }
    .wishlist-btn:hover,
    .wishlist-btn.is-saved {
      border-color: rgba(197,139,42,.34);
      color: var(--cyan);
      background: rgba(197,139,42,.08);
    }
    .course-card.has-access .price-left,
    .course-card.has-access .price-off {
      display: none;
    }
    .course-card.has-access .course-price-row {
      justify-content: flex-start;
    }
    .course-card.has-access .course-price-row::before {
      content: "Access active";
      min-height: 28px;
      display: inline-flex;
      align-items: center;
      padding: 4px 10px;
      border-radius: 999px;
      background: rgba(197,139,42,.08);
      color: var(--cyan);
      font-size: .76rem;
      font-weight: 900;
    }

    /* ===== PATH TO MASTERY ===== */
    .path-section { padding: 90px 0; background: var(--bg); border-top: 1px solid var(--border); border-bottom: 1px solid var(--border); }
    .path-header { text-align: center; margin-bottom: 64px; }
    .path-header h2 { font-size: clamp(1.5rem, 2.5vw, 2rem); font-weight: 800; margin-bottom: 12px; }
    .path-header p { font-size: .9rem; color: var(--gray); max-width: 500px; margin: 0 auto; line-height: 1.7; }

    .steps-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 32px; position: relative; }
    .steps-grid::before {
      content: ''; position: absolute;
      top: 22px; left: 60px; right: 60px; height: 1px;
      background: linear-gradient(90deg, var(--cyan-border), rgba(197,139,42,.05) 50%, var(--cyan-border));
      pointer-events: none;
    }
    .step-item { text-align: center; position: relative; }
    .step-num {
      width: 48px; height: 48px;
      background: var(--cyan);
      border-radius: 12px;
      display: flex; align-items: center; justify-content: center;
      font-size: 1.1rem; font-weight: 800; color: #000;
      margin: 0 auto 18px;
      position: relative; z-index: 1;
    }
    .step-item h4 { font-size: .95rem; font-weight: 700; margin-bottom: 10px; }
    .step-item p { font-size: .8rem; color: var(--gray); line-height: 1.7; }

    /* ===== TESTIMONIAL ===== */
    .testimonial-section { padding: 90px 0; }
    .testimonial-inner {
      display: grid; grid-template-columns: 1fr 1fr;
      gap: 64px; align-items: center;
    }
    .testimonial-mockup {
      background: #fff;
      border-radius: 16px;
      overflow: hidden;
      box-shadow: 0 20px 60px rgba(0,0,0,.6);
      transform: perspective(800px) rotateY(5deg);
      transition: transform .4s;
    }
    .testimonial-mockup:hover { transform: perspective(800px) rotateY(0deg); }
    .tm-inner { padding: 16px; background: #f8f9fa; }
    .tm-top { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }
    .tm-logo { font-size: .7rem; font-weight: 800; color: #000; }
    .tm-logo span { color: var(--cyan); }
    .tm-nav { display: flex; gap: 8px; }
    .tm-nav span { font-size: .52rem; color: #777; }
    .tm-hero { display: grid; grid-template-columns: 1fr auto; gap: 10px; margin-bottom: 10px; align-items: start; }
    .tm-h-badge { display: inline-flex; align-items: center; gap: 4px; padding: 2px 8px; background: rgba(197,139,42,.12); border: 1px solid rgba(197,139,42,.25); border-radius: 100px; font-size: .42rem; color: var(--cyan); margin-bottom: 4px; }
    .tm-h-text h3 { font-size: .7rem; font-weight: 800; color: #111; line-height: 1.2; }
    .tm-h-text h3 span { color: var(--cyan); }
    .tm-h-text p { font-size: .42rem; color: #888; margin: 3px 0 5px; }
    .tm-h-btn { padding: 3px 8px; background: var(--cyan); border-radius: 4px; font-size: .45rem; font-weight: 700; color: #000; display: inline-block; }
    .tm-student { width: 72px; height: 72px; border-radius: 8px; object-fit: cover; }
    .tm-categories { margin-bottom: 10px; }
    .tm-cat-title { font-size: .55rem; font-weight: 700; color: #111; margin-bottom: 6px; text-align: center; }
    .tm-cat-grid { display: grid; grid-template-columns: repeat(4,1fr); gap: 4px; }
    .tm-cat { background: #efefef; border-radius: 4px; padding: 5px 3px; text-align: center; font-size: .38rem; color: #555; font-weight: 600; }
    .tm-cards { display: grid; grid-template-columns: 1fr 1fr; gap: 6px; }
    .tm-mini-card { background: #f1f1f1; border-radius: 6px; padding: 6px; }
    .tm-mini-card .mc-label { font-size: .38rem; color: var(--cyan); font-weight: 700; text-transform: uppercase; margin-bottom: 2px; }
    .tm-mini-card .mc-title { font-size: .45rem; font-weight: 700; color: #111; line-height: 1.3; }
    .tm-mini-card .mc-sub { font-size: .38rem; color: #888; margin: 2px 0; }
    .tm-mini-card .mc-btn { padding: 2px 5px; background: var(--cyan); border-radius: 3px; font-size: .35rem; font-weight: 700; color: #000; display: inline-block; margin-top: 3px; }

    .testimonial-content { padding-left: 16px; }
    .stars { color: #FFD700; font-size: 1.1rem; letter-spacing: 2px; margin-bottom: 20px; }
    .testimonial-quote {
      font-size: clamp(1rem, 1.8vw, 1.2rem);
      font-weight: 600; line-height: 1.65;
      color: var(--text); font-style: italic; margin-bottom: 24px;
    }
    .testimonial-quote::before { content: '"'; color: var(--cyan); font-size: 1.4rem; line-height: 0; vertical-align: -6px; margin-right: 2px; }
    .testimonial-quote::after { content: '"'; color: var(--cyan); font-size: 1.4rem; line-height: 0; vertical-align: -6px; margin-left: 2px; }
    .testimonial-author { display: flex; align-items: center; gap: 14px; }
    .ta-avatar { width: 48px; height: 48px; border-radius: 50%; object-fit: cover; border: 2px solid var(--cyan-border); }
    .ta-name { font-size: .92rem; font-weight: 700; color: var(--text); }
    .ta-role { font-size: .78rem; color: var(--gray); }

    /* ===== FOOTER ===== */
    .footer { background: var(--bg); border-top: 1px solid var(--border); padding: 60px 0 0; }
    .footer-grid { display: grid; grid-template-columns: 1.6fr 1fr 1fr 1fr; gap: 40px; padding-bottom: 48px; }
    .footer-brand-name { font-size: 1.1rem; font-weight: 800; color: var(--cyan); margin-bottom: 14px; }
    .footer-desc { font-size: .82rem; color: var(--gray); line-height: 1.75; margin-bottom: 20px; max-width: 240px; }
    .footer-socials { display: flex; gap: 10px; }
    .social-icon { width: 34px; height: 34px; background: var(--card); border: 1px solid var(--border); border-radius: 8px; display: flex; align-items: center; justify-content: center; font-size: .8rem; color: var(--gray); cursor: pointer; transition: all .2s; }
    .social-icon:hover { border-color: var(--cyan); color: var(--cyan); }
    .footer-col h4 { font-size: .72rem; font-weight: 700; text-transform: uppercase; letter-spacing: .1em; color: var(--text); margin-bottom: 18px; }
    .footer-links { display: flex; flex-direction: column; gap: 11px; }
    .footer-links a { font-size: .85rem; color: var(--gray); transition: color .2s; }
    .footer-links a:hover { color: var(--cyan); }

    .footer-bottom {
      border-top: 1px solid var(--border); padding: 16px 0;
      display: flex; align-items: center; justify-content: space-between;
      flex-wrap: wrap; gap: 12px;
    }
    .footer-bottom p { font-size: .78rem; color: var(--gray); }
    .footer-bottom-right { display: flex; align-items: center; gap: 20px; }
    .system-status { display: flex; align-items: center; gap: 6px; font-size: .75rem; color: var(--gray); }
    .status-dot { width: 7px; height: 7px; border-radius: 50%; background: #C58B2A; box-shadow: 0 0 6px rgba(197,139,42,.6); }
    .lang-badge { font-size: .75rem; color: var(--gray); display: flex; align-items: center; gap: 5px; }

    /* ===== RESPONSIVE ===== */
    @media (max-width: 1024px) {
      .courses-grid { grid-template-columns: repeat(2,1fr); }
      .footer-grid { grid-template-columns: 1fr 1fr; gap: 32px; }
      .steps-grid::before { display: none; }
    }
    @media (max-width: 900px) {
      .nav-links { display: none; }
      .nav-hamburger { display: flex; }
      .testimonial-inner { grid-template-columns: 1fr; }
      .testimonial-mockup { transform: none; }
      .steps-grid { grid-template-columns: repeat(2,1fr); }
    }
    @media (max-width: 640px) {
      .courses-grid { grid-template-columns: 1fr; }
      .steps-grid { grid-template-columns: 1fr 1fr; }
      .footer-grid { grid-template-columns: 1fr; }
      .search-bar-wrap { flex-direction: column; align-items: flex-start; }
      .search-input-wrap { width: 100%; }
      .path-section { padding: 60px 0; }
      .curriculum-section { padding: 0 0 60px; }
      .category-block { margin-bottom: 48px; }
    }
    @media (max-width: 480px) {
      .container { padding: 0 16px; }
      .search-section { padding: 90px 0 32px; }
      .section-header-left h2 { font-size: 1.3rem; }
      .course-body { padding: 16px; }
      .steps-grid { grid-template-columns: 1fr; }
      .footer { padding: 40px 0 0; }
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
