/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Course Details — Skillomate AI`,
  lang: `en`,
  stylesheets: [],
  styles: `
    :root { --font-body:"Manrope",ui-sans-serif,system-ui,sans-serif; --font-display:"Fraunces",Georgia,serif; --bg:#FAF7F1; --card:#FFFDF8; --card2:#FFFCF6; --panel:#F3EBDD; --border:#E2D6C6; --border2:#E6DACB; --text:#332820; --text2:#756A60; --gray:#9A8E82; --cyan:#C58B2A; }
    *,*::before,*::after{box-sizing:border-box}
    html,body{overflow-x:hidden}
    body{margin:0;min-height:100vh;background:var(--bg);color:var(--text);font-family:var(--font-body)}
    img{display:block;max-width:100%}
    a{color:inherit;text-decoration:none}
    h1,h2,h3{font-family:var(--font-display);font-weight:600;letter-spacing:0;margin:0;color:#2B211A}
    p{margin:0;color:var(--text2)}
    .course-detail-page{padding:104px 24px 80px}
    .course-detail-shell{max-width:1180px;margin:0 auto}
    .course-breadcrumb{display:flex;gap:8px;align-items:center;color:var(--text2);font-size:.88rem;margin-bottom:22px}
    .course-breadcrumb a{color:#9A681F;font-weight:800}
    .course-detail-grid{display:grid;grid-template-columns:minmax(0,1.22fr) minmax(320px,.78fr);gap:28px;align-items:start}
    .course-hero-card,.course-side-card,.course-section-card,.course-state-card{background:var(--card);border:1px solid var(--border);border-radius:18px;box-shadow:0 8px 24px rgba(88,65,34,.06)}
    .course-hero-card{overflow:hidden}
    .course-cover{width:100%;aspect-ratio:16/9;object-fit:cover;background:var(--panel)}
    .course-hero-body{padding:clamp(22px,3vw,34px)}
    .course-kicker{display:inline-flex;align-items:center;gap:8px;color:#B07821;text-transform:uppercase;letter-spacing:.08em;font-size:.78rem;font-weight:800;margin-bottom:14px}
    .course-title{font-size:clamp(2.4rem,5.2vw,4.7rem);line-height:.98;max-width:820px}
    .course-desc{margin-top:18px;max-width:760px;font-size:clamp(1rem,1.45vw,1.16rem);line-height:1.68}
    .course-meta-grid{display:flex;flex-wrap:wrap;gap:10px;margin-top:24px}
    .course-meta-chip{display:inline-flex;align-items:center;gap:7px;min-height:34px;padding:7px 12px;border:1px solid var(--border);border-radius:999px;background:var(--card2);color:var(--text2);font-size:.86rem;font-weight:700}
    .course-meta-chip i{color:var(--cyan)}
    .course-side-card{position:sticky;top:92px;padding:22px}
    .course-price{display:flex;align-items:baseline;gap:10px;margin-bottom:16px}
    .course-price strong{font-size:1.95rem;color:#2B211A}
    .course-price span{color:var(--gray);text-decoration:line-through;font-size:.95rem}
    .course-primary-btn,.course-secondary-btn{width:100%;min-height:48px;display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:12px;font-family:var(--font-body);font-size:.96rem;font-weight:800;cursor:pointer;transition:background .2s,border-color .2s,transform .2s}
    .course-primary-btn{border:1px solid #C58B2A;background:#C58B2A;color:#FFFDF8}
    .course-primary-btn:hover{background:#A96F18;border-color:#A96F18;transform:translateY(-1px)}
    .course-secondary-btn{margin-top:10px;border:1px solid #DAB77A;background:#FFFDF8;color:#9A681F}
    .course-side-list{margin:20px 0 0;padding:18px 0 0;border-top:1px solid var(--border2);list-style:none;display:grid;gap:12px}
    .course-side-list li{display:flex;justify-content:space-between;gap:16px;color:var(--text2);font-size:.9rem}
    .course-side-list strong{color:var(--text);text-align:right}
    .course-sections{display:grid;gap:18px;margin-top:22px}
    .course-section-card{padding:clamp(20px,2.5vw,28px)}
    .course-section-card h2{font-size:clamp(1.5rem,2.4vw,2.15rem);margin-bottom:14px}
    .curriculum-list{display:grid;gap:10px;margin-top:10px}
    .curriculum-item{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:14px 16px;border:1px solid var(--border2);border-radius:12px;background:var(--card2)}
    .curriculum-item span{color:var(--text);font-weight:800}
    .curriculum-item small{color:var(--text2);font-weight:700}
    .course-state-wrap{min-height:52vh;display:grid;place-items:center;padding:120px 24px 80px}
    .course-state-card{max-width:560px;width:100%;padding:34px;text-align:center}
    .course-state-card h1{font-size:clamp(2rem,4vw,3rem);margin-bottom:12px}
    .course-state-actions{display:flex;gap:12px;margin-top:24px;justify-content:center;flex-wrap:wrap}
    .course-state-actions a,.course-state-actions button{min-height:44px;padding:0 18px;border-radius:11px;border:1px solid #DAB77A;background:#FFFDF8;color:#9A681F;font:800 .92rem var(--font-body);cursor:pointer}
    .course-state-actions .primary{background:#C58B2A;border-color:#C58B2A;color:#FFFDF8}
    .course-skeleton{min-height:12px;border-radius:999px;background:linear-gradient(90deg,rgba(197,139,42,.08),rgba(255,253,248,.88),rgba(197,139,42,.08));background-size:220% 100%;animation:courseShimmer 1.4s ease-in-out infinite}
    @keyframes courseShimmer{to{background-position:-220% 0}}
    @media(max-width:900px){.course-detail-page{padding:88px 18px 64px}.course-detail-grid{grid-template-columns:1fr}.course-side-card{position:static}}
    @media(max-width:520px){.course-detail-page{padding-inline:14px}.course-hero-body,.course-side-card,.course-section-card{padding:18px;border-radius:16px}.course-title{font-size:clamp(2.15rem,14vw,3.25rem)}.course-meta-chip{width:100%;justify-content:center}.curriculum-item{align-items:flex-start;flex-direction:column}}
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
