/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `EduNex AI — Edit Profile`,
  lang: `en`,
  stylesheets: [`css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; background: #000; color: #fff; min-height: 100vh; }
    a { text-decoration: none; color: inherit; }
    img { display: block; max-width: 100%; }
    a { text-decoration: none; color: inherit; }
    ul { list-style: none; }

    :root {
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,0.1);
      --cyan-border: rgba(197,139,42,0.25);
      --card: #0D0D0D;
      --card2: #111;
      --border: rgba(255,255,255,0.08);
      --gray: #888;
      --light: #bbb;
    }

    /* ===== NAVBAR ===== */
    .navbar {
      position: fixed; top: 0; left: 0; right: 0; z-index: 999;
      background: rgba(0,0,0,0.96); backdrop-filter: blur(20px);
      border-bottom: 1px solid var(--border); padding: 16px 0;
    }
    .nav-inner { max-width: 1200px; margin: 0 auto; padding: 0 24px; display: flex; align-items: center; gap: 40px; }
    .nav-logo { font-size: 1.2rem; font-weight: 700; color: #fff; white-space: nowrap; flex-shrink: 0; }
    .nav-logo span { color: var(--cyan); }
    .nav-links { display: flex; align-items: center; gap: 4px; flex: 1; justify-content: center; }
    .nav-links a { padding: 8px 16px; font-size: .9rem; font-weight: 500; color: #bbb; transition: color .2s; position: relative; }
    .nav-links a:hover { color: #fff; }
    .nav-links a.active { color: #fff; font-weight: 600; }
    .nav-links a.active::after { content: ''; position: absolute; bottom: 0; left: 16px; right: 16px; height: 2px; background: var(--cyan); border-radius: 2px; }
    .nav-right { display: flex; align-items: center; gap: 16px; flex-shrink: 0; }
    .nav-login { font-size: .9rem; font-weight: 500; color: #ccc; transition: color .2s; }
    .nav-login:hover { color: var(--cyan); }
    .nav-avatar { width: 36px; height: 36px; border-radius: 50%; background: var(--card2); border: 1px solid var(--border); display: flex; align-items: center; justify-content: center; font-size: .85rem; color: #888; cursor: pointer; }
    .nav-hamburger { display: none; flex-direction: column; gap: 5px; background: none; border: none; cursor: pointer; padding: 4px; }
    .nav-hamburger span { display: block; width: 22px; height: 2px; background: #fff; border-radius: 2px; }
    .nav-links li { display: flex !important; align-items: center; }

    /* PAGE */
    .page { max-width: 620px; margin: 0 auto; padding: 96px 24px 60px; }

    /* BACK ROW */
    .back-row {
      display: flex; align-items: center; gap: 10px;
      margin-bottom: 28px;
    }
    .back-btn {
      width: 34px; height: 34px; border-radius: 9px;
      background: var(--card); border: 1px solid var(--border2);
      display: flex; align-items: center; justify-content: center;
      color: #888; font-size: .78rem; cursor: pointer; transition: all .2s;
    }
    .back-btn:hover { border-color: var(--cyan-border); color: var(--cyan); }
    .back-title { font-size: 1.2rem; font-weight: 800; }

    /* AVATAR EDIT */
    .ava-edit-wrap {
      display: flex; flex-direction: column; align-items: center;
      margin-bottom: 32px;
    }
    .ava-edit-circle {
      width: 96px; height: 96px; border-radius: 50%;
      border: 2.5px solid var(--cyan);
      background: #111; overflow: hidden; position: relative;
      cursor: pointer; margin-bottom: 10px;
      box-shadow: 0 0 0 5px rgba(197,139,42,.1);
      transition: box-shadow .2s;
    }
    .ava-edit-circle:hover { box-shadow: 0 0 0 8px rgba(197,139,42,.16); }
    .ava-edit-circle img { width: 100%; height: 100%; object-fit: cover; }
    .ava-edit-overlay {
      position: absolute; inset: 0; background: rgba(0,0,0,.5);
      display: flex; align-items: center; justify-content: center;
      opacity: 0; transition: opacity .18s; color: var(--cyan); font-size: 1.2rem;
    }
    .ava-edit-circle:hover .ava-edit-overlay { opacity: 1; }
    .ava-edit-name { font-size: .88rem; font-weight: 700; color: #fff; margin-bottom: 2px; }
    .ava-edit-sub { font-size: .72rem; color: var(--gray); }
    .ava-change-btn {
      margin-top: 12px;
      padding: 10px 14px;
      border-radius: 999px;
      border: 1px solid rgba(197,139,42,.28);
      background: rgba(197,139,42,.08);
      color: var(--cyan);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .78rem;
      font-weight: 800;
      cursor: pointer;
      transition: border-color .2s, background .2s;
    }
    .ava-change-btn:hover { border-color: var(--cyan); background: rgba(197,139,42,.14); }
    .ava-picker {
      width: 100%;
      display: grid;
      grid-template-columns: repeat(6, 1fr);
      gap: 10px;
    }
    .ava-picker-note { color: var(--gray); font-size: .78rem; line-height: 1.5; margin: -6px 0 16px; }
    .ava-choice {
      width: 100%;
      aspect-ratio: 1;
      border-radius: 14px;
      border: 1px solid var(--border2);
      background: #111;
      padding: 0;
      overflow: hidden;
      cursor: pointer;
      transition: border-color .2s, box-shadow .2s, transform .2s;
    }
    .ava-choice:hover,
    .ava-choice.selected {
      border-color: var(--cyan);
      box-shadow: 0 0 0 3px rgba(197,139,42,.12);
      transform: translateY(-1px);
    }
    .ava-choice img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      object-position: center top;
    }
    @media (max-width: 560px) {
      .ava-picker { grid-template-columns: repeat(4, 1fr); }
    }

    /* CARD */
    .ep-card {
      background: var(--card); border: 1px solid var(--border2);
      border-radius: 16px; padding: 24px;
      margin-bottom: 16px;
    }
    .ep-card-title {
      font-size: .72rem; font-weight: 800; text-transform: uppercase;
      letter-spacing: .1em; color: var(--gray); margin-bottom: 18px;
      display: flex; align-items: center; gap: 8px;
    }
    .ep-card-title i { color: var(--cyan); }

    /* FIELDS */
    .ep-row-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-bottom: 14px; }
    .ep-field { margin-bottom: 14px; }
    .ep-field:last-child { margin-bottom: 0; }
    .ep-label {
      display: block; font-size: .72rem; font-weight: 700;
      color: var(--light); margin-bottom: 6px; letter-spacing: .03em;
    }
    .ep-input {
      width: 100%; padding: 12px 14px;
      background: #111; border: 1px solid var(--border2);
      border-radius: 10px; font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .86rem; color: #fff; outline: none;
      transition: border-color .2s;
    }
    .ep-input:focus { border-color: rgba(197,139,42,.4); }
    .ep-input::placeholder { color: var(--gray); }
    .ep-input-wrap { position: relative; }
    .ep-input-wrap .ep-input { padding-left: 40px; }
    .ep-input-wrap i {
      position: absolute; left: 14px; top: 50%; transform: translateY(-50%);
      color: var(--gray); font-size: .8rem; pointer-events: none;
    }
    .ep-prefix {
      position: absolute; left: 14px; top: 50%; transform: translateY(-50%);
      font-size: .82rem; font-weight: 700; color: #aaa;
    }
    .ep-input-prefix { padding-left: 48px; }

    /* Phone field */
    .ep-phone-wrap { display: flex; align-items: center; gap: 10px; }
    .ep-country-code {
      padding: 12px 14px; background: #111; border: 1px solid var(--border2);
      border-radius: 10px; font-size: .86rem; color: #aaa; font-weight: 700;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; white-space: nowrap;
    }

    /* Gender slider */
    .ep-gender-slider {
      background: #111; border: 1px solid var(--border2);
      border-radius: 10px; padding: 5px;
      display: flex; gap: 4px; position: relative;
    }
    .ep-gender-btn {
      flex: 1; padding: 9px 8px; border: none; border-radius: 7px;
      background: transparent; font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .78rem; font-weight: 700; color: var(--light);
      cursor: pointer; transition: all .22s; position: relative; z-index: 1;
      display: flex; align-items: center; justify-content: center; gap: 5px;
    }
    .ep-gender-btn.selected { color: #000; }
    .ep-gender-thumb {
      position: absolute; top: 5px; bottom: 5px; left: 5px;
      border-radius: 7px; background: var(--cyan);
      transition: left .22s cubic-bezier(.4,0,.2,1), width .22s; z-index: 0;
    }

    /* Save button */
    .ep-save-btn {
      width: 100%; padding: 14px;
      background: var(--cyan); color: #000;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; font-size: .93rem; font-weight: 800;
      border: none; border-radius: 12px; cursor: pointer; transition: all .2s;
      margin-top: 8px;
    }
    .ep-save-btn:hover { background: #A96F18; box-shadow: 0 6px 22px rgba(197,139,42,.35); }
    .ep-save-btn:disabled { opacity: .65; cursor: wait; box-shadow: none; }

    /* Toast */
    .ep-toast {
      position: fixed; bottom: 28px; left: 50%; transform: translateX(-50%) translateY(20px);
      background: #1a1a1a; border: 1px solid rgba(197,139,42,.3);
      color: var(--cyan); padding: 12px 24px; border-radius: 100px;
      font-size: .82rem; font-weight: 700;
      opacity: 0; transition: all .3s; pointer-events: none; white-space: nowrap; z-index: 9999;
    }
    .ep-toast.show { opacity: 1; transform: translateX(-50%) translateY(0); }
    .ep-status {
      display: none;
      margin-bottom: 16px;
      padding: 12px 14px;
      border-radius: 12px;
      border: 1px solid rgba(197,139,42,.22);
      background: rgba(197,139,42,.07);
      color: var(--light);
      font-size: .82rem;
      line-height: 1.5;
    }
    .ep-status.show { display: block; }
    .ep-status.error {
      border-color: rgba(248,113,113,.35);
      background: rgba(248,113,113,.08);
      color: #A96F18;
    }
    .ep-status button {
      margin-left: 10px;
      border: 0;
      background: transparent;
      color: var(--cyan);
      font: inherit;
      font-weight: 800;
      cursor: pointer;
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
