/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Help & Support — Skillomate AI`,
  lang: `en`,
  stylesheets: [],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    :root { --bg:#000; --card:#0d0d0d; --text:#fff; --text2:#9ca3af; --cyan:#C58B2A; --border:rgba(255,255,255,.08); }
    * { box-sizing: border-box; }
    body { margin:0; background:var(--bg); color:var(--text); font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; }
    .help-page { width:min(1100px, calc(100% - 32px)); margin:0 auto; padding:130px 0 72px; }
    .help-kicker { color:var(--cyan); font-size:.78rem; font-weight:900; letter-spacing:.12em; text-transform:uppercase; }
    h1 { margin:10px 0 14px; font-size:clamp(2rem, 7vw, 4rem); line-height:1.04; }
    .help-intro { color:var(--text2); line-height:1.8; max-width:760px; }
    .help-grid { display:grid; grid-template-columns:repeat(3, minmax(0,1fr)); gap:16px; margin-top:28px; }
    .help-card { padding:22px; border:1px solid var(--border); border-radius:18px; background:var(--card); }
    .help-card i { color:var(--cyan); margin-bottom:14px; }
    h2 { margin:0 0 10px; font-size:1rem; }
    p { color:var(--text2); line-height:1.75; font-size:.9rem; }
    a { color:var(--cyan); text-decoration:none; font-weight:800; }
    @media (max-width: 800px) { .help-grid { grid-template-columns:1fr; } }
  `,
  scripts: [],
};

export default page;
