/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Skillomate — Democratizing AI Income`,
  lang: `en`,
  stylesheets: [`css/style.css`, `css/animations.css`],
  styles: ``,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `js/main.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
