/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Skillomate AI — Best Platform to Empower Skills`,
  lang: `en`,
  stylesheets: [`css/theme.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    :root {
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,0.1);
      --cyan-border: rgba(197,139,42,0.25);
      --accent: #B9853E;
      --gold: #C58B2A;
      --bg: #000000;
      --card: #0d0d0d;
      --card2: #111318;
      --border2: rgba(255,255,255,0.10);
      --border: rgba(255,255,255,0.08);
      --text: #ffffff;
      --text2: #9ca3af;
      --nav-bg: rgba(0,0,0,0.95);
      --gray: #888888;
    }
    body {
      background-color: var(--bg);
      color: var(--text);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      background:
        radial-gradient(circle at 18% 12%, rgba(197,139,42,.10), transparent 30rem),
        radial-gradient(circle at 86% 8%, rgba(197,139,42,.07), transparent 28rem),
        var(--bg);
    }
    a { text-decoration: none; }
    .material-symbols-outlined {
      font-family: "Material Symbols Outlined" !important;
      font-weight: normal !important;
      font-style: normal !important;
      line-height: 1;
      letter-spacing: normal !important;
      text-transform: none !important;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      white-space: nowrap;
      word-wrap: normal;
      direction: ltr;
      -webkit-font-feature-settings: "liga";
      -webkit-font-smoothing: antialiased;
      font-variation-settings: "FILL" 0, "wght" 400, "GRAD" 0, "opsz" 24;
      vertical-align: middle;
    }
    .glass-card {
      background: color-mix(in srgb, var(--card) 82%, transparent);
      backdrop-filter: blur(12px);
      border: 1px solid var(--border);
    }
    .border-subtle { border: 1px solid var(--border); }
    .page-grid {
      position: fixed;
      inset: 0;
      pointer-events: none;
      opacity: .22;
      background-image:
        linear-gradient(rgba(255,255,255,.04) 1px, transparent 1px),
        linear-gradient(90deg, rgba(255,255,255,.04) 1px, transparent 1px);
      background-size: 72px 72px;
      mask-image: linear-gradient(to bottom, #000, transparent 72%);
    }
    .section-kicker {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      color: var(--cyan);
      font-size: 12px;
      font-weight: 700;
      letter-spacing: .08em;
      text-transform: uppercase;
      margin-bottom: 14px;
    }
    .section-kicker::before {
      content: "";
      width: 18px;
      height: 2px;
      border-radius: 999px;
      background: var(--cyan);
    }
    .hero-panel-row {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 18px;
      padding: 16px;
      border-radius: 16px;
      background: color-mix(in srgb, var(--card2) 70%, transparent);
      border: 1px solid var(--border);
    }
    .hero-panel-meter {
      height: 8px;
      border-radius: 999px;
      overflow: hidden;
      background: var(--border);
    }
    .hero-panel-meter span {
      display: block;
      height: 100%;
      border-radius: inherit;
      background: var(--cyan);
      box-shadow: 0 0 18px rgba(197,139,42,.36);
    }
    .professional-card {
      transition: transform .22s ease, border-color .22s ease, background .22s ease;
    }
    .professional-card:hover {
      transform: translateY(-3px);
      border-color: rgba(197,139,42,.36);
      background: color-mix(in srgb, var(--card2) 88%, transparent);
    }
    .hero-cta-primary,
    .hero-cta-secondary {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 10px;
      min-height: 50px;
      padding: 0 22px;
      border-radius: 12px;
      font-family: "Manrope", sans-serif;
      font-size: clamp(15px, 1vw, 16px);
      font-weight: 600;
      transition: transform .18s ease, border-color .18s ease, background .18s ease;
    }
    .hero-cta-primary {
      background: var(--cyan);
      color: #001f26;
      border: 1px solid var(--cyan);
    }
    .hero-cta-secondary {
      color: var(--text);
      background: color-mix(in srgb, var(--card2) 70%, transparent);
      border: 1px solid var(--border2);
    }
    .hero-cta-primary:hover,
    .hero-cta-secondary:hover {
      transform: translateY(-1px);
    }
    .hero-cta-secondary:hover {
      border-color: rgba(197,139,42,.38);
      background: color-mix(in srgb, var(--card2) 88%, transparent);
    }
    .learning-hero {
      position: relative;
      max-width: none;
      margin: 0 auto;
      padding: clamp(50px, 5vw, 76px) 0 clamp(34px, 5vw, 58px);
      overflow: hidden;
    }
    .learning-hero-copy {
      position: relative;
      z-index: 3;
      max-width: 860px;
      margin: 0 auto;
      padding: 0 clamp(16px, 5vw, 72px);
      text-align: center;
    }
    .learning-hero-label {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      margin-bottom: 22px;
      color: var(--cyan);
      font-family: "Manrope", sans-serif;
      font-size: clamp(13px, .95vw, 14px);
      font-weight: 700;
      letter-spacing: .08em;
      line-height: 1.2;
      text-transform: uppercase;
    }
    .learning-hero h1 {
      max-width: 850px;
      margin: 0 auto;
      font-family: "Fraunces", serif;
      font-size: clamp(42px, 5.9vw, 82px);
      line-height: .98;
      letter-spacing: 0;
      font-weight: 600;
      text-align: center;
    }
    .learning-hero-copy > p {
      max-width: 720px;
      margin: 22px auto 0;
      color: var(--text2);
      font-family: "Manrope", sans-serif;
      font-size: clamp(16px, 1.38vw, 20px);
      font-weight: 500;
      line-height: 1.55;
      text-align: center;
    }
    .learning-hero-actions {
      position: relative;
      z-index: 3;
      display: flex;
      justify-content: center;
      gap: 12px;
      margin: clamp(18px, 2.5vw, 28px) auto 0;
      padding: 0 clamp(16px, 5vw, 72px);
      flex-wrap: wrap;
    }
    .hero-tabs-wrap {
      position: relative;
      z-index: 3;
      margin: clamp(18px, 3vw, 28px) auto -24px;
      display: flex;
      justify-content: center;
    }
    .home-hero-tabs {
      display: inline-flex;
      align-items: center;
      gap: 24px;
      border-bottom: 1px solid var(--border);
    }
    .home-hero-tab {
      position: relative;
      padding: 0 0 11px;
      border: 0;
      background: transparent;
      color: var(--text2);
      font-family: "Manrope", sans-serif;
      font-size: clamp(15px, 1vw, 16px);
      font-weight: 600;
      line-height: 1.2;
      cursor: pointer;
    }
    .home-hero-tab::after {
      content: "";
      position: absolute;
      left: 0;
      right: 0;
      bottom: -1px;
      height: 2px;
      border-radius: 999px;
      background: transparent;
    }
    .home-hero-tab:hover,
    .home-hero-tab.is-active {
      color: var(--text);
    }
    .home-hero-tab.is-active::after {
      background: var(--cyan);
    }
    .hero-carousel-shell {
      position: relative;
      z-index: 2;
      width: 100%;
      margin: clamp(24px, 3vw, 42px) auto 0;
      padding: 12px 0 0;
    }
    .hero-carousel-viewport {
      overflow-x: auto;
      overflow-y: hidden;
      scroll-snap-type: x mandatory;
      scrollbar-width: none;
      padding: 34px 0 24px;
      touch-action: pan-x;
      -webkit-user-select: none;
      user-select: none;
    }
    .hero-carousel-viewport * { -webkit-user-drag: none; }
    .hero-carousel-viewport::-webkit-scrollbar { display: none; }
    .hero-carousel-viewport.is-dragging {
      scroll-snap-type: none;
    }
    .hero-carousel-viewport.is-auto-moving {
      scroll-snap-type: none;
    }
    .hero-carousel-track {
      display: flex;
      align-items: stretch;
      gap: clamp(12px, 1.4vw, 22px);
      min-height: clamp(270px, 21vw, 350px);
    }
    .hero-carousel-track.is-empty {
      justify-content: center;
      min-height: 220px;
    }
    .hero-carousel-track::before,
    .hero-carousel-track::after {
      content: "";
      flex: 0 0 clamp(12px, 2.5vw, 40px);
    }
    .hero-carousel-track.is-empty::before,
    .hero-carousel-track.is-empty::after {
      display: none;
    }
    .hero-course-card {
      font-family: "Manrope", sans-serif;
      flex: 0 0 var(--hero-card-width, clamp(220px, 16.8vw, 286px));
      height: var(--hero-card-height, clamp(270px, 20vw, 340px));
      scroll-snap-align: center;
      border-radius: 22px;
      border: 1px solid var(--border);
      background: color-mix(in srgb, var(--card) 88%, transparent);
      overflow: hidden;
      position: relative;
      box-shadow: 0 18px 45px rgba(15,23,42,.10);
      transform: none;
      transition: border-color .35s ease, box-shadow .35s ease, background .35s ease;
    }
    .hero-course-card.is-center {
      border-color: var(--cyan-border);
      box-shadow: 0 18px 45px rgba(15,23,42,.10);
      background: color-mix(in srgb, var(--card) 96%, transparent);
    }
    .hero-placeholder-card {
      cursor: pointer;
    }
    .hero-course-card[data-hero-id],
    .hero-course-card[data-hero-path] {
      cursor: pointer;
    }
    .hero-course-card:focus-visible {
      outline: 2px solid var(--cyan);
      outline-offset: 4px;
    }
    .hero-card-media {
      position: relative;
      height: 100%;
      overflow: hidden;
      background: var(--card2);
    }
    .hero-card-media img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      display: block;
    }
    .hero-card-badge,
    .hero-card-wish {
      position: absolute;
      top: 14px;
    }
    .hero-card-badge {
      left: 14px;
      max-width: calc(100% - 70px);
      padding: 5px 10px;
      border-radius: 999px;
      background: rgba(0,0,0,.78);
      border: 1px solid var(--cyan-border);
      color: var(--cyan);
      font-size: 10px;
      font-weight: 700;
      letter-spacing: .06em;
      text-transform: uppercase;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
    .hero-card-wish {
      right: 14px;
      width: 34px;
      height: 34px;
      border-radius: 999px;
      border: 1px solid var(--border);
      background: color-mix(in srgb, var(--card) 86%, transparent);
      color: var(--text2);
      display: grid;
      place-items: center;
    }
    .hero-card-media::after {
      content: "";
      position: absolute;
      inset: 45% 0 0;
      background: linear-gradient(180deg, transparent, color-mix(in srgb, var(--bg) 88%, rgba(0,0,0,.52)));
      opacity: .86;
    }
    .hero-card-body {
      position: absolute;
      left: 0;
      right: 0;
      bottom: 0;
      z-index: 2;
      padding: 18px;
      opacity: 1;
      transform: none;
      transition: opacity .35s ease;
    }
    .hero-course-card.is-center .hero-card-body {
      opacity: 1;
      transform: none;
    }
    .hero-card-kicker {
      color: var(--cyan);
      font-size: 11px;
      font-weight: 700;
      letter-spacing: .08em;
      text-transform: uppercase;
      margin-bottom: 9px;
    }
    .hero-card-title {
      color: var(--text);
      font-size: clamp(.95rem, 1vw, 1.05rem);
      line-height: 1.35;
      font-weight: 600;
      min-height: 0;
      margin-bottom: 8px;
    }
    .hero-card-meta,
    .hero-card-lesson {
      display: flex;
      flex-wrap: wrap;
      gap: 8px 12px;
      color: var(--text2);
      font-size: .78rem;
      font-weight: 500;
      line-height: 1.5;
    }
    .hero-card-meta span,
    .hero-card-lesson span {
      display: inline-flex;
      align-items: center;
      gap: 5px;
    }
    .hero-card-price {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 12px;
      margin-top: 16px;
    }
    .hero-card-price strong,
    .hero-card-action {
      color: var(--cyan);
      font-weight: 600;
    }
    .hero-card-action {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      border: 0;
      background: transparent;
      font-family: "Manrope", sans-serif;
      font-size: .86rem;
      cursor: pointer;
    }
    .hero-progress-row {
      display: flex;
      justify-content: space-between;
      gap: 12px;
      margin: 14px 0 8px;
      color: var(--text2);
      font-family: "Manrope", sans-serif;
      font-size: .78rem;
      font-weight: 600;
    }
    .hero-progress-track {
      height: 7px;
      border-radius: 999px;
      overflow: hidden;
      background: var(--border);
    }
    .hero-progress-track span {
      display: block;
      height: 100%;
      width: var(--progress, 0%);
      background: var(--cyan);
      border-radius: inherit;
    }
    .hero-skeleton {
      display: block;
      border-radius: 999px;
      background: linear-gradient(90deg, color-mix(in srgb, var(--border) 65%, transparent), color-mix(in srgb, var(--card2) 88%, transparent), color-mix(in srgb, var(--border) 65%, transparent));
      background-size: 220% 100%;
      animation: heroSkeleton 1.7s ease-in-out infinite;
    }
    .hero-skeleton-media {
      width: 100%;
      height: 100%;
      border-radius: 0;
      background: linear-gradient(135deg, color-mix(in srgb, var(--card2) 84%, transparent), color-mix(in srgb, var(--border) 72%, transparent));
      animation: none;
    }
    .hero-skeleton-kicker { width: 34%; height: 10px; margin-bottom: 14px; }
    .hero-skeleton-title { width: 82%; height: 18px; margin-bottom: 10px; }
    .hero-skeleton-title.short { width: 58%; }
    .hero-skeleton-line { width: 100%; height: 10px; margin-top: 10px; }
    .hero-skeleton-line.medium { width: 72%; }
    .hero-placeholder-note {
      color: var(--text2);
      font-family: "Manrope", sans-serif;
      font-size: .83rem;
      line-height: 1.55;
      margin-top: 14px;
    }
    @keyframes heroSkeleton {
      0% { background-position: 120% 0; }
      100% { background-position: -120% 0; }
    }
    .hero-carousel-empty {
      flex: 0 0 min(92vw, 620px);
      width: min(92vw, 620px);
      margin: 24px auto 42px;
      padding: 28px;
      text-align: center;
      border-radius: 22px;
      border: 1px solid var(--border);
      background: color-mix(in srgb, var(--card) 88%, transparent);
      color: var(--text2);
    }
    .hero-carousel-empty strong {
      display: block;
      color: var(--text);
      font-size: 1rem;
      margin-bottom: 8px;
    }
    .hero-search-block {
      font-family: "Manrope", sans-serif;
      position: relative;
      z-index: 3;
      width: min(100%, 820px);
      margin: clamp(18px, 2.4vw, 30px) auto 0;
      padding: 0 clamp(16px, 5vw, 72px);
    }
    .hero-search-form {
      display: grid;
      grid-template-columns: 1fr auto;
      gap: 10px;
      padding: 8px;
      border: 1px solid rgba(255, 255, 255, 0.3);
      border-radius: 18px;
      background: color-mix(in srgb, var(--card) 86%, transparent);
      box-shadow: 0 18px 45px rgba(15,23,42,.08);
    }
    .hero-search-field {
      display: flex;
      align-items: center;
      gap: 10px;
      min-height: 48px;
      padding: 0 14px;
      color: var(--text2);
    }
    .hero-search-field input {
      width: 100%;
      border: 0;
      outline: 0;
      background: transparent;
      color: var(--text);
      font-family: "Manrope", sans-serif;
      font-size: .95rem;
      font-weight: 500;
    }
    .hero-search-field input::placeholder {
      font-family: "Manrope", sans-serif;
      font-weight: 400;
    }
    .hero-search-btn {
      border: 1px solid var(--cyan);
      border-radius: 12px;
      background: var(--cyan);
      color: #001f26;
      font-family: "Manrope", sans-serif;
      font-size: clamp(15px, 1vw, 16px);
      font-weight: 600;
      padding: 0 20px;
      cursor: pointer;
    }
    .hero-topics {
      display: flex;
      justify-content: center;
      flex-wrap: wrap;
      gap: 10px;
      margin-top: 14px;
    }
    .hero-topic {
      color: var(--text2);
      border: 1px solid var(--border);
      background: color-mix(in srgb, var(--card2) 72%, transparent);
      border-radius: 999px;
      padding: 7px 12px;
      font-family: "Manrope", sans-serif;
      font-size: .82rem;
      font-weight: 600;
    }
    .hero-topic:hover {
      color: var(--cyan);
      border-color: var(--cyan-border);
    }
    .hero-trust-strip {
      font-family: "Manrope", sans-serif;
      position: relative;
      z-index: 3;
      display: grid;
      grid-template-columns: repeat(5, minmax(0, 1fr));
      gap: 12px;
      width: min(100%, 1080px);
      margin: clamp(30px, 5vw, 52px) auto 0;
    }
    .hero-trust-item {
      min-height: 84px;
      display: flex;
      align-items: center;
      gap: 12px;
      padding: 14px;
      border: 1px solid var(--border);
      border-radius: 18px;
      background: color-mix(in srgb, var(--card) 86%, transparent);
      color: var(--text2);
      font-size: .8rem;
      font-weight: 700;
    }
    .hero-trust-item strong {
      display: block;
      color: var(--text);
      font-size: .92rem;
      line-height: 1.25;
    }
    .hero-trust-item .material-symbols-outlined {
      color: var(--cyan);
      font-size: 21px;
      flex: 0 0 auto;
    }
    .hero-mock-placeholder {
      min-height: 430px;
      border-radius: 22px;
      border: 1px solid var(--border2);
      background: linear-gradient(145deg, #05070d, #000);
      overflow: visible;
      position: relative;
      display: grid;
      place-items: center;
      perspective: 1200px;
      box-shadow: inset 0 0 0 1px rgba(255,255,255,.03), 0 26px 80px rgba(0,0,0,.36);
    }
    .hero-mock-image {
      width: min(100%, 430px);
      height: min(72vh, 620px);
      object-fit: contain;
      object-position: center bottom;
      transform: rotateY(-10deg) rotateZ(-2.5deg) translateY(8px);
      transform-origin: 52% 70%;
      filter: drop-shadow(26px 34px 46px rgba(0,0,0,.52)) drop-shadow(0 0 28px rgba(197,139,42,.12));
      transition: transform .35s ease, filter .35s ease;
      will-change: transform;
    }
    .hero-mock-placeholder:hover .hero-mock-image {
      transform: rotateY(-7deg) rotateZ(-1.5deg) translateY(2px);
      filter: drop-shadow(30px 38px 54px rgba(0,0,0,.56)) drop-shadow(0 0 34px rgba(197,139,42,.16));
    }
    .site-footer {
      border-top: 1px solid var(--border);
      background:
        linear-gradient(180deg, color-mix(in srgb, var(--card) 55%, transparent), var(--bg)),
        var(--bg);
      padding: 64px clamp(16px, 5vw, 72px) 28px;
    }
    .footer-shell {
      max-width: 1480px;
      margin: 0 auto;
    }
    .footer-top {
      display: grid;
      grid-template-columns: minmax(280px, 1.4fr) repeat(3, minmax(140px, .65fr)) minmax(260px, .95fr);
      gap: clamp(28px, 4vw, 56px);
      align-items: start;
    }
    .footer-brand-mark {
      display: inline-flex;
      align-items: center;
      gap: 10px;
      color: var(--text);
      font-size: 1.15rem;
      font-weight: 800;
      margin-bottom: 16px;
    }
    .footer-brand-icon {
      width: 36px;
      height: 36px;
      border-radius: 11px;
      display: grid;
      place-items: center;
      background: var(--cyan);
      color: #001f26;
      font-weight: 900;
    }
    .footer-brand-mark span:last-child {
      color: var(--cyan);
    }
    .footer-copy {
      color: var(--text2);
      font-size: .9rem;
      line-height: 1.75;
      max-width: 360px;
      margin-bottom: 22px;
    }
    .footer-trust-row {
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
    }
    .footer-trust-chip {
      display: inline-flex;
      align-items: center;
      gap: 7px;
      padding: 8px 11px;
      border: 1px solid var(--border);
      border-radius: 999px;
      color: var(--text2);
      background: color-mix(in srgb, var(--card2) 76%, transparent);
      font-size: .75rem;
      font-weight: 700;
    }
    .footer-trust-chip .material-symbols-outlined {
      color: var(--cyan);
      font-size: 16px;
    }
    .footer-heading {
      color: var(--text);
      font-size: .75rem;
      font-weight: 800;
      letter-spacing: .1em;
      text-transform: uppercase;
      margin-bottom: 16px;
    }
    .footer-links {
      display: flex;
      flex-direction: column;
      gap: 11px;
      color: var(--text2);
      font-size: .88rem;
    }
    .footer-links a {
      width: fit-content;
      color: inherit;
      transition: color .18s ease, transform .18s ease;
    }
    .footer-links a:hover {
      color: var(--cyan);
      transform: translateX(2px);
    }
    .footer-contact {
      padding: 18px;
      border: 1px solid var(--border);
      border-radius: 18px;
      background: color-mix(in srgb, var(--card2) 82%, transparent);
    }
    .footer-contact p {
      color: var(--text2);
      font-size: .86rem;
      line-height: 1.65;
      margin-bottom: 16px;
    }
    .footer-contact-link {
      display: inline-flex;
      align-items: center;
      gap: 9px;
      color: var(--cyan);
      font-weight: 800;
      font-size: .88rem;
    }
    .footer-socials {
      display: flex;
      gap: 10px;
      margin-top: 20px;
    }
    .footer-socials a {
      width: 36px;
      height: 36px;
      display: grid;
      place-items: center;
      border-radius: 10px;
      border: 1px solid var(--border);
      background: color-mix(in srgb, var(--card2) 76%, transparent);
      color: var(--text2);
      transition: color .18s ease, border-color .18s ease, transform .18s ease;
    }
    .footer-socials a:hover {
      color: var(--cyan);
      border-color: var(--cyan-border);
      transform: translateY(-1px);
    }
    .footer-bottom {
      margin-top: 46px;
      padding-top: 22px;
      border-top: 1px solid var(--border);
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 18px;
      color: var(--text2);
      font-size: .8rem;
    }
    .footer-bottom-links {
      display: flex;
      flex-wrap: wrap;
      gap: 18px;
    }
    .footer-bottom-links a {
      color: inherit;
    }
    .footer-bottom-links a:hover {
      color: var(--cyan);
    }
    @media (min-width: 1280px) {
      .hero-mock-placeholder {
        min-height: 520px;
      }
    }
    @media (min-width: 1536px) {
      .hero-mock-placeholder {
        min-height: 590px;
      }
    }

    /* Navbar copied from index.html */
    .navbar {
      position: fixed; top: 0; left: 0; right: 0; z-index: 999;
      background: var(--nav-bg);
      backdrop-filter: blur(20px);
      border-bottom: 1px solid var(--border);
      padding: 16px 0;
    }
    .nav-inner {
      max-width: 1480px; margin: 0 auto; padding: 0 clamp(16px, 5vw, 72px);
      display: flex; align-items: center; gap: 32px;
    }
    .nav-logo {
      font-size: 1.2rem; font-weight: 700; color: var(--text);
      white-space: nowrap; flex-shrink: 0;
    }
    .nav-logo span { color: var(--cyan); }
    .nav-links {
      display: flex; align-items: center; gap: 4px;
      flex: 1; justify-content: center; list-style: none; margin: 0; padding: 0;
    }
    .nav-links a {
      padding: 8px 14px; font-size: .9rem; font-weight: 500;
      color: var(--text2); transition: color .2s; position: relative;
    }
    .nav-links a:hover { color: var(--text); }
    .nav-links a.active { color: var(--text); font-weight: 600; }
    .nav-links a.active::after {
      content: ""; position: absolute; bottom: 0; left: 14px; right: 14px;
      height: 2px; background: var(--cyan); border-radius: 2px;
    }
    .nav-right { display: flex; align-items: center; gap: 12px; flex-shrink: 0; }
    .nav-login { font-size: .9rem; font-weight: 500; color: var(--text2); transition: color .2s; }
    .nav-login:hover { color: var(--cyan); }
    .nav-avatar {
      width: 36px; height: 36px; border-radius: 50%;
      background: var(--card2); border: 1px solid var(--border);
      display: flex; align-items: center; justify-content: center;
      font-size: .85rem; color: var(--gray); cursor: pointer;
      transition: border-color .2s; overflow: hidden;
    }
    .nav-avatar:hover { border-color: var(--cyan); color: var(--cyan); }
    .nav-hamburger {
      display: none; flex-direction: column; gap: 5px;
      background: none; border: none; cursor: pointer; padding: 4px;
    }
    .nav-hamburger span {
      display: block; width: 22px; height: 2px;
      background: var(--text); border-radius: 2px; transition: .3s;
    }
    .index2-mobile-menu {
      display: none; position: fixed; top: 65px; left: 0; right: 0; z-index: 998;
      background: var(--nav-bg); border-bottom: 1px solid var(--border);
      padding: 16px 24px; flex-direction: column; gap: 4px;
    }
    .index2-mobile-menu a {
      padding: 12px 0; font-size: .95rem; color: var(--text2);
      border-bottom: 1px solid var(--border); display: block;
    }
    .index2-mobile-menu a.active { color: var(--text); }
    @media (max-width: 900px) {
      .nav-links, .nav-right { display: none; }
      .nav-hamburger { display: flex; margin-left: auto; }
      .footer-top {
        grid-template-columns: 1fr 1fr;
      }
      .footer-top > :first-child,
      .footer-contact {
        grid-column: 1 / -1;
      }
      .footer-bottom {
        align-items: flex-start;
        flex-direction: column;
      }
    }
    @media (max-width: 560px) {
      .footer-top {
        grid-template-columns: 1fr;
      }
    }
    html[data-theme="light"] body {
      background:
        radial-gradient(circle at 18% 12%, rgba(197,139,42,.16), transparent 30rem),
        radial-gradient(circle at 86% 8%, rgba(197,139,42,.10), transparent 28rem),
        var(--bg);
    }
    html[data-theme="light"] .page-grid {
      opacity: .32;
      background-image:
        linear-gradient(rgba(15,23,42,.06) 1px, transparent 1px),
        linear-gradient(90deg, rgba(15,23,42,.06) 1px, transparent 1px);
    }
    html[data-theme="light"] .text-on-surface,
    html[data-theme="light"] .text-white,
    html[data-theme="light"] h1,
    html[data-theme="light"] h2,
    html[data-theme="light"] h3,
    html[data-theme="light"] h4 {
      color: #332820 !important;
    }
    html[data-theme="light"] .text-on-surface-variant,
    html[data-theme="light"] footer p,
    html[data-theme="light"] footer li,
    html[data-theme="light"] footer span {
      color: #756A60 !important;
    }
    html[data-theme="light"] .glass-card {
      background: rgba(255,255,255,.82);
      border-color: rgba(0,0,0,.08);
      box-shadow: 0 18px 45px rgba(15,23,42,.08);
    }
    html[data-theme="light"] .hero-course-card,
    html[data-theme="light"] .hero-carousel-empty,
    html[data-theme="light"] .hero-search-form,
    html[data-theme="light"] .hero-trust-item,
    html[data-theme="light"] .hero-card-wish,
    html[data-theme="light"] .hero-topic {
      background: #FAF7F1;
      border-color: rgba(0,0,0,.08);
    }
    html[data-theme="light"] .hero-mock-placeholder {
      background:
        linear-gradient(135deg, rgba(255,255,255,.86), rgba(241,245,249,.92)),
        #ffffff;
      box-shadow: 0 24px 70px rgba(15,23,42,.10);
    }
    html[data-theme="light"] .hero-mock-placeholder::before {
      background-image:
        linear-gradient(rgba(15,23,42,.055) 1px, transparent 1px),
        linear-gradient(90deg, rgba(15,23,42,.055) 1px, transparent 1px);
    }
    html[data-theme="light"] .hero-mock-placeholder::after {
      background: rgba(255,255,255,.74);
      border-color: rgba(0,0,0,.08);
    }
    html[data-theme="light"] .hero-cta-secondary,
    html[data-theme="light"] .rounded-2xl.bg-white\\/\\[\\.035\\] {
      background: rgba(255,255,255,.78) !important;
      border-color: rgba(0,0,0,.09) !important;
      color: #332820 !important;
    }
    html[data-theme="light"] .bg-black\\/80 {
      background: rgba(255,255,255,.92) !important;
      color: #A96F18 !important;
    }
    html[data-theme="light"] footer {
      background: rgba(255,255,255,.56) !important;
      border-top-color: rgba(0,0,0,.08) !important;
    }
    html[data-theme="light"] .site-footer {
      background:
        linear-gradient(180deg, rgba(255,255,255,.72), rgba(243,244,246,.94)),
        var(--bg) !important;
    }
    html[data-theme="light"] .footer-contact,
    html[data-theme="light"] .footer-trust-chip,
    html[data-theme="light"] .footer-socials a {
      background: rgba(255,255,255,.82);
      border-color: rgba(0,0,0,.08);
    }
    @media (max-width: 1100px) {
      .hero-trust-strip {
      grid-template-columns: repeat(3, minmax(0, 1fr));
      }
      .hero-carousel-shell {
        padding-inline: 0;
      }
      .learning-hero h1 {
        font-size: clamp(58px, 6vw, 66px);
        line-height: .98;
      }
      .learning-hero-copy > p {
        font-size: clamp(17px, 1.7vw, 18px);
        line-height: 1.55;
      }
    }
    @media (max-width: 760px) {
      .learning-hero {
        padding-top: 86px;
      }
      .learning-hero h1 {
        font-size: clamp(42px, 11.5vw, 48px);
        line-height: 1;
      }
      .learning-hero-copy > p {
        font-size: 16px;
        line-height: 1.55;
      }
      .learning-hero-actions,
      .hero-search-form {
        grid-template-columns: 1fr;
      }
      .learning-hero-actions .hero-cta-primary,
      .learning-hero-actions .hero-cta-secondary,
      .hero-search-btn {
        width: 100%;
      }
      .learning-hero-actions {
        margin-top: 8px;
      }
      .hero-search-block {
        margin-top: 56px;
      }
      .home-hero-tabs {
        width: auto;
        max-width: calc(100% - 32px);
        justify-content: center;
        gap: clamp(24px, 8vw, 36px);
      }
      .hero-carousel-shell {
        width: calc(100% + 32px);
        margin: 18px 0 0 -16px;
        padding: 8px 0 0;
      }
      .hero-carousel-viewport {
        padding: 18px 0 16px;
      }
      .hero-carousel-track {
        min-height: 360px;
      }
      .hero-course-card {
        flex-basis: min(78vw, 330px) !important;
        height: min(86vw, 360px) !important;
        transform: none;
      }
      .hero-trust-strip {
        grid-template-columns: 1fr;
      }
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` }
  ],
};

export default page;
