/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Sign In — Skillomate AI`,
  lang: `en`,
  stylesheets: [`css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      background: var(--bg, #000);
      color: var(--text, #fff);
      min-height: 100vh;
      width: 100%;
      display: block;
    }
    a { text-decoration: none; color: inherit; }

    :root {
      --bg: #000000;
      --text: #ffffff;
      --text2: #9ca3af;
      --nav-bg: rgba(0,0,0,0.95);
      --cyan: #C58B2A;
      --border: rgba(255,255,255,0.08);
      --border2: rgba(255,255,255,0.12);
      --card: #0d0f14;
      --input: #111418;
      --gray: #6b7280;
      --light: #9ca3af;
    }

    .lp-wrap {
      display: grid;
      grid-template-columns: minmax(0, 1fr) minmax(420px, 520px);
      width: 100%;
      max-width: 100%;
      min-height: 100vh;
      min-width: 0;
    }

    /* LEFT PANEL */
    .lp-left {
      background: #07090f;
      display: flex;
      flex-direction: column;
      padding: 42px 52px;
      position: relative;
      overflow: hidden;
      border-right: 1px solid var(--border);
      min-width: 0;
    }
    .lp-left::before {
      content: '';
      position: absolute;
      top: -120px; left: -120px;
      width: 380px; height: 380px;
      background: radial-gradient(circle, rgba(197,139,42,0.06) 0%, transparent 70%);
      pointer-events: none;
    }
    .lp-logo {
      font-size: 1.25rem;
      font-weight: 800;
      color: var(--cyan);
      flex-shrink: 0;
    }
    .lp-hero { margin-top: 56px; }
    .lp-hero .lp-marketing-title {
      font-family: var(--font-display);
      font-size: clamp(1.9rem, 3.2vw, 2.7rem);
      font-weight: 900;
      line-height: 1.14;
      margin-bottom: 18px;
      letter-spacing: 0;
    }
    .lp-hero .lp-marketing-title span { color: var(--cyan); }
    .lp-hero p {
      font-size: .88rem;
      color: var(--light);
      line-height: 1.78;
      max-width: 380px;
    }

    /* Testimonial */
    .lp-testimonial { margin-top: auto; padding-top: 36px; }
    .lp-test-card {
      background: var(--card);
      border: 1px solid var(--border2);
      border-radius: 18px;
      overflow: hidden;
    }
    .lp-test-photo {
      width: 100%; height: 230px;
      object-fit: cover; object-position: center 20%;
      display: block;
    }
    .lp-test-body { padding: 20px 22px; }
    .lp-big-quote {
      font-size: 2.4rem; line-height: 1;
      color: var(--cyan);
      font-family: "Fraunces", Georgia, serif;
      margin-bottom: 8px;
    }
    .lp-test-text {
      font-size: .82rem;
      color: #d1d5db;
      line-height: 1.7;
      margin-bottom: 16px;
    }
    .lp-author { display: flex; align-items: center; gap: 10px; }
    .lp-author-avatar {
      width: 34px; height: 34px;
      border-radius: 50%;
      object-fit: cover;
      border: 2px solid var(--border2);
    }
    .lp-author-name { font-size: .84rem; font-weight: 700; color: var(--text); }
    .lp-author-role { font-size: .72rem; color: var(--gray); }

    /* RIGHT PANEL */
    .lp-right {
      background: #000;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 40px 64px;
      min-width: 0;
    }
    .lp-form-box { width: 100%; max-width: 440px; min-width: 0; }
    .lp-form-box .lp-login-title {
      font-size: 2rem;
      font-weight: 800;
      margin-bottom: 6px;
      letter-spacing: 0;
    }
    .lp-subtitle {
      font-size: .86rem;
      color: var(--light);
      margin-bottom: 28px;
      line-height: 1.6;
    }

    /* Form groups */
    .lp-form-group { margin-bottom: 14px; }
    .lp-label-row {
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: 6px;
    }
    .lp-form-group > label,
    .lp-label-row label {
      font-size: .8rem; font-weight: 600; color: #d1d5db;
      display: block; margin-bottom: 6px;
    }
    .lp-label-row label { margin-bottom: 0; }
    .lp-forgot {
      font-size: .8rem; font-weight: 600; color: var(--cyan);
      transition: opacity .2s;
      border: 0;
      background: none;
      padding: 0;
      cursor: pointer;
      font: inherit;
      font-size: .8rem;
      font-weight: 600;
    }
    .lp-forgot:hover { opacity: .7; }
    .lp-input-wrap {
      display: flex; align-items: center; gap: 10px;
      background: var(--input);
      border: 1px solid var(--border2);
      border-radius: 12px;
      padding: 0 16px;
      transition: border-color .2s;
      position: relative;
      min-width: 0;
    }
    .lp-input-wrap:focus-within { border-color: var(--border2); }
    .lp-input-wrap i { color: var(--gray); font-size: .82rem; flex-shrink: 0; }
    .lp-input-wrap input {
      flex: 1; min-width: 0; background: none; border: none; outline: none;
      padding: 13px 0;
      font-size: .88rem; color: var(--text);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
    }
    .lp-prefix {
      font-size: .85rem; font-weight: 700; color: #aaa;
      padding: 0 8px 0 36px; white-space: nowrap; position: absolute;
      left: 0;
      pointer-events: none;
    }
    .lp-input-wrap input:focus {
      border-color: transparent;
      outline: none;
      box-shadow: none;
    }
    .lp-input-wrap input::placeholder { color: var(--gray); }
    .lp-eye-icon {
      color: var(--gray); font-size: .82rem;
      cursor: pointer; flex-shrink: 0; transition: color .2s;
      width: 32px; height: 32px; border: 0; background: none;
      display: inline-flex; align-items: center; justify-content: center;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
    }
    .lp-eye-icon:hover { color: var(--light); }

    /* Remember */
    .lp-remember {
      display: flex; align-items: center; gap: 8px;
      font-size: .82rem; color: var(--light);
      cursor: pointer; margin: 6px 0 20px;
    }
    .lp-remember input[type="checkbox"] {
      width: 16px; height: 16px;
      accent-color: var(--cyan);
      cursor: pointer; flex-shrink: 0;
    }

    /* Sign In button */
    .lp-signin-btn {
      width: 100%; padding: 14px;
      background: var(--cyan); color: #000;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .95rem; font-weight: 800;
      border: none; border-radius: 12px;
      cursor: pointer; transition: all .2s;
      margin-bottom: 14px;
    }
    .lp-signin-btn:hover {
      background: #C58B2A;
      box-shadow: 0 6px 24px rgba(197,139,42,.4);
    }

    /* Create account */
    .lp-create-row {
      text-align: center; font-size: .82rem;
      color: var(--light); margin-bottom: 30px;
    }
    .lp-create-row a { color: var(--cyan); font-weight: 700; }
    .lp-create-row a:hover { opacity: .8; }

    /* Footer links */
    .lp-footer-links {
      display: flex; align-items: center; justify-content: center; gap: 20px;
      padding-top: 24px;
      border-top: 1px solid var(--border);
    }
    .lp-footer-links a { font-size: .75rem; color: var(--gray); transition: color .2s; }
    .lp-footer-links a:hover { color: var(--light); }

    .lp-err { font-size: .8rem; color: #f87171; margin-bottom: 10px; text-align: center; }

    @media (max-width: 1280px) {
      .lp-wrap {
        display: block;
        min-height: 100svh;
        padding: 80px clamp(24px, 4vw, 40px) 40px;
      }
      .lp-left { display: none; }
      .lp-right {
        width: 100%;
        min-height: auto;
        padding: 0;
        background: transparent;
      }
      .lp-form-box { margin: 0 auto; }
    }
    @media (max-width: 768px) {
      .lp-wrap { padding: 76px 20px 34px; }
    }
    @media (max-width: 480px) {
      .lp-wrap { padding-left: 16px; padding-right: 16px; }
      .lp-form-box { padding: 24px 16px; }
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
