/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Skillomate — OTP Verification`,
  lang: `en`,
  stylesheets: [`css/style.css`, `css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    body{background:radial-gradient(ellipse 80% 60% at 50% -10%,rgba(197,139,42,.08) 0%,transparent 60%),var(--bg-primary)}
    .countdown{font-size:.88rem;color:var(--text-muted);margin-top:8px}
    .countdown span{color:var(--accent);font-weight:700}
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `js/main.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
