/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Start Learning | Skillomate`,
  lang: `en`,
  stylesheets: [`/main.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    body { background: #f8fafc; }

    /* ── Top nav (minimal) ─────────────────────────────── */
    .pay-nav {
      background: #fff;
      border-bottom: 1px solid var(--line);
      height: 64px;
      display: flex;
      align-items: center;
      padding: 0 32px;
      position: sticky;
      top: 0;
      z-index: 100;
    }
    .pay-nav-brand {
      display: flex;
      align-items: center;
      gap: 10px;
      font-size: 19px;
      font-weight: 900;
      color: var(--text);
      text-decoration: none;
    }
    .pay-nav-logo {
      width: 34px;
      height: 34px;
      border-radius: 9px;
      background: var(--cyan);
      color: #fff;
      display: grid;
      place-items: center;
      font-size: 16px;
      font-weight: 900;
    }
    .pay-nav-secure {
      margin-left: auto;
      display: flex;
      align-items: center;
      gap: 6px;
      font-size: 13px;
      font-weight: 700;
      color: var(--success);
    }

    /* ── Page layout ───────────────────────────────────── */
    .pay-page {
      min-height: calc(100vh - 64px);
      display: flex;
      align-items: flex-start;
      justify-content: center;
      padding: 48px 20px 80px;
    }
    .pay-grid {
      display: grid;
      grid-template-columns: 1fr 420px;
      gap: 32px;
      width: 100%;
      max-width: 960px;
      align-items: start;
    }

    /* ── Course preview card ───────────────────────────── */
    .course-preview {
      background: #fff;
      border: 1px solid var(--line);
      border-radius: 20px;
      overflow: hidden;
      box-shadow: var(--shadow);
    }
    .cp-recommended {
      padding: 14px 18px 0;
      color: var(--cyan);
      font-size: 11px;
      font-weight: 900;
      letter-spacing: .08em;
      text-transform: uppercase;
    }
    .cp-thumb {
      aspect-ratio: 16/9;
      background: var(--cyan);
      position: relative;
      overflow: hidden;
      margin: 10px 18px 0;
      border-radius: 16px;
    }
    .cp-thumb img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      display: block;
    }
    .cp-body { padding: 28px; }
    .cp-cat {
      display: inline-block;
      background: var(--primary-lt);
      color: var(--primary);
      font-size: 11px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: .06em;
      padding: 4px 12px;
      border-radius: 100px;
      margin-bottom: 14px;
    }
    .cp-title {
      font-size: 22px;
      font-weight: 900;
      line-height: 1.25;
      color: var(--text);
      margin-bottom: 10px;
    }
    .cp-desc {
      font-size: 14px;
      color: var(--muted);
      line-height: 1.7;
      margin-bottom: 20px;
      display: -webkit-box;
      -webkit-line-clamp: 3;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
    .cp-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 18px;
      padding-top: 18px;
      border-top: 1px solid var(--line);
    }
    .cp-meta-item {
      display: flex;
      align-items: center;
      gap: 6px;
      font-size: 13px;
      font-weight: 700;
      color: var(--muted);
    }
    .cp-meta-item .icon { font-size: 16px; }

    /* ── Includes list ─────────────────────────────────── */
    .cp-includes {
      padding: 20px 28px;
      background: var(--surface-alt);
      border-top: 1px solid var(--line);
    }
    .cp-includes p {
      font-size: 12px;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: .07em;
      color: var(--muted);
      margin-bottom: 12px;
    }
    .cp-includes ul {
      list-style: none;
      display: flex;
      flex-direction: column;
      gap: 8px;
    }
    .cp-includes li {
      font-size: 13px;
      color: var(--text-soft);
      font-weight: 600;
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .cp-includes li::before {
      content: '✓';
      color: var(--success);
      font-weight: 900;
      font-size: 14px;
      flex-shrink: 0;
    }

    /* ── Checkout card ─────────────────────────────────── */
    .checkout-card {
      background: #fff;
      border: 1px solid var(--line);
      border-radius: 20px;
      overflow: hidden;
      box-shadow: 0 20px 60px rgba(53,156,87,.1);
      position: sticky;
      top: 84px;
    }
    .checkout-header {
      background: var(--cyan);
      padding: 24px 28px;
      color: #fff;
      text-align: center;
    }
    .checkout-header h1,
    .checkout-header h2 {
      font-size: 20px;
      font-weight: 800;
      color: #fff;
      margin-bottom: 4px;
    }
    .checkout-header p {
      font-size: 13px;
      color: rgba(255,255,255,.75);
      margin: 0;
    }
    .checkout-body { padding: 28px; }

    /* Plan selector */
    .plan-selector { display: flex; flex-direction: column; gap: 12px; margin-bottom: 24px; }
    .plan-option {
      display: flex;
      align-items: center;
      gap: 14px;
      padding: 16px 18px;
      border: 2px solid var(--line);
      border-radius: 14px;
      cursor: pointer;
      transition: border-color .2s, background .2s;
      position: relative;
    }
    .plan-option:hover { border-color: var(--primary); }
    .plan-option.selected {
      border-color: var(--primary);
      background: var(--primary-lt);
    }
    .plan-option.disabled,
    .plan-option[aria-disabled="true"] {
      cursor: not-allowed;
      opacity: .62;
    }
    .plan-option.disabled:hover,
    .plan-option[aria-disabled="true"]:hover {
      border-color: var(--line);
    }
    .plan-option input[type="radio"] { display: none; }
    .plan-radio {
      width: 20px;
      height: 20px;
      border-radius: 50%;
      border: 2px solid var(--line);
      flex-shrink: 0;
      transition: border-color .2s, background .2s;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .plan-option.selected .plan-radio {
      border-color: var(--primary);
      background: var(--primary);
    }
    .plan-option.selected .plan-radio::after {
      content: '';
      width: 8px;
      height: 8px;
      border-radius: 50%;
      background: #fff;
    }
    .plan-info { flex: 1; }
    .plan-name {
      font-size: 15px;
      font-weight: 800;
      color: var(--text);
      margin-bottom: 2px;
    }
    .plan-desc { font-size: 12px; color: var(--muted); }
    .plan-price {
      text-align: right;
      flex-shrink: 0;
    }
    .plan-price .amount {
      font-size: 22px;
      font-weight: 900;
      color: var(--primary);
      line-height: 1;
    }
    .plan-price .per {
      font-size: 11px;
      color: var(--muted);
      display: block;
      margin-top: 2px;
    }
    .plan-badge {
      position: absolute;
      top: -1px;
      right: 14px;
      background: var(--cyan);
      color: #fff;
      font-size: 10px;
      font-weight: 800;
      padding: 3px 10px;
      border-radius: 0 0 8px 8px;
      text-transform: uppercase;
      letter-spacing: .05em;
    }

    /* Pay button */
    .pay-btn {
      width: 100%;
      height: 52px;
      border-radius: 14px;
      background: var(--cyan);
      color: #fff;
      font-size: 16px;
      font-weight: 800;
      border: none;
      cursor: pointer;
      transition: transform .2s, box-shadow .2s, opacity .2s;
      box-shadow: 0 6px 24px rgba(53,156,87,.4);
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 10px;
      margin-bottom: 16px;
    }
    .pay-btn:hover:not(:disabled) {
      transform: translateY(-2px);
      box-shadow: 0 10px 36px rgba(53,156,87,.5);
    }
    .pay-btn:disabled { opacity: .65; cursor: not-allowed; transform: none; }

    .login-cta-btn {
      width: 100%;
      height: 52px;
      border-radius: 14px;
      background: var(--cyan);
      color: #fff;
      font-size: 16px;
      font-weight: 800;
      border: none;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      box-shadow: 0 6px 24px rgba(53,156,87,.35);
      text-decoration: none;
      transition: transform .2s, box-shadow .2s;
      margin-bottom: 16px;
    }
    .login-cta-btn:hover { transform: translateY(-2px); box-shadow: 0 10px 36px rgba(53,156,87,.5); }

    .pay-btn-secondary {
      width: 100%;
      height: 44px;
      border-radius: 12px;
      background: transparent;
      border: 1.5px solid var(--line);
      color: var(--muted);
      font-size: 14px;
      font-weight: 700;
      cursor: pointer;
      transition: border-color .2s, color .2s;
      text-decoration: none;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    .pay-btn-secondary:hover { border-color: var(--primary); color: var(--primary); }

    .pay-msg { margin-bottom: 16px; }

    /* Security row */
    .pay-security {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 6px;
      font-size: 12px;
      color: var(--muted);
      font-weight: 600;
      margin-top: 16px;
    }
    .pay-security span { font-size: 15px; }

    /* Divider */
    .pay-divider {
      display: flex;
      align-items: center;
      gap: 12px;
      margin: 16px 0;
    }
    .pay-divider::before,
    .pay-divider::after {
      content: '';
      flex: 1;
      height: 1px;
      background: var(--line);
    }
    .pay-divider span { font-size: 12px; color: var(--muted); font-weight: 700; white-space: nowrap; }

    /* Already subscribed state */
    .subscribed-banner {
      background: var(--cyan);
      border: 1px solid #a7f3d0;
      border-radius: 14px;
      padding: 18px 20px;
      text-align: center;
      margin-bottom: 20px;
    }
    .subscribed-banner .icon { font-size: 28px; margin-bottom: 6px; }
    .subscribed-banner h3 { font-size: 15px; font-weight: 800; color: #15803d; margin-bottom: 4px; }
    .subscribed-banner p { font-size: 13px; color: #166534; margin: 0; }

    /* ── Post-payment choice modal ─────────────────────── */
    .payment-choice-modal {
      position: fixed;
      inset: 0;
      display: none;
      align-items: center;
      justify-content: center;
      padding: 20px;
      background: rgba(15, 23, 42, .55);
      backdrop-filter: blur(8px);
      z-index: 2000;
    }
    .payment-choice-modal.is-open {
      display: flex;
    }
    .payment-choice-card {
      width: min(100%, 440px);
      background: #fff;
      border: 1px solid var(--line);
      border-radius: 20px;
      box-shadow: 0 24px 80px rgba(15, 23, 42, .24);
      overflow: hidden;
    }
    .payment-choice-head {
      padding: 24px 24px 18px;
      background: var(--cyan);
      border-bottom: 1px solid rgba(21, 128, 61, .12);
    }
    .payment-choice-kicker {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      font-size: 11px;
      font-weight: 900;
      letter-spacing: .08em;
      text-transform: uppercase;
      color: #15803d;
      margin-bottom: 10px;
    }
    .payment-choice-title {
      font-size: 22px;
      line-height: 1.25;
      font-weight: 900;
      color: var(--text);
      margin: 0 0 8px;
    }
    .payment-choice-copy {
      font-size: 14px;
      line-height: 1.7;
      color: var(--muted);
      margin: 0;
    }
    .payment-choice-body {
      padding: 20px 24px 24px;
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    .payment-choice-actions {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 10px;
    }
    .payment-choice-btn {
      min-height: 48px;
      border-radius: 14px;
      border: 1.5px solid var(--line);
      font-size: 14px;
      font-weight: 800;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      text-decoration: none;
      cursor: pointer;
      transition: transform .2s, box-shadow .2s, border-color .2s;
    }
    .payment-choice-btn:hover {
      transform: translateY(-1px);
    }
    .payment-choice-btn.primary {
      background: var(--cyan);
      color: #fff;
      border-color: transparent;
      box-shadow: 0 10px 26px rgba(53,156,87,.28);
    }
    .payment-choice-btn.secondary {
      background: #fff;
      color: var(--text);
    }
    .payment-choice-meta {
      font-size: 12px;
      color: var(--muted);
      text-align: center;
      line-height: 1.6;
    }

    /* Skeleton loader */
    .cp-title-skel  { height: 28px; border-radius: 8px; margin-bottom: 10px; }
    .cp-desc-skel   { height: 60px; border-radius: 8px; margin-bottom: 20px; }

    /* ── Responsive ─────────────────────────────────────── */
    @media (max-width: 768px) {
      .pay-grid { grid-template-columns: 1fr; }
      .checkout-card { position: static; }
      .pay-page { padding: 24px 16px 60px; }
    }

    /* New Skillomate noir/cyan checkout theme */
    :root {
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,.10);
      --cyan-border: rgba(197,139,42,.28);
      --bg: #000;
      --card: #0d0d0d;
      --card2: #111318;
      --border: rgba(255,255,255,.08);
      --text: #fff;
      --text-soft: #d1d5db;
      --muted: #8b949e;
      --line: rgba(255,255,255,.10);
      --surface-alt: #111318;
      --primary: var(--cyan);
      --primary-lt: var(--cyan-dim);
      --success: var(--cyan);
      --shadow: 0 24px 80px rgba(0,0,0,.45);
    }
    body { background: #000; color: var(--text); font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; }
    .navbar {
      position: fixed; top: 0; left: 0; right: 0; z-index: 999;
      background: var(--nav-bg, rgba(0,0,0,0.92));
      backdrop-filter: blur(20px);
      border-bottom: 1px solid var(--border);
      padding: 16px 0;
    }
    .nav-inner { max-width: 1200px; margin: 0 auto; padding: 0 24px; display: flex; align-items: center; gap: 32px; }
    .nav-logo { font-size: 1.2rem; font-weight: 700; color: var(--text); white-space: nowrap; flex-shrink: 0; text-decoration: none; }
    .nav-logo span { color: var(--cyan); }
    .nav-links { display: flex; align-items: center; gap: 4px; flex: 1; justify-content: center; list-style: none; margin: 0; padding: 0; }
    .nav-links a { padding: 8px 14px; font-size: .9rem; font-weight: 500; color: var(--text2, #9ca3af); transition: color .2s; position: relative; text-decoration: none; }
    .nav-links a:hover { color: var(--text); }
    .nav-links a.active { color: var(--text); font-weight: 600; }
    .nav-links a.active::after { content: ''; position: absolute; bottom: 0; left: 14px; right: 14px; height: 2px; background: var(--cyan); border-radius: 2px; }
    .nav-right { display: flex; align-items: center; gap: 12px; flex-shrink: 0; }
    .nav-login { font-size: .9rem; font-weight: 500; color: var(--text2, #9ca3af); transition: color .2s; text-decoration: none; }
    .nav-login:hover { color: var(--cyan); }
    .nav-avatar { width: 36px; height: 36px; border-radius: 50%; background: var(--card2); border: 1px solid var(--border); display: flex; align-items: center; justify-content: center; font-size: .85rem; color: var(--gray, #888); cursor: pointer; transition: border-color .2s; text-decoration: none; }
    .nav-avatar:hover { border-color: var(--cyan); color: var(--cyan); }
    .nav-hamburger { display: none; flex-direction: column; gap: 5px; background: none; border: none; cursor: pointer; padding: 4px; }
    .nav-hamburger span { display: block; width: 22px; height: 2px; background: var(--text); border-radius: 2px; transition: .3s; }
    @media (max-width: 840px) { .nav-links, .nav-right { display: none; } .nav-hamburger { display: flex; margin-left: auto; } }
    .pay-page { padding-top: 112px; }
    .course-preview,
    .checkout-card {
      background: rgba(13,13,13,.94);
      border-color: var(--border);
      box-shadow: var(--shadow);
      border-radius: 18px;
    }
    .cp-recommended,
    .cp-cat,
    .plan-price .amount {
      color: var(--cyan);
    }
    .cp-cat {
      background: var(--cyan-dim);
      border: 1px solid var(--cyan-border);
    }
    .cp-title,
    .plan-name,
    .payment-choice-title {
      color: var(--text);
    }
    .cp-desc,
    .plan-desc,
    .pay-security,
    .payment-choice-copy,
    .payment-choice-meta {
      color: var(--muted);
    }
    .cp-thumb {
      background: #111318;
      border: 1px solid var(--border);
    }
    .checkout-header,
    .plan-badge,
    .pay-btn,
    .login-cta-btn,
    .payment-choice-btn.primary {
      background: var(--cyan);
      color: #000;
      box-shadow: 0 14px 34px rgba(197,139,42,.18);
    }
    .checkout-header h1,
    .checkout-header h2,
    .checkout-header p {
      color: #000;
    }
    .checkout-body,
    .cp-includes {
      background: transparent;
    }
    .plan-option {
      background: var(--card2);
      border-color: var(--border);
    }
    .plan-option:hover,
    .plan-option.selected {
      border-color: var(--cyan);
      background: rgba(197,139,42,.08);
    }
    .plan-option.selected .plan-radio {
      border-color: var(--cyan);
      background: var(--cyan);
    }
    .pay-btn-secondary,
    .payment-choice-btn.secondary {
      background: transparent;
      color: var(--text);
      border-color: var(--border);
    }
    .pay-btn-secondary:hover,
    .payment-choice-btn.secondary:hover {
      border-color: var(--cyan);
      color: var(--cyan);
    }
    .subscribed-banner,
    .payment-choice-card {
      background: var(--card);
      border-color: var(--border);
    }
    .payment-choice-head {
      background: var(--card2);
      border-color: var(--border);
    }
    .payment-choice-modal {
      background: rgba(0,0,0,.72);
    }
    .cp-thumb {
      background: #111318 !important;
      border: 1px solid var(--border) !important;
    }
    .cp-thumb img {
      width: 100% !important;
      height: 100% !important;
      object-fit: cover !important;
      display: block !important;
      border: 0 !important;
      border-radius: 0 !important;
      box-shadow: none !important;
      position: static !important;
    }
    .checkout-header,
    .plan-badge,
    .pay-btn,
    .login-cta-btn,
    .payment-choice-btn.primary {
      background: var(--cyan) !important;
      color: #000 !important;
    }
    .subscribed-banner,
    .payment-choice-head {
      background: var(--cyan-dim) !important;
      border-color: var(--cyan-border) !important;
    }
    .subscribed-banner h3,
    .subscribed-banner p,
    .payment-choice-kicker {
      color: var(--cyan) !important;
    }
    .pay-btn:hover:not(:disabled),
    .login-cta-btn:hover,
    .payment-choice-btn.primary:hover {
      box-shadow: 0 12px 32px rgba(197,139,42,.28) !important;
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` }
  ],
};

export default page;
