/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Profile Settings — EduNex AI`,
  lang: `en`,
  stylesheets: [`css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { overflow-x: hidden; }
    body {
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      background: var(--bg, #000);
      color: var(--text, #fff);
      min-height: 100vh;
    }
    a { text-decoration: none; color: inherit; }

    :root {
      --bg: #000000;
      --text: #ffffff;
      --text2: #9ca3af;
      --nav-bg: rgba(0,0,0,0.95);
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,0.1);
      --cyan-border: rgba(197,139,42,0.25);
      --card: #0d0d0d;
      --card2: #111318;
      --border: rgba(255,255,255,0.07);
      --border2: rgba(255,255,255,0.1);
      --gray: #6b7280;
      --light: #9ca3af;
      --danger: #f87171;
    }

    /* ===== NAVBAR ===== */
    .navbar {
      position: fixed; top: 0; left: 0; right: 0; z-index: 999;
      background: var(--nav-bg);
      backdrop-filter: blur(20px);
      border-bottom: 1px solid var(--border);
      padding: 16px 0;
    }
    .nav-inner {
      max-width: 1200px; margin: 0 auto; padding: 0 24px;
      display: flex; align-items: center; gap: 40px;
    }
    .nav-logo { font-size: 1.2rem; font-weight: 700; color: #fff; white-space: nowrap; flex-shrink: 0; }
    .nav-logo span { color: var(--cyan); }
    .nav-links { display: flex; align-items: center; gap: 4px; flex: 1; justify-content: center; }
    .nav-links a { padding: 8px 16px; font-size: .9rem; font-weight: 500; color: var(--text2); transition: color .2s; position: relative; }
    .nav-links a:hover { color: var(--text); }
    .nav-links a.active { color: var(--text); font-weight: 600; }
    .nav-links a.active::after {
      content: ''; position: absolute; bottom: 0; left: 16px; right: 16px;
      height: 2px; background: var(--cyan); border-radius: 2px;
    }
    .nav-right { display: flex; align-items: center; gap: 16px; flex-shrink: 0; }
    .nav-login { font-size: .9rem; font-weight: 500; color: var(--text2); transition: color .2s; }
    .nav-login:hover { color: var(--cyan); }
    .nav-avatar {
      width: 36px; height: 36px; border-radius: 50%;
      background: var(--card2); border: 1px solid var(--border);
      display: flex; align-items: center; justify-content: center;
      font-size: .85rem; color: #888; cursor: pointer;
    }
    .nav-hamburger { display: none; flex-direction: column; gap: 5px; background: none; border: none; cursor: pointer; padding: 4px; }
    .nav-hamburger span { display: block; width: 22px; height: 2px; background: #fff; border-radius: 2px; }
    .nav-links li:not(:last-child)::after { content: '' !important; display: none !important; }
    .nav-links a:not(:last-of-type)::after { content: '' !important; display: none !important; }
    .nav-links li { display: flex !important; align-items: center; }

    /* ===== PAGE CONTENT ===== */
    .pf-page {
      padding: 96px 24px 20px;
      max-width: 1100px;
      margin: 0 auto;
    }

    /* Breadcrumb */
    .pf-breadcrumb {
      display: flex; align-items: center; gap: 6px;
      font-size: .82rem; margin-bottom: 24px;
    }
    .pf-breadcrumb a { color: var(--light); transition: color .2s; }
    .pf-breadcrumb a:hover { color: #fff; }
    .pf-breadcrumb .sep { color: var(--gray); font-size: .7rem; }
    .pf-breadcrumb .current { color: #fff; font-weight: 600; }

    .pf-page-title {
      font-size: 1.7rem; font-weight: 800;
      letter-spacing: 0; margin-bottom: 24px;
    }
    .pf-status {
      display: none;
      margin: -8px 0 18px;
      padding: 12px 14px;
      border-radius: 12px;
      border: 1px solid rgba(197,139,42,.24);
      background: rgba(197,139,42,.08);
      color: var(--light);
      font-size: .86rem;
      line-height: 1.5;
    }
    .pf-status.show { display: block; }
    .pf-status.error {
      border-color: rgba(248,113,113,.3);
      background: rgba(248,113,113,.08);
      color: #fecaca;
    }
    .pf-status button {
      margin-left: 10px;
      border: 0;
      background: transparent;
      color: var(--cyan);
      font: inherit;
      font-weight: 800;
      cursor: pointer;
    }

    /* ===== CARDS ===== */
    .pf-card {
      background: var(--card2);
      border: 1px solid var(--border2);
      border-radius: 16px;
      padding: 24px;
    }

    /* Profile info card */
    .pf-profile-card {
      display: flex; align-items: center; gap: 22px;
      margin-bottom: 20px;
    }
    .pf-avatar-wrap { position: relative; flex-shrink: 0; }
    .pf-avatar {
      width: 88px; height: 88px; border-radius: 14px;
      object-fit: cover; object-position: center top;
      display: block; border: 2px solid var(--border2);
    }
    .pf-avatar-online {
      position: absolute; bottom: 4px; right: 4px;
      width: 14px; height: 14px; border-radius: 50%;
      background: var(--cyan); border: 2px solid var(--card2);
    }
    .pf-profile-info { flex: 1; }
    .pf-profile-name { font-size: 1.4rem; font-weight: 800; letter-spacing: 0; margin-bottom: 3px; }
    .pf-profile-email { font-size: .82rem; color: var(--light); margin-bottom: 10px; }
    .pf-badges { display: flex; gap: 8px; flex-wrap: wrap; }
    .pf-badge { padding: 4px 12px; border-radius: 100px; font-size: .72rem; font-weight: 700; }
    .pf-badge-teal {
      background: rgba(197,139,42,0.14);
      border: 1px solid rgba(197,139,42,0.34);
      color: #DAB77A;
    }
    .pf-badge-gray {
      background: rgba(255,255,255,0.06);
      border: 1px solid var(--border2);
      color: var(--light);
    }
    .pf-edit-btn {
      display: flex; align-items: center; gap: 7px;
      padding: 9px 18px;
      background: rgba(255,255,255,0.05);
      border: 1px solid var(--border2);
      border-radius: 10px;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .82rem; font-weight: 600; color: #d1d5db;
      cursor: pointer; transition: all .2s;
      flex-shrink: 0; align-self: flex-start;
    }
    .pf-edit-btn:hover { border-color: rgba(255,255,255,.22); color: #fff; }
    .pf-edit-btn i { font-size: .78rem; }
    .pf-profile-actions {
      display: flex;
      flex-direction: column;
      gap: 10px;
      flex-shrink: 0;
      align-self: flex-start;
    }
    .pf-secondary-btn {
      display: flex; align-items: center; justify-content: center; gap: 7px;
      padding: 9px 18px;
      background: rgba(197,139,42,.08);
      border: 1px solid rgba(197,139,42,.24);
      border-radius: 10px;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .82rem; font-weight: 700; color: var(--cyan);
      cursor: pointer; transition: all .2s;
      white-space: nowrap;
    }
    .pf-secondary-btn:hover { background: rgba(197,139,42,.14); color: #fff; }

    /* Two-column row */
    .pf-row-2 {
      display: grid; grid-template-columns: 1fr 1fr;
      gap: 20px; margin-bottom: 20px;
    }

    /* Card heading */
    .pf-card-heading {
      display: flex; align-items: center; gap: 10px;
      font-size: .95rem; font-weight: 700; color: #fff;
      margin-bottom: 20px;
    }
    .pf-card-heading i { color: var(--cyan); font-size: .92rem; }

    /* Theme section */
    .pf-theme-grid { display: flex; gap: 14px; }
    .pf-theme-opt { flex: 1; cursor: pointer; }
    .pf-theme-preview {
      border-radius: 10px; height: 68px;
      border: 2px solid var(--border2);
      display: flex; flex-direction: column; gap: 5px;
      padding: 10px; transition: all .2s;
      margin-bottom: 8px; overflow: hidden;
    }
    .pf-theme-bar { height: 6px; border-radius: 3px; }
    .pf-theme-opt[data-theme="light"] .pf-theme-preview { background: #e5e7eb; }
    .pf-theme-opt[data-theme="light"] .pf-theme-bar { background: rgba(0,0,0,0.15); }
    .pf-theme-opt[data-theme="noir"] .pf-theme-preview { background: #0a0c12; }
    .pf-theme-opt[data-theme="noir"] .pf-theme-bar { background: rgba(197,139,42,0.3); }
    .pf-theme-opt[data-theme="system"] .pf-theme-preview { background: #374151; }
    .pf-theme-opt[data-theme="system"] .pf-theme-bar { background: rgba(255,255,255,0.2); }
    .pf-theme-opt.selected .pf-theme-preview {
      border-color: var(--cyan);
      box-shadow: 0 0 0 1px var(--cyan);
    }
    .pf-theme-label {
      font-size: .78rem; font-weight: 600;
      text-align: center; color: var(--light); transition: color .2s;
    }
    .pf-theme-opt.selected .pf-theme-label { color: var(--cyan); }

    /* List items */
    .pf-list-item {
      display: flex; align-items: center; gap: 12px;
      padding: 13px 0;
      border-bottom: 1px solid var(--border);
      cursor: pointer; transition: all .15s;
    }
    .pf-list-item:last-child { border-bottom: none; padding-bottom: 0; }
    .pf-list-item:first-child { padding-top: 0; }
    .pf-list-icon {
      width: 34px; height: 34px; border-radius: 8px;
      background: rgba(255,255,255,0.04);
      display: flex; align-items: center; justify-content: center;
      font-size: .8rem; color: var(--light);
      flex-shrink: 0; transition: all .2s;
    }
    .pf-list-item:hover .pf-list-icon { background: var(--cyan-dim); color: var(--cyan); }
    .pf-list-label {
      flex: 1; font-size: .86rem; font-weight: 500;
      color: #d1d5db; transition: color .2s;
    }
    .pf-list-item:hover .pf-list-label { color: #fff; }
    .pf-list-chevron {
      color: var(--gray); font-size: .72rem; transition: transform .2s;
    }
    .pf-list-item:hover .pf-list-chevron { transform: translateX(3px); color: var(--light); }

    /* Preferences card */
    .pf-prefs-card { margin-bottom: 32px; }
    .pf-prefs-inner {
      display: grid; grid-template-columns: 1fr auto;
      gap: 24px;
    }
    .pf-prefs-right {
      display: flex; flex-direction: column;
      align-items: flex-end; justify-content: flex-end; gap: 10px;
    }
    .pf-logout-btn {
      display: flex; align-items: center; gap: 8px;
      padding: 11px 20px;
      background: rgba(248,113,113,0.1);
      border: 1px solid rgba(248,113,113,0.25);
      border-radius: 10px;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .84rem; font-weight: 700; color: #f87171;
      cursor: pointer; transition: all .2s; white-space: nowrap;
    }
    .pf-logout-btn:hover {
      background: rgba(248,113,113,0.18);
      border-color: rgba(248,113,113,0.4);
    }
    .pf-version-text { font-size: .68rem; color: var(--gray); text-align: right; }
    .pf-version-text span { color: #DAB77A; font-weight: 600; }

    /* Watermark */
    .pf-watermark {
      text-align: center; padding: 20px 24px 36px;
      user-select: none;
    }
    .pf-watermark-main {
      font-size: clamp(2.4rem, 5vw, 4rem);
      font-weight: 900; letter-spacing: .35em;
      color: rgba(255,255,255,0.04);
      line-height: 1; margin-bottom: 6px;
    }
    .pf-watermark-sub {
      font-size: .62rem; font-weight: 700;
      letter-spacing: .38em; text-transform: uppercase;
      color: rgba(255,255,255,0.04);
    }
    .pf-modal {
      position: fixed; inset: 0; z-index: 9992;
      display: grid; place-items: center;
      padding: 18px;
      background: rgba(0,0,0,.72);
      backdrop-filter: blur(10px);
    }
    .pf-modal[hidden] { display: none !important; }
    .pf-modal-card {
      width: min(720px, 100%);
      max-height: min(760px, 90vh);
      overflow: auto;
      border: 1px solid var(--border2);
      border-radius: 18px;
      background: var(--card2);
      box-shadow: 0 28px 90px rgba(0,0,0,.42);
    }
    .pf-modal-head {
      display: flex; align-items: center; justify-content: space-between; gap: 14px;
      padding: 18px 20px;
      border-bottom: 1px solid var(--border);
    }
    .pf-modal-head h2 { margin: 0; font-size: 1rem; color: var(--text); }
    .pf-modal-close {
      width: 34px; height: 34px;
      border-radius: 10px;
      border: 1px solid var(--border2);
      background: rgba(255,255,255,.05);
      color: var(--light);
      cursor: pointer;
    }
    .pf-modal-body { padding: 20px; display: grid; gap: 14px; }
    .sub-current-card,
    .sub-history-row {
      border: 1px solid var(--border);
      border-radius: 14px;
      background: rgba(255,255,255,.04);
      padding: 16px;
    }
    .sub-current-card strong,
    .sub-history-row strong {
      display: block;
      color: var(--text);
      margin-bottom: 6px;
    }
    .sub-current-card span,
    .sub-history-row span {
      display: block;
      color: var(--light);
      font-size: .82rem;
      line-height: 1.6;
    }
    .sub-history-list { display: grid; gap: 10px; }

    /* Responsive */
    @media (max-width: 900px) {
      .pf-row-2 { grid-template-columns: 1fr; }
      .pf-prefs-inner { grid-template-columns: 1fr; }
      .pf-prefs-right { align-items: flex-start; }
      .pf-profile-card { flex-wrap: wrap; }
      .pf-profile-actions { width: 100%; }
      .pf-edit-btn, .pf-secondary-btn { width: 100%; justify-content: center; }
      .nav-links { display: none; }
      .nav-hamburger { display: flex; }
      .pf-page { padding-top: 80px; }
    }
    @media (max-width: 480px) {
      .container { padding: 0 16px; }
    }
    html[data-theme="light"] .nav-logo,
    html[data-theme="light"] .nav-links a.active,
    html[data-theme="light"] .pf-page-title,
    html[data-theme="light"] .pf-profile-name,
    html[data-theme="light"] .pf-card-heading,
    html[data-theme="light"] .pf-breadcrumb .current {
      color: #2B211A !important;
    }
    html[data-theme="light"] .nav-links a,
    html[data-theme="light"] .nav-login,
    html[data-theme="light"] .pf-profile-email,
    html[data-theme="light"] .pf-breadcrumb a,
    html[data-theme="light"] .pf-theme-label,
    html[data-theme="light"] .pf-version-text {
      color: #756A60 !important;
    }
    html[data-theme="light"] .pf-card,
    html[data-theme="light"] .pf-profile-card,
    html[data-theme="light"] .pf-modal-card,
    html[data-theme="light"] .sub-current-card,
    html[data-theme="light"] .sub-history-row {
      background: #FFFDF8 !important;
      border-color: #E2D6C6 !important;
      box-shadow: 0 8px 24px rgba(88,65,34,.06);
    }
    html[data-theme="light"] .pf-list-label {
      color: #5F534A !important;
    }
    html[data-theme="light"] .pf-list-icon,
    html[data-theme="light"] .pf-edit-btn,
    html[data-theme="light"] .pf-secondary-btn {
      background: #FAF5ED !important;
      border-color: #E2D6C6 !important;
      color: #9A681F !important;
    }
    html[data-theme="light"] .pf-list-item {
      border-color: #E6DACB !important;
    }
    html[data-theme="light"] .pf-list-item:hover .pf-list-label,
    html[data-theme="light"] .pf-breadcrumb a:hover {
      color: #A96F18 !important;
    }
    html[data-theme="light"] .pf-theme-opt[data-theme="noir"] .pf-theme-label {
      color: #2B211A !important;
      font-weight: 700;
    }
    html[data-theme="light"] .pf-badge-teal,
    html[data-theme="light"] .pf-badge-gray {
      background: #F3E4C8 !important;
      border-color: #DAB77A !important;
      color: #8E621D !important;
    }
    html[data-theme="light"] .pf-watermark-main,
    html[data-theme="light"] .pf-watermark-sub {
      color: rgba(88,65,34,.055) !important;
    }
    html:not([data-theme="light"]) .pf-page-title,
    html:not([data-theme="light"]) .pf-profile-name,
    html:not([data-theme="light"]) .pf-card-heading,
    html:not([data-theme="light"]) .pf-breadcrumb .current {
      color: #ffffff !important;
    }
    html:not([data-theme="light"]) .pf-profile-email,
    html:not([data-theme="light"]) .pf-breadcrumb a,
    html:not([data-theme="light"]) .pf-theme-label,
    html:not([data-theme="light"]) .pf-version-text,
    html:not([data-theme="light"]) .pf-list-chevron {
      color: #9ca3af !important;
    }
    html:not([data-theme="light"]) .pf-list-label {
      color: #d1d5db !important;
    }
    html:not([data-theme="light"]) .pf-list-item:hover .pf-list-label,
    html:not([data-theme="light"]) .pf-breadcrumb a:hover {
      color: #ffffff !important;
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
