/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Create Account — Skillomate AI`,
  lang: `en`,
  stylesheets: [`css/animations.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { scroll-behavior: smooth; overflow-x: hidden; }
    body { font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; background: var(--bg, #000); color: var(--text, #fff); min-height: 100vh; display: flex; flex-direction: column; }
    a { text-decoration: none; color: inherit; }
    img { display: block; max-width: 100%; }

    :root {
      --bg: #000000;
      --text: #ffffff;
      --text2: #9ca3af;
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,0.08);
      --cyan-border: rgba(197,139,42,0.25);
      --border: rgba(255,255,255,0.08);
      --border2: rgba(255,255,255,0.12);
      --card: #0d0f14;
      --input: #111418;
      --gray: #6b7280;
      --light: #9ca3af;
    }

    /* ===== NAVBAR ===== */
    .sp-nav {
      position: sticky; top: 0; z-index: 200;
      background: rgba(0,0,0,0.96);
      backdrop-filter: blur(20px);
      border-bottom: 1px solid var(--border);
      padding: 14px 0; flex-shrink: 0;
    }
    .sp-nav-inner {
      max-width: 1160px; margin: 0 auto; padding: 0 28px;
      display: flex; align-items: center; gap: 32px;
    }
    .sp-nav-logo {
      font-size: 1.05rem; font-weight: 800; flex-shrink: 0;
    }
    .sp-nav-logo span { color: var(--cyan); }
    .sp-nav-links {
      display: flex; align-items: center; gap: 4px; flex: 1;
    }
    .sp-nav-links a {
      padding: 7px 14px; font-size: .86rem; font-weight: 500;
      color: var(--light); transition: color .2s; border-radius: 8px;
    }
    .sp-nav-links a:hover { color: #fff; }
    .sp-nav-right { display: flex; align-items: center; gap: 10px; flex-shrink: 0; }
    .sp-btn-ghost {
      padding: 8px 18px; border: 1px solid var(--border2);
      border-radius: 10px; font-size: .84rem; font-weight: 600;
      color: var(--light); transition: all .2s; cursor: pointer;
      background: none; font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
    }
    .sp-btn-ghost:hover { color: #fff; border-color: rgba(255,255,255,.22); }
    .sp-btn-cyan {
      padding: 9px 20px; background: var(--cyan); border: none;
      border-radius: 10px; font-size: .84rem; font-weight: 700;
      color: #000; cursor: pointer; font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      transition: all .2s;
    }
    .sp-btn-cyan:hover { background: #A96F18; }

    /* ===== MAIN SPLIT ===== */
    .sp-main {
      flex: 1; display: flex;
      min-height: calc(100vh - 60px - 260px);
    }

    /* LEFT — photo panel */
    .sp-photo {
      flex: 0 0 42%;
      position: relative;
      overflow: hidden;
      min-height: 600px;
    }
    .sp-photo img {
      width: 100%; height: 100%;
      object-fit: cover; object-position: center top;
      filter: brightness(0.82);
      display: block;
    }
    .sp-photo-overlay {
      position: absolute; inset: 0;
      background: linear-gradient(to top, rgba(0,0,0,0.92) 0%, rgba(0,0,0,0.3) 50%, transparent 75%);
    }
    .sp-photo-bottom {
      position: absolute; bottom: 40px; left: 32px; right: 32px;
    }
    .sp-photo-heading {
      font-size: 1.8rem; font-weight: 900;
      line-height: 1.15; margin-bottom: 14px;
      letter-spacing: 0;
    }
    .sp-photo-quote {
      display: flex; align-items: flex-start; gap: 10px;
      margin-bottom: 18px;
    }
    .sp-photo-quote i {
      color: var(--cyan); font-size: .85rem; margin-top: 3px; flex-shrink: 0;
    }
    .sp-photo-quote p {
      font-size: .82rem; color: #c8cdd4; line-height: 1.65;
    }
    .sp-photo-cta {
      display: inline-flex; align-items: center; gap: 8px;
      padding: 10px 20px;
      border: 1px solid rgba(197,139,42,0.4);
      border-radius: 100px;
      font-size: .82rem; font-weight: 600;
      color: #fff; transition: all .2s;
    }
    .sp-photo-cta:hover { background: rgba(197,139,42,0.1); }
    .sp-photo-cta i { color: var(--cyan); }

    /* RIGHT — form panel */
    .sp-form-panel {
      flex: 1;
      background: #000;
      display: flex;
      align-items: center;
      justify-content: center;
      padding: 52px 64px;
    }

    /* Form steps */
    .sp-step { display: none; width: 100%; max-width: 360px; }
    .sp-step.active { display: block; }

    .sp-form-title {
      font-size: 1.7rem; font-weight: 800;
      letter-spacing: 0; margin-bottom: 5px;
    }
    .sp-form-sub {
      font-size: .83rem; color: var(--light);
      margin-bottom: 28px; line-height: 1.6;
    }

    .sp-field-label {
      font-size: .8rem; font-weight: 600;
      color: #d1d5db; display: block; margin-bottom: 6px;
    }
    .sp-input-row {
      display: flex; align-items: center; gap: 0;
      background: var(--input);
      border: 1px solid var(--border2);
      border-radius: 12px;
      overflow: hidden;
      transition: border-color .2s;
      margin-bottom: 16px;
    }
    .sp-input-row:focus-within { border-color: var(--border2); }
    .sp-prefix {
      padding: 13px 14px;
      font-size: .88rem; font-weight: 600;
      color: var(--light); white-space: nowrap;
      border-right: 1px solid var(--border2);
    }
    .sp-input-row input {
      flex: 1; background: none; border: none; outline: none;
      padding: 13px 16px;
      font-size: .88rem; color: #fff;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
    }
    .sp-input-row input:focus {
      border-color: transparent;
      outline: none;
      box-shadow: none;
    }
    .sp-input-row input::placeholder { color: var(--gray); }

    /* Checkbox */
    .sp-checkbox-row {
      display: flex; align-items: center; gap: 9px;
      font-size: .8rem; color: var(--light);
      margin-bottom: 20px; cursor: pointer;
    }
    .sp-checkbox-row input {
      width: 16px; height: 16px;
      accent-color: var(--cyan); cursor: pointer; flex-shrink: 0;
    }
    .sp-checkbox-row a { color: var(--cyan); font-weight: 600; }
    .sp-checkbox-row a:hover { opacity: .8; }

    /* Primary button */
    .sp-primary-btn {
      width: 100%; padding: 14px;
      background: var(--cyan); color: #000;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .93rem; font-weight: 800;
      border: none; border-radius: 12px;
      cursor: pointer; transition: all .2s;
      margin-bottom: 16px;
    }
    .sp-primary-btn:hover {
      background: #A96F18;
      box-shadow: 0 6px 22px rgba(197,139,42,.38);
    }
    .sp-primary-btn:disabled {
      opacity: .5; cursor: not-allowed;
    }

    /* Login link */
    .sp-login-row {
      text-align: center; font-size: .82rem;
      color: var(--light);
    }
    .sp-login-row a { color: var(--cyan); font-weight: 700; }
    .sp-login-row a:hover { opacity: .8; }

    /* ===== OTP BOXES ===== */
    .sp-otp-label {
      font-size: 1rem; font-weight: 700;
      color: #fff; margin-bottom: 5px;
    }
    .sp-otp-desc {
      font-size: .82rem; color: var(--light);
      margin-bottom: 22px; line-height: 1.6;
    }
    .sp-otp-boxes {
      display: flex; gap: 10px; margin-bottom: 22px;
    }
    .sp-otp-box {
      flex: 1; aspect-ratio: 1/1;
      max-width: 52px; max-height: 52px;
      background: var(--input);
      border: 1px solid var(--border2);
      border-radius: 10px;
      font-size: 1.3rem; font-weight: 700;
      color: #fff; text-align: center;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      outline: none; transition: border-color .2s;
    }
    .sp-otp-box:focus {
      border-color: var(--border2);
      outline: none;
      box-shadow: none;
    }
    .sp-resend {
      text-align: center;
      font-size: .8rem; color: var(--light);
      margin-bottom: 22px;
    }
    .sp-resend a, .sp-resend span.link, .sp-resend button.link {
      color: var(--cyan); font-weight: 700; cursor: pointer;
      border: 0; background: transparent; padding: 0; font: inherit;
    }

    /* ===== PROFILE STEP (step 3 full-width) ===== */
    .sp-profile-wrap {
      display: none;
      flex-direction: column;
      align-items: center;
      padding: 60px 28px;
    }
    .sp-profile-wrap.active { display: flex; flex: 1; }
    .sp-profile-heading {
      font-size: clamp(1.6rem, 3vw, 2rem);
      font-weight: 800; color: var(--cyan);
      text-align: center; margin-bottom: 8px;
      letter-spacing: 0;
    }
    .sp-profile-sub {
      font-size: .86rem; color: var(--light);
      text-align: center; margin-bottom: 32px;
      max-width: 380px; line-height: 1.65;
    }
    .sp-profile-card {
      background: var(--card);
      border: 1px solid var(--border2);
      border-radius: 18px;
      padding: 32px 28px;
      width: 100%; max-width: 500px;
    }

    /* Avatar centered circle */
    .sp-ava-center {
      display: flex; flex-direction: column; align-items: center;
      margin-bottom: 20px;
    }
    .sp-ava-circle {
      width: 90px; height: 90px; border-radius: 50%;
      border: 2.5px solid var(--cyan);
      background: #111; overflow: hidden;
      cursor: pointer; position: relative;
      box-shadow: 0 0 0 4px rgba(197,139,42,.12);
      transition: box-shadow .22s, transform .18s;
    }
    .sp-ava-circle:hover { box-shadow: 0 0 0 7px rgba(197,139,42,.18); transform: scale(1.04); }
    .sp-ava-circle img { width: 100%; height: 100%; object-fit: cover; display: block; }
    .sp-ava-circle-edit {
      position: absolute; bottom: 0; left: 0; right: 0;
      background: rgba(197,139,42,.82); color: #000;
      font-size: .58rem; font-weight: 800; text-align: center;
      padding: 4px 0; letter-spacing: .05em;
      opacity: 0; transition: opacity .18s;
    }
    .sp-ava-circle:hover .sp-ava-circle-edit { opacity: 1; }
    .sp-ava-circle-name {
      margin-top: 8px; font-size: .78rem; font-weight: 700; color: #fff;
    }
    .sp-ava-circle-hint { font-size: .68rem; color: var(--gray); margin-top: 2px; }

    /* Avatar modal */
    .sp-ava-modal-overlay {
      display: none; position: fixed; inset: 0; z-index: 9999;
      background: rgba(0,0,0,.72); backdrop-filter: blur(6px);
      align-items: center; justify-content: center;
    }
    .sp-ava-modal-overlay.open { display: flex; }
    .sp-ava-modal {
      background: #0d0d0d; border: 1px solid rgba(255,255,255,.1);
      border-radius: 20px; padding: 24px 22px;
      width: 340px; max-width: 92vw;
      animation: avaModalIn .22s cubic-bezier(.4,0,.2,1);
    }
    @keyframes avaModalIn { from { opacity:0; transform:translateY(18px) scale(.97); } to { opacity:1; transform:none; } }
    .sp-ava-modal-head {
      display: flex; align-items: center; justify-content: space-between;
      margin-bottom: 16px;
    }
    .sp-ava-modal-title { font-size: .9rem; font-weight: 800; color: #fff; }
    .sp-ava-modal-close {
      width: 28px; height: 28px; border-radius: 8px;
      background: rgba(255,255,255,.06); border: 1px solid rgba(255,255,255,.1);
      color: #888; font-size: .78rem; cursor: pointer;
      display: flex; align-items: center; justify-content: center;
      transition: all .18s;
    }
    .sp-ava-modal-close:hover { color: #fff; border-color: rgba(255,255,255,.2); }

    /* Tabs inside modal */
    .sp-avatar-tabs {
      display: flex; gap: 6px; margin-bottom: 14px;
    }
    .sp-avatar-tab {
      flex: 1; padding: 7px 10px;
      background: rgba(255,255,255,.04); border: 1px solid rgba(255,255,255,.08);
      border-radius: 8px; cursor: pointer;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; font-size: .74rem; font-weight: 700;
      color: var(--light); transition: all .2s;
      display: flex; align-items: center; justify-content: center; gap: 6px;
    }
    .sp-avatar-tab.active { background: var(--cyan-dim); border-color: var(--cyan); color: var(--cyan); }
    .sp-avatar-tab.locked { opacity: .3; cursor: not-allowed; }

    /* Grid inside modal */
    .sp-avatar-grid {
      display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px;
    }
    .sp-ava-opt {
      width: 100%; aspect-ratio: 1; border-radius: 10px;
      border: 2px solid rgba(255,255,255,.08);
      overflow: hidden; cursor: pointer; transition: all .2s;
      background: #1a1a1a; position: relative;
    }
    .sp-ava-opt img { width: 100%; height: 100%; object-fit: cover; display: block; }
    .sp-ava-opt:hover { border-color: rgba(197,139,42,.4); transform: scale(1.05); }
    .sp-ava-opt.selected { border-color: var(--cyan); box-shadow: 0 0 0 3px rgba(197,139,42,.2); }
    .sp-ava-opt.selected::after {
      content: '';
      position: absolute; bottom: 4px; right: 4px;
      width: 16px; height: 16px; border-radius: 50%;
      background: var(--cyan) url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23000' stroke-width='3' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='m5 12 4 4L19 6'/%3E%3C/svg%3E") center/11px 11px no-repeat; color: #000;
      display: flex; align-items: center; justify-content: center;
    }

    /* Profile fields */
    .sp-row-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 14px; }
    .sp-profile-field { margin-bottom: 14px; }
    .sp-profile-input {
      width: 100%; padding: 12px 14px;
      background: var(--input);
      border: 1px solid var(--border2);
      border-radius: 10px;
      font-size: .86rem; color: #fff;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; outline: none;
      transition: border-color .2s;
    }
    .sp-profile-input:focus {
      border-color: var(--border2);
      outline: none;
      box-shadow: none;
    }
    .sp-profile-input::placeholder { color: var(--gray); }

    /* Age roller */
    .sp-age-roller {
      display: block;
      background: var(--input); border: 1px solid var(--border2);
      border-radius: 10px; overflow: hidden; height: 156px;
      user-select: none;
      position: relative;
    }
    .sp-age-roller::before,
    .sp-age-roller::after {
      content: "";
      position: absolute; left: 0; right: 0; z-index: 2; height: 52px;
      pointer-events: none;
    }
    .sp-age-roller::before { top: 0; background: linear-gradient(180deg, var(--input), transparent); }
    .sp-age-roller::after { bottom: 0; background: linear-gradient(0deg, var(--input), transparent); }
    .sp-roller-track {
      height: 100%;
      overflow-y: auto;
      scroll-snap-type: y mandatory;
      scrollbar-width: none;
      padding: 52px 0;
    }
    .sp-roller-track::-webkit-scrollbar { display: none; }
    .sp-roller-inner {
      display: flex; flex-direction: column; align-items: stretch;
    }
    .sp-roller-item {
      height: 52px; width: 100%; display: flex; align-items: center; justify-content: center;
      flex: 0 0 52px;
      scroll-snap-align: center;
      font-size: 1rem; font-weight: 700; color: rgba(197,139,42,.32);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      transition: color .18s, font-size .18s;
    }
    .sp-roller-item.active { color: var(--cyan); font-size: 1.45rem; font-weight: 900; }

    /* Gender slider */
    .sp-gender-slider {
      background: var(--input); border: 1px solid var(--border2);
      border-radius: 10px; padding: 6px;
      display: flex; gap: 4px; margin-bottom: 22px; position: relative;
      overflow: hidden;
    }
    .sp-gender-slide-btn {
      flex: 1; padding: 9px 6px; border: none; border-radius: 7px;
      background: transparent;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif; font-size: .78rem; font-weight: 700;
      color: var(--light); cursor: pointer; transition: all .22s;
      display: flex; align-items: center; justify-content: center; gap: 5px;
      position: relative; z-index: 1;
    }
    .sp-gender-slide-btn.selected { color: var(--cyan); }
    .sp-gender-slider.ready .sp-gender-slide-btn.selected { color: #000; }
    .sp-gender-slider-thumb {
      position: absolute; top: 6px; bottom: 6px; left: 6px;
      border-radius: 7px; background: var(--cyan);
      transition: left .22s cubic-bezier(.4,0,.2,1), width .22s;
      z-index: 0;
    }

    /* Profile primary btn */
    .sp-complete-btn {
      width: 100%; padding: 14px;
      background: var(--cyan); color: #000;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .93rem; font-weight: 800;
      border: none; border-radius: 12px;
      cursor: pointer; transition: all .2s;
      margin-bottom: 12px;
    }
    .sp-complete-btn:hover {
      background: #A96F18;
      box-shadow: 0 6px 22px rgba(197,139,42,.38);
    }
    .sp-terms-note {
      text-align: center; font-size: .72rem; color: var(--gray); line-height: 1.55;
    }
    .sp-terms-note a { color: var(--cyan); }

    /* ===== FOOTER ===== */
    .sp-footer {
      background: #000;
      border-top: 1px solid var(--border);
      padding: 52px 0 0;
      flex-shrink: 0;
    }
    .sp-footer-inner {
      max-width: 1160px; margin: 0 auto; padding: 0 28px;
    }
    .sp-footer-top {
      display: grid;
      grid-template-columns: 1.5fr 1fr 1fr 1fr;
      gap: 40px; padding-bottom: 48px;
    }
    .sp-footer-brand { font-size: 1.05rem; font-weight: 800; margin-bottom: 10px; }
    .sp-footer-brand span { color: var(--cyan); }
    .sp-footer-brand-desc {
      font-size: .78rem; color: var(--gray);
      line-height: 1.72; max-width: 200px; margin-bottom: 16px;
    }
    .sp-footer-icons { display: flex; gap: 10px; }
    .sp-footer-icon {
      width: 32px; height: 32px; border-radius: 8px;
      background: var(--card); border: 1px solid var(--border2);
      display: flex; align-items: center; justify-content: center;
      font-size: .78rem; color: var(--light);
      transition: all .2s; cursor: pointer;
    }
    .sp-footer-icon:hover { border-color: rgba(197,139,42,.3); color: var(--cyan); }
    .sp-footer-col-title {
      font-size: .62rem; font-weight: 800; letter-spacing: .12em;
      text-transform: uppercase; color: #fff; margin-bottom: 14px;
    }
    .sp-footer-col-links { display: flex; flex-direction: column; gap: 10px; }
    .sp-footer-col-links a {
      font-size: .79rem; color: var(--gray); transition: color .2s;
    }
    .sp-footer-col-links a:hover { color: var(--cyan); }
    .sp-footer-bottom {
      border-top: 1px solid var(--border);
      padding: 16px 0;
      display: flex; align-items: center; justify-content: space-between;
      flex-wrap: wrap; gap: 10px;
    }
    .sp-footer-bottom p { font-size: .74rem; color: var(--gray); }
    .sp-footer-bottom-links { display: flex; gap: 18px; }
    .sp-footer-bottom-links a {
      font-size: .74rem; color: var(--gray); transition: color .2s;
    }
    .sp-footer-bottom-links a:hover { color: var(--light); }

    /* Hide photo + show full width on profile step */
    body.profile-mode .sp-photo { display: none; }
    body.profile-mode .sp-form-panel { display: none; }
    body.profile-mode .sp-main { display: block; }
    body.profile-mode .sp-profile-wrap { display: flex; }

    @media (max-width: 768px) {
      .sp-photo { display: none; }
      .sp-form-panel { padding: 40px 28px; }
      .sp-footer-top { grid-template-columns: 1fr 1fr; }
      .sp-nav-links { display: none; }
      .sp-avatar-grid { grid-template-columns: repeat(2, 1fr); }
    }
    @media (max-width: 480px) {
      .sp-footer-top { grid-template-columns: 1fr; }
      .sp-avatar-grid { grid-template-columns: repeat(3, 1fr); }
      .sp-form-panel { padding: 24px 16px; }
    }
  `,
  scripts: [
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` },
    { src: `js/animations.js` }
  ],
};

export default page;
