/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Terms &amp; Conditions - Skillomate AI`,
  lang: `en`,
  stylesheets: [],
  styles: ``,
  scripts: [],
};

export default page;
