/* This file is generated by scripts/generate-legacy-pages.mjs. */
export const page = {
  title: `Course Player | Skillomate`,
  lang: `en`,
  stylesheets: [`css/animations.css`, `/main.css`, `/motion.css`],
  styles: `
    :root { --font-body: "Manrope", ui-sans-serif, system-ui, sans-serif; --font-display: "Fraunces", Georgia, serif; }
    body, button, input, textarea, select { font-family: var(--font-body); }
    h1, h2, .hero-title, .section-title, .auth-brand, .library-hero h1, .welcome-left h1, .market-right h2, .trial-left h2, .team-header-row h2, .cta-section h2, .section-head h2, .lp-title, .sp-title, .payment-choice-title { font-family: var(--font-display); font-weight: 600; letter-spacing: 0; }

    :root {
      --library-bg: #f7fbf8;
      --library-ink: #102719;
      --library-soft: #52616b;
      --library-line: #dbe7df;
      --library-green: #359c57;
      --library-green-dark: #2f7f48;
      --library-blue: #2563eb;
      --library-amber: #b7791f;
      --library-card: #ffffff;
      --library-shadow: 0 18px 48px rgba(16, 39, 25, .1);
    }

    * { box-sizing: border-box; }
    body {
      margin: 0;
      min-height: 100vh;
      background:
        linear-gradient(180deg, #ffffff 0%, var(--library-bg) 42%, #ffffff 100%);
      color: var(--library-ink);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
    }
    a { color: inherit; text-decoration: none; }
    button, input { font: inherit; }
    button { cursor: pointer; }

    .library-shell {
      width: min(1180px, calc(100% - 40px));
      margin: 0 auto;
    }
    .library-hero {
      padding: 118px 0 30px;
      display: grid;
      grid-template-columns: minmax(0, 1fr) 320px;
      gap: 32px;
      align-items: end;
    }
    .library-kicker {
      display: inline-flex;
      align-items: center;
      gap: 9px;
      margin: 0 0 14px;
      color: var(--library-green-dark);
      font-size: 12px;
      font-weight: 900;
      text-transform: uppercase;
    }
    .library-kicker::before {
      content: "";
      width: 22px;
      height: 2px;
      background: var(--library-green);
      border-radius: 999px;
    }
    .library-hero h1 {
      max-width: 760px;
      margin: 0;
      font-family: "Fraunces", Georgia, serif;
      font-size: clamp(42px, 6vw, 76px);
      line-height: .98;
      letter-spacing: 0;
    }
    .library-hero p {
      max-width: 650px;
      margin: 18px 0 0;
      color: var(--library-soft);
      font-size: 17px;
      line-height: 1.75;
    }
    .library-search {
      margin-top: 24px;
      display: flex;
      gap: 10px;
      max-width: 620px;
    }
    .library-search input {
      width: 100%;
      min-height: 50px;
      border: 1px solid var(--library-line);
      border-radius: 8px;
      padding: 0 16px;
      color: var(--library-ink);
      background: #fff;
      outline: none;
      box-shadow: 0 8px 22px rgba(16, 39, 25, .04);
    }
    .library-search input:focus {
      border-color: rgba(53, 156, 87, .58);
      box-shadow: 0 0 0 4px rgba(53, 156, 87, .1);
    }
    .library-search button,
    .back-library,
    .lesson-action {
      min-height: 50px;
      border: 0;
      border-radius: 8px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      padding: 0 18px;
      color: #fff;
      background: var(--library-green);
      font-weight: 900;
      white-space: nowrap;
      transition: transform .2s ease, background .2s ease;
    }
    .library-search button:hover,
    .back-library:hover,
    .lesson-action:hover {
      transform: translateY(-1px);
      background: var(--library-green-dark);
    }
    .library-summary {
      min-height: 220px;
      padding: 20px;
      border: 1px solid rgba(219, 231, 223, .9);
      border-radius: 8px;
      background:
        linear-gradient(135deg, rgba(255,255,255,.88), rgba(238,248,241,.92)),
        url("data:image/svg+xml,%3Csvg%20xmlns=%27http://www.w3.org/2000/svg%27%20width=%27900%27%20height=%27600%27%20viewBox=%270%200%20900%20600%27%3E%3Crect%20width=%27900%27%20height=%27600%27%20fill=%27%23000000%27/%3E%3Crect%20x=%271%27%20y=%271%27%20width=%27898%27%20height=%27598%27%20rx=%2732%27%20fill=%27%230d0d0d%27%20stroke=%27%23C58B2A%27%20stroke-opacity=%27.35%27/%3E%3Ctext%20x=%27450%27%20y=%27312%27%20text-anchor=%27middle%27%20fill=%27%23C58B2A%27%20font-family=%27Arial%27%20font-size=%2748%27%20font-weight=%27800%27%3ESkillomate%3C/text%3E%3C/svg%3E") center/cover;
      box-shadow: var(--library-shadow);
      display: flex;
      flex-direction: column;
      justify-content: space-between;
    }
    .summary-pill {
      width: max-content;
      padding: 7px 10px;
      border-radius: 8px;
      background: #fff;
      color: var(--library-green-dark);
      font-size: 11px;
      font-weight: 900;
      text-transform: uppercase;
    }
    .summary-number {
      display: block;
      font-family: "Fraunces", Georgia, serif;
      font-size: 42px;
      line-height: 1;
      font-weight: 900;
    }
    .summary-label {
      color: var(--library-soft);
      font-size: 13px;
      font-weight: 800;
    }

    .library-tabs {
      display: flex;
      gap: 8px;
      margin: 6px 0 24px;
      overflow-x: auto;
      padding-bottom: 2px;
    }
    .library-tab {
      min-height: 38px;
      border: 1px solid var(--library-line);
      border-radius: 8px;
      padding: 0 14px;
      background: #fff;
      color: var(--library-soft);
      font-size: 13px;
      font-weight: 900;
      white-space: nowrap;
    }
    .library-tab.is-active {
      background: var(--library-ink);
      border-color: var(--library-ink);
      color: #fff;
    }

    .section-head {
      display: flex;
      justify-content: space-between;
      align-items: end;
      gap: 18px;
      margin: 28px 0 16px;
    }
    .section-head h2 {
      margin: 0;
      font-family: "Fraunces", Georgia, serif;
      font-size: 30px;
      letter-spacing: 0;
    }
    .section-head p {
      margin: 6px 0 0;
      color: var(--library-soft);
      font-size: 14px;
    }
    .status-line {
      color: var(--library-soft);
      font-size: 13px;
      font-weight: 800;
    }

    .continue-grid,
    .course-grid {
      display: grid;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 16px;
    }
    .course-tile {
      min-width: 0;
      border: 1px solid var(--library-line);
      border-radius: 8px;
      background: var(--library-card);
      overflow: hidden;
      box-shadow: 0 10px 26px rgba(16, 39, 25, .06);
      transition: transform .22s ease, box-shadow .22s ease, border-color .22s ease;
    }
    .course-tile:hover {
      transform: translateY(-3px);
      border-color: rgba(53, 156, 87, .42);
      box-shadow: var(--library-shadow);
    }
    .tile-media {
      position: relative;
      aspect-ratio: 16 / 9;
      overflow: hidden;
      background: #332820;
    }
    .tile-media img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      display: block;
      transition: transform .3s ease;
    }
    .course-tile:hover .tile-media img { transform: scale(1.04); }
    .tile-badge {
      position: absolute;
      top: 10px;
      left: 10px;
      max-width: calc(100% - 20px);
      min-height: 26px;
      display: inline-flex;
      align-items: center;
      padding: 4px 8px;
      border-radius: 8px;
      background: rgba(255,255,255,.94);
      color: var(--library-ink);
      font-size: 11px;
      font-weight: 900;
      text-transform: uppercase;
    }
    .tile-body {
      padding: 16px;
    }
    .tile-body h3 {
      min-height: 54px;
      margin: 0;
      font-family: "Fraunces", Georgia, serif;
      font-size: 23px;
      line-height: 1.15;
      letter-spacing: 0;
    }
    .tile-body p {
      margin: 9px 0 14px;
      min-height: 45px;
      color: var(--library-soft);
      font-size: 13px;
      line-height: 1.55;
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
    .tile-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      color: var(--library-soft);
      font-size: 12px;
      font-weight: 800;
    }
    .tile-progress {
      height: 7px;
      margin-top: 14px;
      border-radius: 999px;
      background: #e8efe9;
      overflow: hidden;
    }
    .tile-progress span {
      display: block;
      width: var(--progress, 0%);
      height: 100%;
      border-radius: inherit;
      background: linear-gradient(90deg, var(--library-green), var(--library-blue));
    }

    .watch-page {
      width: min(1320px, calc(100% - 32px));
      margin: 0 auto;
      padding: 98px 0 46px;
    }
    .watch-top {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 14px;
      margin-bottom: 14px;
    }
    .back-library {
      min-height: 42px;
      padding: 0 14px;
      font-size: 13px;
    }
    .watch-layout {
      display: grid;
      grid-template-columns: minmax(0, 1fr) 380px;
      gap: 20px;
      align-items: start;
    }
    .player-wrap {
      min-width: 0;
    }
    .player-frame {
      width: 100%;
      aspect-ratio: 16 / 9;
      border-radius: 8px;
      overflow: hidden;
      background: #0b1117;
      box-shadow: 0 22px 62px rgba(11, 17, 23, .18);
    }
    .player-frame iframe,
    .player-frame video {
      width: 100%;
      height: 100%;
      border: 0;
      display: block;
      background: #0b1117;
    }
    .player-placeholder {
      width: 100%;
      height: 100%;
      display: grid;
      place-items: center;
      padding: 28px;
      color: rgba(255,255,255,.82);
      text-align: center;
    }
    .player-placeholder strong {
      display: block;
      color: #fff;
      font-family: "Fraunces", Georgia, serif;
      font-size: 30px;
      line-height: 1.1;
      margin-bottom: 8px;
    }
    .lesson-info {
      padding: 20px 2px 0;
    }
    .lesson-info h1 {
      margin: 0;
      font-family: "Fraunces", Georgia, serif;
      font-size: clamp(30px, 4vw, 46px);
      line-height: 1.04;
      letter-spacing: 0;
    }
    .lesson-info p {
      max-width: 840px;
      margin: 10px 0 0;
      color: var(--library-soft);
      font-size: 15px;
      line-height: 1.75;
    }
    .lesson-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 9px;
      margin-top: 14px;
    }
    .lesson-meta span {
      min-height: 30px;
      display: inline-flex;
      align-items: center;
      padding: 5px 9px;
      border: 1px solid var(--library-line);
      border-radius: 8px;
      color: var(--library-soft);
      background: #fff;
      font-size: 12px;
      font-weight: 900;
    }
    .lesson-sidebar {
      border: 1px solid var(--library-line);
      border-radius: 8px;
      background: #fff;
      overflow: hidden;
      box-shadow: 0 12px 32px rgba(16, 39, 25, .07);
      max-height: calc(100vh - 116px);
      display: flex;
      flex-direction: column;
    }
    .sidebar-head {
      padding: 16px;
      border-bottom: 1px solid var(--library-line);
    }
    .sidebar-head h2 {
      margin: 0;
      font-family: "Fraunces", Georgia, serif;
      font-size: 24px;
      letter-spacing: 0;
    }
    .sidebar-head p {
      margin: 5px 0 0;
      color: var(--library-soft);
      font-size: 12px;
      font-weight: 800;
    }
    .lesson-list {
      overflow: auto;
      padding: 8px;
    }
    .lesson-item {
      width: 100%;
      min-height: 86px;
      display: grid;
      grid-template-columns: 112px minmax(0, 1fr);
      gap: 11px;
      border: 1px solid transparent;
      border-radius: 8px;
      padding: 8px;
      background: transparent;
      text-align: left;
      color: inherit;
    }
    .lesson-item:hover,
    .lesson-item.is-active {
      background: #f4faf6;
      border-color: rgba(53, 156, 87, .18);
    }
    .lesson-thumb {
      width: 112px;
      aspect-ratio: 16 / 9;
      border-radius: 8px;
      overflow: hidden;
      background: #0b1117;
      position: relative;
    }
    .lesson-thumb img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      display: block;
    }
    .lesson-number {
      position: absolute;
      right: 6px;
      bottom: 6px;
      padding: 2px 6px;
      border-radius: 6px;
      background: rgba(0,0,0,.72);
      color: #fff;
      font-size: 10px;
      font-weight: 900;
    }
    .lesson-copy {
      min-width: 0;
      align-self: center;
    }
    .lesson-copy strong {
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
      font-size: 13px;
      line-height: 1.35;
    }
    .lesson-copy span {
      display: block;
      margin-top: 6px;
      color: var(--library-soft);
      font-size: 11px;
      font-weight: 800;
    }
    .empty-state {
      padding: 28px;
      border: 1px dashed var(--library-line);
      border-radius: 8px;
      background: #fff;
      color: var(--library-soft);
      font-weight: 800;
    }
    .continue-grid > .empty-state,
    .course-grid > .empty-state {
      grid-column: 1 / -1;
    }

    [hidden] { display: none !important; }

    @media (max-width: 960px) {
      .library-hero,
      .watch-layout {
        grid-template-columns: 1fr;
      }
      .library-summary { min-height: 170px; }
      .continue-grid,
      .course-grid {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
      .lesson-sidebar {
        max-height: none;
      }
    }

    @media (max-width: 640px) {
      .library-shell,
      .watch-page {
        width: min(100% - 28px, 1180px);
      }
      .library-hero {
        padding-top: 104px;
      }
      .library-search {
        flex-direction: column;
      }
      .continue-grid,
      .course-grid {
        grid-template-columns: 1fr;
      }
      .section-head,
      .watch-top {
        align-items: start;
        flex-direction: column;
      }
      .lesson-item {
        grid-template-columns: 96px minmax(0, 1fr);
      }
      .lesson-thumb { width: 96px; }
    }

    /* ===== Lesson page theme applied to the real library/player ===== */
    :root {
      --cyan: #C58B2A;
      --cyan-dim: rgba(197,139,42,0.1);
      --cyan-border: rgba(197,139,42,0.25);
      --panel: #141820;
      --panel2: #1a1f2e;
      --card: #0e1118;
      --border: rgba(255,255,255,0.08);
      --gray: #6b7280;
      --light: #9ca3af;
      --library-bg: #0a0c12;
      --library-ink: #ffffff;
      --library-soft: #9ca3af;
      --library-line: rgba(255,255,255,0.08);
      --library-green: var(--cyan);
      --library-green-dark: #A96F18;
      --library-blue: var(--cyan);
      --library-amber: var(--cyan);
      --library-card: #141820;
      --library-shadow: 0 24px 70px rgba(0,0,0,.34);
    }

    html, body { min-height: 100%; }
    body {
      background: #0a0c12;
      color: #fff;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      overflow-x: hidden;
    }

    .premium-site-nav {
      background: rgba(10,12,18,.74);
      backdrop-filter: blur(18px);
      border-bottom: 1px solid var(--border);
    }
    .premium-nav-panel {
      background: transparent;
      border-color: transparent;
      box-shadow: none;
    }

    .library-shell {
      width: min(1180px, calc(100% - 32px));
    }
    .library-hero {
      padding: 112px 0 24px;
      grid-template-columns: minmax(0, 1fr) 280px;
      align-items: stretch;
    }
    .library-kicker {
      color: var(--cyan);
      letter-spacing: .12em;
      font-size: .68rem;
    }
    .library-kicker::before {
      background: var(--cyan);
      box-shadow: 0 0 18px rgba(197,139,42,.45);
    }
    .library-hero h1 {
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: clamp(2rem, 5vw, 4.2rem);
      line-height: 1.02;
      max-width: 780px;
    }
    .library-hero p {
      color: var(--light);
      font-size: .96rem;
      max-width: 650px;
    }
    .library-search {
      max-width: 640px;
    }
    .library-search input {
      min-height: 48px;
      border-color: var(--border);
      background: var(--card);
      color: #fff;
      box-shadow: none;
    }
    .library-search input::placeholder {
      color: var(--gray);
    }
    .library-search input:focus {
      border-color: var(--cyan-border);
      box-shadow: 0 0 0 4px rgba(197,139,42,.09);
    }
    .library-search button,
    .back-library,
    .lesson-action {
      min-height: 42px;
      border-radius: 11px;
      background: var(--cyan);
      color: #000;
      font-size: .8rem;
      font-weight: 800;
      box-shadow: none;
    }
    .library-search button:hover,
    .back-library:hover,
    .lesson-action:hover {
      background: #A96F18;
      box-shadow: 0 4px 18px rgba(197,139,42,.38);
    }

    .library-summary,
    .course-tile,
    .empty-state {
      background: var(--panel);
      border: 1px solid var(--border);
      border-radius: 18px;
      box-shadow: none;
    }
    .library-summary {
      min-height: 210px;
      overflow: hidden;
      background:
        linear-gradient(180deg, rgba(20,24,32,.80), rgba(20,24,32,.96)),
        var(--panel);
    }
    .summary-pill,
    .tile-badge {
      border-radius: 999px;
      background: var(--cyan-dim);
      border: 1px solid var(--cyan-border);
      color: var(--cyan);
      letter-spacing: .08em;
    }
    .summary-number {
      color: #fff;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
    }
    .summary-label,
    .section-head p,
    .status-line,
    .tile-body p,
    .tile-meta,
    .empty-state {
      color: var(--light);
    }

    .library-tabs {
      gap: 8px;
      margin-top: 8px;
    }
    .library-tab {
      min-height: 36px;
      border-radius: 999px;
      border-color: var(--border);
      background: rgba(255,255,255,.04);
      color: var(--light);
      font-size: .75rem;
      letter-spacing: .03em;
    }
    .library-tab.is-active {
      background: var(--cyan-dim);
      border-color: var(--cyan-border);
      color: var(--cyan);
    }

    .section-head {
      margin: 28px 0 14px;
    }
    .section-head h2,
    .tile-body h3 {
      color: #fff;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
    }
    .continue-grid,
    .course-grid {
      gap: 14px;
    }
    .course-tile {
      overflow: hidden;
      transition: transform .22s ease, border-color .22s ease, background .22s ease;
    }
    .course-tile:hover {
      transform: translateY(-3px);
      border-color: var(--cyan-border);
      background: var(--panel2);
      box-shadow: none;
    }
    .tile-media {
      background: #050710;
    }
    .tile-body h3 {
      min-height: 46px;
      font-size: 1rem;
      font-weight: 700;
    }
    .tile-progress {
      height: 4px;
      background: rgba(255,255,255,.1);
    }
    .tile-progress span {
      background: var(--cyan);
      box-shadow: 0 0 12px rgba(197,139,42,.4);
    }

    .watch-page {
      width: auto;
      min-height: 100vh;
      padding: 16px;
      display: flex;
      flex-direction: column;
      gap: 0;
    }
    .watch-top {
      display: flex;
      align-items: center;
      gap: 12px;
      margin: 0;
      padding: 0 4px 14px;
    }
    .back-library {
      padding: 6px 12px;
      min-height: 34px;
      background: rgba(255,255,255,0.05);
      border: 1px solid var(--border);
      color: var(--light);
      box-shadow: none;
    }
    .back-library:hover {
      color: #fff;
      background: rgba(255,255,255,0.08);
      border-color: rgba(255,255,255,0.15);
      box-shadow: none;
    }
    #watchStatus {
      margin-left: auto;
      padding: 4px 12px;
      border-radius: 999px;
      background: var(--cyan-dim);
      border: 1px solid var(--cyan-border);
      color: var(--cyan);
      font-size: .7rem;
      font-weight: 800;
      text-transform: uppercase;
    }
    .watch-actions {
      display: flex;
      align-items: center;
      gap: 8px;
    }
    .watch-tool-btn,
    .notes-modal-close,
    .notes-open-link {
      min-height: 34px;
      padding: 0 12px;
      border-radius: 999px;
      border: 1px solid var(--border);
      background: rgba(255,255,255,.05);
      color: var(--light);
      font-size: .74rem;
      font-weight: 800;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 7px;
      text-decoration: none;
    }
    .watch-tool-btn:hover,
    .notes-modal-close:hover,
    .notes-open-link:hover {
      border-color: rgba(197,139,42,.34);
      color: var(--cyan);
      background: rgba(197,139,42,.08);
    }
    .back-bar-title {
      min-width: 0;
      color: var(--light);
      font-size: .85rem;
      font-weight: 600;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
    }
    .watch-layout {
      display: flex;
      gap: 14px;
      align-items: flex-start;
      min-height: 0;
    }
    .player-wrap {
      flex: 1;
      width: 100%;
      min-width: 0;
      display: flex;
      flex-direction: column;
    }
    .player-frame {
      flex: 0 0 auto;
      width: 100%;
      height: auto;
      aspect-ratio: 3 / 2;
      min-height: 0;
      border-radius: 22px;
      overflow: hidden;
      position: relative;
      background: #050710;
      box-shadow: none;
    }
    .player-frame iframe,
    .player-frame video {
      width: 100%;
      height: 100%;
      border: 0;
      display: block;
      background: #050710;
    }
    .custom-video-player {
      position: relative;
      width: 100%;
      height: 100%;
      background: #050710;
      overflow: hidden;
    }
    .custom-video-player video {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
    .custom-video-player iframe {
      width: 100%;
      height: 100%;
      border: 0;
      display: block;
      background: #050710;
    }
    .tap-zone {
      position: absolute;
      top: 0;
      bottom: 74px;
      width: 50%;
      border: 0;
      background: transparent;
      z-index: 2;
      display: grid;
      place-items: center;
      color: rgba(255,255,255,.9);
      font-weight: 900;
      pointer-events: auto;
      user-select: none;
      cursor: pointer;
      touch-action: manipulation;
    }
    .tap-zone-left { left: 0; }
    .tap-zone-right { right: 0; }
    .tap-hint {
      opacity: 0;
      transform: scale(.88);
      padding: 12px 14px;
      border-radius: 999px;
      background: rgba(0,0,0,.55);
      border: 1px solid rgba(255,255,255,.16);
      transition: opacity .18s ease, transform .18s ease;
    }
    .tap-zone.show .tap-hint {
      opacity: 1;
      transform: scale(1);
    }
    .custom-video-controls {
      position: absolute;
      left: 14px;
      right: 14px;
      bottom: 14px;
      z-index: 4;
      display: grid;
      grid-template-columns: auto minmax(0, 1fr) 38px 104px;
      gap: 8px;
      align-items: center;
      padding: 12px;
      border: 1px solid rgba(255,255,255,.12);
      border-radius: 16px;
      background: rgba(5,7,16,.78);
      backdrop-filter: blur(18px);
      box-shadow: 0 18px 40px rgba(0,0,0,.32);
    }
    .video-control-btn {
      width: 38px;
      height: 38px;
      border: 1px solid rgba(255,255,255,.12);
      border-radius: 999px;
      display: grid;
      place-items: center;
      background: rgba(255,255,255,.06);
      color: #fff;
      font-size: .9rem;
    }
    .video-control-btn:hover {
      border-color: rgba(197,139,42,.38);
      color: var(--cyan);
    }
    .video-volume {
      position: relative;
      width: 38px;
      height: 38px;
      flex-shrink: 0;
      z-index: 6;
    }
    .video-volume-toggle {
      width: 38px;
      height: 38px;
    }
    .video-volume-panel {
      position: absolute;
      left: 50%;
      bottom: calc(100% + 10px);
      width: 52px;
      height: 154px;
      padding: 10px 8px;
      border: 1px solid rgba(255,255,255,.14);
      border-radius: 16px;
      background: rgba(5,7,16,.94);
      box-shadow: 0 16px 36px rgba(0,0,0,.42);
      backdrop-filter: blur(16px);
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 8px;
      opacity: 0;
      visibility: hidden;
      pointer-events: none;
      transform: translate(-50%, 6px);
      transition: opacity .16s ease, transform .16s ease, visibility .16s ease;
    }
    .video-volume.is-open .video-volume-panel {
      opacity: 1;
      visibility: visible;
      pointer-events: auto;
      transform: translate(-50%, 0);
    }
    .video-volume-slider {
      width: 18px;
      height: 104px;
      writing-mode: vertical-lr;
      direction: rtl;
      appearance: slider-vertical;
      -webkit-appearance: slider-vertical;
      accent-color: var(--cyan);
      cursor: pointer;
    }
    .video-volume-value {
      width: auto;
      color: rgba(255,255,255,.72);
      font-size: .68rem;
      font-weight: 900;
      text-align: center;
      font-variant-numeric: tabular-nums;
    }
    .video-timeline-wrap {
      display: grid;
      gap: 7px;
      min-width: 0;
    }
    .video-time-row {
      display: flex;
      justify-content: space-between;
      color: rgba(255,255,255,.72);
      font-size: .72rem;
      font-weight: 800;
      font-variant-numeric: tabular-nums;
    }
    .video-seek {
      width: 100%;
      accent-color: var(--cyan);
      cursor: pointer;
    }
    .video-speed {
      min-height: 38px;
      display: inline-flex;
      align-items: center;
      border: 1px solid rgba(255,255,255,.12);
      border-radius: 999px;
      padding: 0;
      background: rgba(255,255,255,.06);
      flex-shrink: 0;
      width: 58px;
      justify-content: center;
    }
    .video-speed-btn {
      all: unset;
      width: 100%;
      height: 38px;
      display: grid;
      place-items: center;
      color: #fff;
      font-size: .78rem;
      font-weight: 900;
      cursor: pointer;
      text-align: center;
      font-variant-numeric: tabular-nums;
    }
    .video-speed:hover {
      border-color: rgba(197,139,42,.38);
    }
    .video-speed:hover .video-speed-btn {
      color: var(--cyan);
    }
    .video-end-controls {
      width: 104px;
      display: inline-flex;
      align-items: center;
      justify-content: flex-end;
      gap: 8px;
    }
    .video-fullscreen-control {
      flex: 0 0 38px;
    }
    .video-screen-btn {
      position: absolute;
      top: 14px;
      z-index: 5;
      min-height: 38px;
      padding: 0 13px;
      border: 1px solid rgba(255,255,255,.14);
      border-radius: 999px;
      background: rgba(5,7,16,.72);
      color: #fff;
      backdrop-filter: blur(14px);
      display: inline-flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      font-size: .75rem;
      font-weight: 900;
      box-shadow: 0 12px 30px rgba(0,0,0,.28);
    }
    .video-screen-btn:hover {
      border-color: rgba(197,139,42,.38);
      background: rgba(197,139,42,.14);
      color: var(--cyan);
    }
    .video-ai-screen-btn {
      right: 14px;
    }
    .player-placeholder {
      background: #050710;
    }
    .player-placeholder strong {
      color: #fff;
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: clamp(1.2rem, 2.5vw, 1.6rem);
    }
    .lesson-info {
      padding: 16px 4px 0;
    }
    .lesson-info h1 {
      color: #fff;
      font-family: "Fraunces", Georgia, serif;
      font-size: clamp(1.25rem, 2.6vw, 1.8rem);
      font-weight: 800;
      line-height: 1.2;
    }
    .lesson-info p {
      color: rgba(255,255,255,.58);
      font-size: .92rem;
      line-height: 1.65;
      letter-spacing: 0;
    }
    .lesson-meta span {
      min-height: 28px;
      border-color: var(--border);
      border-radius: 999px;
      background: rgba(255,255,255,.05);
      color: var(--light);
      font-size: .68rem;
      letter-spacing: .04em;
      text-transform: uppercase;
    }

    .lesson-sidebar {
      flex: 0 0 292px;
      max-height: none;
      border: 1px solid var(--border);
      border-radius: 18px;
      background: var(--panel);
      box-shadow: none;
      overflow: hidden;
      display: flex;
      flex-direction: column;
    }
    .sidebar-head {
      padding: 20px 16px 14px;
      border-bottom: 1px solid var(--border);
    }
    .sidebar-head h2 {
      margin: 0;
      color: var(--cyan);
      font-family: "Manrope", ui-sans-serif, system-ui, sans-serif;
      font-size: .68rem;
      font-weight: 800;
      letter-spacing: .12em;
      text-transform: uppercase;
    }
    .sidebar-head p {
      color: var(--gray);
      font-size: .72rem;
      font-weight: 700;
    }
    .sidebar-top-row {
      display: flex;
      align-items: flex-start;
      justify-content: space-between;
      gap: 12px;
    }
    .auto-next-toggle {
      flex: 0 0 auto;
      display: inline-flex;
      align-items: center;
      gap: 9px;
      min-height: 34px;
      padding: 5px 6px 5px 10px;
      border: 1px solid rgba(197,139,42,.16);
      border-radius: 999px;
      background: rgba(197,139,42,.06);
      color: rgba(255,255,255,.74);
      font-size: .66rem;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: .04em;
      user-select: none;
      cursor: pointer;
      transition: border-color .2s, background .2s, color .2s;
    }
    .auto-next-toggle input {
      position: absolute;
      opacity: 0;
      pointer-events: none;
    }
    .auto-next-switch {
      width: 42px;
      height: 22px;
      padding: 3px;
      border-radius: 999px;
      background: rgba(255,255,255,.12);
      border: 1px solid rgba(255,255,255,.1);
      display: inline-flex;
      align-items: center;
      transition: background .2s, border-color .2s;
    }
    .auto-next-switch::before {
      content: "";
      width: 14px;
      height: 14px;
      border-radius: 50%;
      background: rgba(255,255,255,.78);
      box-shadow: 0 2px 8px rgba(0,0,0,.22);
      transition: transform .2s, background .2s;
    }
    .auto-next-toggle:has(input:checked) {
      border-color: rgba(197,139,42,.38);
      background: rgba(197,139,42,.12);
      color: #fff;
    }
    .auto-next-toggle:has(input:checked) .auto-next-switch {
      background: var(--cyan);
      border-color: var(--cyan);
    }
    .auto-next-toggle:has(input:checked) .auto-next-switch::before {
      transform: translateX(18px);
      background: #001015;
    }
    .lesson-list {
      padding: 10px;
      overflow: auto;
    }
    .lesson-list::-webkit-scrollbar { width: 3px; }
    .lesson-list::-webkit-scrollbar-track { background: transparent; }
    .lesson-list::-webkit-scrollbar-thumb { background: rgba(255,255,255,.12); border-radius: 2px; }
    .lesson-item {
      min-height: 64px;
      grid-template-columns: 44px minmax(0, 1fr);
      gap: 10px;
      padding: 10px;
      border-radius: 11px;
      color: #fff;
      background: transparent;
      position: relative;
      transition: all .18s;
    }
    .lesson-item:hover,
    .lesson-item.is-active {
      background: rgba(197,139,42,0.07);
      border-color: rgba(197,139,42,0.15);
    }
    .lesson-item.is-active::before {
      content: "";
      position: absolute;
      left: 0;
      top: 8px;
      bottom: 8px;
      width: 3px;
      border-radius: 2px;
      background: var(--cyan);
    }
    .lesson-thumb {
      width: 44px;
      height: 34px;
      border-radius: 8px;
      background: #1a1e28;
    }
    .lesson-number {
      inset: 0;
      width: 100%;
      height: 100%;
      display: grid;
      place-items: center;
      padding: 0;
      border-radius: inherit;
      background: rgba(10,12,18,.52);
      color: #fff;
      font-size: .7rem;
      font-weight: 800;
    }
    .lesson-copy strong {
      color: #fff;
      font-size: .8rem;
      font-weight: 600;
      line-height: 1.35;
      -webkit-line-clamp: 1;
    }
    .lesson-copy span {
      color: var(--gray);
      font-size: .68rem;
      font-weight: 700;
    }
    .course-notes-modal {
      position: fixed;
      inset: 0;
      z-index: 9992;
      display: grid;
      place-items: center;
      padding: 18px;
      background: rgba(0,0,0,.72);
      backdrop-filter: blur(10px);
    }
    .course-notes-card {
      width: min(720px, 100%);
      max-height: min(760px, 90vh);
      overflow: auto;
      border: 1px solid var(--border);
      border-radius: 18px;
      background: var(--panel);
      color: var(--light);
      box-shadow: 0 28px 90px rgba(0,0,0,.42);
    }
    .notes-modal-head {
      display: flex;
      align-items: center;
      justify-content: space-between;
      gap: 16px;
      padding: 18px 20px;
      border-bottom: 1px solid var(--border);
    }
    .notes-modal-head h2 {
      margin: 0;
      color: #fff;
      font-size: 1rem;
      font-weight: 900;
    }
    .notes-modal-body {
      padding: 20px;
      display: grid;
      gap: 16px;
      color: rgba(255,255,255,.74);
      line-height: 1.65;
    }
    .notes-empty {
      padding: 18px;
      border: 1px dashed rgba(255,255,255,.16);
      border-radius: 14px;
      color: var(--gray);
      font-weight: 700;
    }

    [hidden] { display: none !important; }

    @media (max-width: 960px) {
      .library-hero {
        grid-template-columns: 1fr;
      }
      .watch-layout {
        flex-direction: column;
      }
      .lesson-sidebar {
        flex: 0 0 auto;
      }
      .player-frame {
        min-height: 0;
      }
    }

    @media (max-width: 640px) {
      .library-shell {
        width: min(100% - 24px, 1180px);
      }
      .watch-page {
        padding: 10px;
      }
      .watch-top {
        flex-wrap: wrap;
      }
      #watchStatus {
        margin-left: 0;
      }
      .watch-actions {
        width: 100%;
      }
      .watch-tool-btn {
        flex: 1;
      }
      .library-hero {
        padding-top: 92px;
      }
      .player-frame {
        min-height: 0;
        aspect-ratio: 9 / 16;
        border-radius: 18px;
        touch-action: manipulation;
      }
      .lesson-info h1 {
        font-size: clamp(1.35rem, 6vw, 1.8rem);
        line-height: 1.14;
      }
      .tap-zone {
        bottom: 116px;
      }
      .custom-video-controls {
        left: 8px;
        right: 8px;
        bottom: 8px;
        grid-template-columns: auto minmax(0, 1fr) 38px 104px;
        gap: 8px;
        padding: 10px;
      }
      .video-screen-btn span {
        display: none;
      }
      .lesson-item {
        grid-template-columns: 44px minmax(0, 1fr);
      }
      .lesson-thumb {
        width: 44px;
      }
    }
    @media (max-width: 520px) {
      .custom-video-controls {
        grid-template-columns: 38px minmax(0, 1fr) 38px 104px;
        grid-template-rows: auto;
      }
      .video-volume {
        grid-column: 3;
        grid-row: 1;
      }
      .video-play-control {
        grid-column: 1;
        grid-row: 1;
      }
      .video-timeline-wrap {
        grid-column: 2;
        grid-row: 1;
      }
      .video-end-controls {
        grid-column: 4;
        grid-row: 1;
      }
      .tap-zone {
        bottom: 74px;
      }
    }
  `,
  scripts: [
    { src: `/motion.js` },
    { src: `js/edunex-api.js` },
    { src: `assets/bot-avatars/manifest.js` },
    { src: `js/nex-ai-widget.js` }
  ],
};

export default page;
