from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


OUTPUT = "output/pdf/skillomate-testing-apk-comparison-2026-09-12.pdf"


def para(text, style):
    return Paragraph(text, style)


styles = getSampleStyleSheet()
styles.add(ParagraphStyle(
    name="TitleCustom",
    parent=styles["Title"],
    fontName="Helvetica-Bold",
    fontSize=18,
    leading=22,
    textColor=colors.HexColor("#111111"),
    spaceAfter=10,
))
styles.add(ParagraphStyle(
    name="Section",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=12,
    leading=14,
    textColor=colors.HexColor("#1F2933"),
    spaceBefore=8,
    spaceAfter=5,
))
styles.add(ParagraphStyle(
    name="BodyCustom",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=8.5,
    leading=11.2,
    textColor=colors.HexColor("#222222"),
))
styles.add(ParagraphStyle(
    name="Small",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=7.4,
    leading=9.5,
    textColor=colors.HexColor("#444444"),
))
styles.add(ParagraphStyle(
    name="TableCell",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=7.0,
    leading=9.0,
    textColor=colors.HexColor("#111111"),
))
styles.add(ParagraphStyle(
    name="TableHeader",
    parent=styles["BodyText"],
    fontName="Helvetica-Bold",
    fontSize=7.2,
    leading=9.0,
    textColor=colors.white,
))

doc = SimpleDocTemplate(
    OUTPUT,
    pagesize=A4,
    rightMargin=0.45 * inch,
    leftMargin=0.45 * inch,
    topMargin=0.4 * inch,
    bottomMargin=0.4 * inch,
)

story = []
story.append(para("Skillomate Testing APK Build Comparison", styles["TitleCustom"]))
story.append(para("Date: 2026-09-12", styles["BodyCustom"]))
story.append(para(
    "Scope: Off-record Android testing APK generated from the current Skillomate source tree. "
    "The artifact uses a neutral filename and keeps the existing app store metadata unchanged.",
    styles["BodyCustom"],
))
story.append(Spacer(1, 6))

story.append(para("Artifact Summary", styles["Section"]))
rows = [
    ["Area", "Previous APK", "New Testing APK"],
    [
        "Artifact",
        "Previous debug-signed Android APK from releases/android",
        "appcopyai/releases/android/skillomate-testing.apk",
    ],
    ["Created", "2026-09-12 12:32:56", "2026-09-12 14:45:58"],
    ["Size", "34,869,401 bytes", "34,869,401 bytes"],
    [
        "SHA-256",
        "3d73aacb4999620d888ee42fcfa75ed940c92cc8a95b2135b55bde333166b820",
        "cf2c7f633a16314edd54f805e6df767eb11c122759cd22c59b3d2fd99b6e2b81",
    ],
]
table_rows = [
    [para(cell, styles["TableHeader"] if row_index == 0 else styles["TableCell"]) for cell in row]
    for row_index, row in enumerate(rows)
]
table = Table(table_rows, colWidths=[1.15 * inch, 2.65 * inch, 2.65 * inch])
table.setStyle(TableStyle([
    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#111111")),
    ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#CBD2D9")),
    ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F7F9FB")]),
    ("LEFTPADDING", (0, 0), (-1, -1), 5),
    ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ("TOPPADDING", (0, 0), (-1, -1), 4),
    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
]))
story.append(table)

story.append(para("Code And Configuration Changes", styles["Section"]))
for item in [
    "No source code, Expo config, Gradle config, or app store metadata was changed for this testing artifact.",
    "The APK was rebuilt locally from the current Android release target.",
    "The final artifact was renamed to a neutral testing filename so the filename does not expose store metadata details.",
]:
    story.append(para("- " + item, styles["BodyCustom"]))

story.append(para("Build And Signing Changes", styles["Section"]))
for item in [
    "Gradle release build completed successfully with Android SDK path supplied at build time.",
    "The unsigned arm64 release APK was zip-aligned before signing.",
    "The testing APK was signed with the existing Android debug keystore for device installation.",
    "A signing sidecar file was generated by apksigner; the APK itself is the installable artifact.",
]:
    story.append(para("- " + item, styles["BodyCustom"]))

story.append(para("Verification Performed", styles["Section"]))
for item in [
    "Gradle task :app:assembleRelease completed successfully.",
    "Metro generated the Android JavaScript bundle during the release build.",
    "apksigner verification passed for the new testing APK.",
    "The new testing APK verifies with APK Signature Scheme v2 and v3.",
    "Package badging was inspected to confirm the Skillomate application id, app label, SDK range, and arm64-v8a native target.",
]:
    story.append(para("- " + item, styles["BodyCustom"]))

story.append(para("Notes", styles["Section"]))
for item in [
    "This APK is intended for local device testing only.",
    "It is not Play Store signed and should not be submitted to Google Play.",
    "Because app store metadata was intentionally left unchanged, installing over an existing build with identical metadata may require uninstalling the old test build first on some devices.",
]:
    story.append(para("- " + item, styles["BodyCustom"]))

story.append(Spacer(1, 6))
story.append(para("Prepared by Codex for the off-record Skillomate Android testing APK build.", styles["Small"]))

doc.build(story)
