const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto'),mongoose=require('mongoose');
process.env.JWT_SECRET='isolated-playback-test-secret';process.env.CLOUDFRONT_ACCESS_MODE='private';
const {privateKey,publicKey}=crypto.generateKeyPairSync('rsa',{modulusLength:2048});
process.env.CLOUDFRONT_PRIVATE_KEY=privateKey.export({type:'pkcs8',format:'pem'});process.env.CLOUDFRONT_PUBLIC_KEY_ID='test-key';
const source=require('../services/videoSources'),cf=require('../services/cloudFrontPlayback'),Course=require('../models/Course'),rules=require('../services/completionRules');
const raw='https://d2vntxz4x493rp.cloudfront.net/Course%20One/Lesson.M3U8%20?label=Case%20&v=A%2fb',bunny='https://iframe.mediadelivery.net/embed/675520/abc-123';
function sanitize(videos,existing=[]){const text=fs.readFileSync(require.resolve('../server'),'utf8');const fn=text.slice(text.indexOf('function sanitizeCourseVideos('),text.indexOf('\nfunction applyCourseThumbnailToVideos('));const context={mongoose,require:()=>source,sanitizeOptionalUrl:x=>x||null};vm.createContext(context);vm.runInContext(fn,context);return context.sanitizeCourseVideos(videos,existing);}
test('raw URL preservation and backend validation',()=>{assert.equal(source.validateCloudFront(raw),raw);for(const bad of [raw.replace('https:','http:'),raw.replace('d2vntxz4x493rp','evil'),raw+'&Signature=x',raw+'&Hash-Algorithm=SHA256',raw.replace('%20',' '),raw.replace('.M3U8','.mp4')])assert.throws(()=>source.validateCloudFront(bad));assert.throws(()=>source.validateSource({provider:'unknown',videoUrl:raw}));});
test('mixed course create, serialized reopen, edit, reorder and publish retain references and IDs',async()=>{const videos=sanitize([{title:'AWS',provider:'aws_cloudfront',videoUrl:raw,duration:80},{title:'Bunny',videoUrl:bunny,duration:100}]);const course=new Course({title:'Fixture',slug:'fixture',description:'Fixture course',category:new mongoose.Types.ObjectId(),status:'draft',videos});await course.validate();const reopened=Course.hydrate(JSON.parse(JSON.stringify(course)));assert.equal(reopened.videos[0].videoUrl,raw);assert.equal(reopened.videos[1].provider,'bunny_stream');const ids=reopened.videos.map(v=>String(v._id));reopened.videos=sanitize([...reopened.videos].reverse().map(v=>v.toObject()),reopened.videos);reopened.status='published';await reopened.validate();assert.deepEqual(reopened.videos.map(v=>String(v._id)),ids.reverse());assert.deepEqual(reopened.videos.map(v=>v.order),[1,2]);assert.equal(reopened.videos[1].videoUrl,raw);assert.throws(()=>sanitize([{...videos[0],_id:new mongoose.Types.ObjectId()}],videos),/does not belong/);assert.throws(()=>sanitize([videos[0],videos[0]],videos),/Duplicate/);});
test('legacy Bunny provider and embed inferred',()=>{const video=source.validateSource({videoUrl:bunny});assert.equal(video.provider,'bunny_stream');assert.match(video.embedUrl,/embed\/675520\/abc-123/);});
test('signature verifies exact resource and query; missing keys fail closed',()=>{const expiry=Math.floor(Date.now()/1000)+900,signed=cf.signedUrl(raw,expiry);assert.ok(signed.startsWith(raw+'&Expires='));const encoded=new URL(signed).searchParams.get('Signature').replace(/-/g,'+').replace(/_/g,'=').replace(/~/g,'/');const policy=JSON.stringify({Statement:[{Resource:raw,Condition:{DateLessThan:{'AWS:EpochTime':expiry}}}]});assert.equal(crypto.verify('RSA-SHA1',Buffer.from(policy),publicKey,Buffer.from(encoded,'base64')),true);assert.throws(()=>cf.signedUrl(raw,expiry,{CLOUDFRONT_ACCESS_MODE:'private'}),/needs/);});
function grant(){return cf.decodeGrant(new URL(cf.issueGrant(raw,{preview:true}).hlsUrl,'https://api.example').searchParams.get('grant'));}
test('nested playlists, keys, initialization files and segments covered',()=>{const g=grant(),output=cf.rewritePlaylist('#EXTM3U\n#EXT-X-STREAM-INF:BANDWIDTH=128000\nvariant\n#EXT-X-KEY:METHOD=AES-128,URI="key.bin"\n#EXT-X-MAP:URI="init.mp4"\n#EXTINF:6,\nPart%20One.ts?x=A%2fb\n',g);const nested=cf.decodeGrant(new URL(output.split('\n')[2],'https://api.example').searchParams.get('grant'));assert.equal(nested.reference,raw);assert.match(nested.url,/\/variant$/);assert.match(output,/key.bin\?Expires=/);assert.match(output,/init.mp4\?Expires=/);assert.match(output,/Part%20One.ts\?x=A%2fb&Expires=/);assert.equal(output.includes('PRIVATE KEY'),false);assert.throws(()=>cf.rewritePlaylist('#EXTM3U\n../other.ts',g),/escapes/);assert.throws(()=>cf.rewritePlaylist('#EXTM3U\nhttps://evil.example/a.ts',g),/outside/);assert.throws(()=>cf.decodeGrant('invalid'));});
test('fetch bounded and errors actionable',async()=>{const g=grant();await assert.rejects(cf.fetchPlaylist(g,async()=>new Response('forbidden',{status:403})),/HTTP 403/);await assert.rejects(cf.fetchPlaylist(g,async()=>new Response('not a playlist')),/valid HLS/);await assert.rejects(cf.fetchPlaylist(g,async()=>new Response('',{headers:{'content-length':1048577}})),/1 MB/);await cf.fetchPlaylist(g,async(_url,options)=>{assert.equal(options.redirect,'error');return new Response('#EXTM3U\npart.ts');});});
test('bulk import ordering, mixed providers, exact URLs and duplicate errors',async()=>{const code=fs.readFileSync(require('node:path').join(__dirname,'../../edunex-f/src/pages/admin/videoForm.js'));const form=await import(`data:text/javascript;base64,${code.toString('base64')}`);const result=form.importLessons(`2. AWS | ${raw}\n1. Bunny\n${bunny}`);assert.equal(result[1].videoUrl,raw);assert.equal(result[0].title,'Bunny');assert.equal(form.videoError(result[1]),'');assert.throws(()=>form.importLessons(`1. One | ${raw}\n1. Two | ${raw}`),/unique/);});
test('reordering retains completion version and per-lesson coverage and resume',()=>{const videos=[{_id:'b',title:'B',duration:100,videoUrl:bunny},{_id:'a',title:'A',duration:100,videoUrl:raw}];assert.equal(rules.manifest({videos}).version,rules.manifest({videos:[...videos].reverse(),completionOrder:videos.map(v=>v._id)}).version);const e=rules.eligibility({videos:rules.manifest({videos}).videos,rows:[{videoId:'a',position:92,intervals:[[0,92]]}],user:{isMobileVerified:true,fullName:'Test'}});assert.equal(e.lessons.find(v=>v.id==='a').complete,true);assert.equal(e.lessons.find(v=>v.id==='a').resumePosition,92);assert.equal(e.lessons.find(v=>v.id==='b').complete,false);});
test('playback endpoint preserves admin protection, subscription checks and course ownership',async()=>{
 const routes=[],admin=()=>{},auth=()=>{};let allowed=true,course={_id:'course',videos:[{_id:'video',provider:'aws_cloudfront',videoUrl:raw}]};
 const context={module:{exports:{}},process,URL,require(name){if(name==='express')return {Router:()=>({get:(...args)=>routes.push(args),post:(...args)=>routes.push(args)})};if(name.endsWith('compatAuth'))return {requireCompatibleAuth:()=>auth};if(name.endsWith('adminAuth'))return {protectAdmin:admin};if(name.endsWith('certificationService'))return {access:async()=>{if(!allowed)throw Object.assign(new Error('Subscription required'),{statusCode:403});}};if(name.endsWith('/Course'))return {findOne:query=>{assert.equal(query.status,'published');return {select:projection=>{assert.match(projection,/-videos\.thumbnail/);assert.match(projection,/-thumbnailHorizontal/);return {lean:async()=>course};}};}};if(name.endsWith('/User'))return {};if(name.endsWith('videoSources'))return source;if(name.endsWith('cloudFrontPlayback'))return cf;throw Error(name);}};
 vm.runInNewContext(fs.readFileSync(require.resolve('../routes/playback'),'utf8'),context);
 assert.equal(routes.find(r=>r[0]==='/admin/playback-preview')[1],admin);
 const route=routes.find(r=>r[0].endsWith('/playback-access'));assert.equal(route[1],auth);
 async function call(videoId='video'){const res={code:200,set(){return this;},status(code){this.code=code;return this;},json(data){this.data=data;return this;}};await route[2]({params:{courseId:'course',videoId},compatUser:{_id:'user'},compatAuth:{sessionId:'session'}},res);return res;}
 assert.equal((await call()).code,200);assert.equal((await call('foreign')).code,404);allowed=false;assert.equal((await call()).code,403);allowed=true;course=null;assert.equal((await call()).code,404);
});
